### ISSUE TITLE
im trying to test the ai on my local pc and i cant get it to work

### ISSUE THREAD

**Issue by ZDaPlaY** [CompVis/stable-diffusion#104]
im trying to test the ai on my local pc and i cant get it to work

E:\IA-Local\stable-diffusion-main>set /P id=Enter Prompt And Options :
Enter Prompt And Options : --prompt "a dog photo"

E:\IA-Local\stable-diffusion-main>python "scripts\txt2img.py" --ckpt "model 1.3.ckpt" --config "configs\stable-diffusion\v1-inference.yaml" --prompt "a dog photo"
Traceback (most recent call last):
  File "E:\IA-Local\stable-diffusion-main\scripts\txt2img.py", line 17, in <module>
    from ldm.util import instantiate_from_config
  File "C:\Users\zhixi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\ldm.py", line 20
    print self.face_rec_model_path
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)?

**Comment by RomanADavis** [comment]
Maybe it's assuming python 2?

**Comment by EiderFC** [comment]
No, python 3.10

**Comment by breadbrowser** [comment]
just this https://huggingface.co/spaces/stabilityai/stable-diffusion

**Comment by smoran** [comment]
Do you run it inside a Conda terminal?

**Comment by Hypero** [comment]
Copy the file txt2img.py to the root folder of the project (for you it should be E:\IA-Local\stable-diffusion-main) and start it from there:
"python "txt2img.py" --ckpt "model 1.3.ckpt" --config "configs\stable-diffusion\v1-inference.yaml" --prompt "a dog photo"

**Comment by TnnsBeast** [comment]
> 

Did you find an answer for this?
