### ISSUE TITLE
something wrong with text2image

### ISSUE THREAD

**Issue by whdcwsj** [CompVis/stable-diffusion#126]
I set image height to 384, width to 608, they are all multiples of 8, requirements are met:
code: [batch_size, self.opt.C, height // self.opt.f, width // self.opt.f]

But I get the problem as follows:

~~~Stable Diffusion完整模型加载完成~~~

text:a cute cat, trending on artstation
Global seed set to 6
Sampling:   0%|                                                                                                                           | 0/1 [00:00<?, ?it/s]
Data shape for PLMS sampling is (3, 4, 48, 76)                                                                                            | 0/1 [00:00<?, ?it/s]
Running PLMS Sampling with 50 timesteps
PLMS Sampler:   0%|                                                                                                                      | 0/50 [00:00<?, ?it/s]
data:   0%|                                                                                                                               | 0/1 [00:01<?, ?it/s]
Sampling:   0%|                                                                                                                           | 0/1 [00:01<?, ?it/s]
Traceback (most recent call last):
  File "text2image_inference.py", line 323, in <module>
    image_path_list, inference_time = model.predict(text_prompt="a cute cat, trending on artstation",
  File "text2image_inference.py", line 245, in predict
    samples_ddim, _ = self.sampler.sample(S=self.opt.ddim_steps,
  File "/opt/conda/envs/ldm/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/data/juicefs_hz_cv_v3/11153568/stable-diffusion/stable-diffusion-main/ldm/models/diffusion/plms.py", line 97, in sample
    samples, intermediates = self.plms_sampling(conditioning, size,
  File "/opt/conda/envs/ldm/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/data/juicefs_hz_cv_v3/11153568/stable-diffusion/stable-diffusion-main/ldm/models/diffusion/plms.py", line 152, in plms_sampling
    outs = self.p_sample_plms(img, cond, ts, index=index, use_original_steps=ddim_use_original_steps,
  File "/opt/conda/envs/ldm/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/data/juicefs_hz_cv_v3/11153568/stable-diffusion/stable-diffusion-main/ldm/models/diffusion/plms.py", line 218, in p_sample_plms
    e_t = get_model_output(x, t)
  File "/data/juicefs_hz_cv_v3/11153568/stable-diffusion/stable-diffusion-main/ldm/models/diffusion/plms.py", line 185, in get_model_output
    e_t_uncond, e_t = self.model.apply_model(x_in, t_in, c_in).chunk(2)
  File "/data/juicefs_hz_cv_v3/11153568/stable-diffusion/stable-diffusion-main/ldm/models/diffusion/ddpm.py", line 987, in apply_model
    x_recon = self.model(x_noisy, t, **cond)
  File "/opt/conda/envs/ldm/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/data/juicefs_hz_cv_v3/11153568/stable-diffusion/stable-diffusion-main/ldm/models/diffusion/ddpm.py", line 1410, in forward
    out = self.diffusion_model(x, t, context=cc)
  File "/opt/conda/envs/ldm/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/data/juicefs_hz_cv_v3/11153568/stable-diffusion/stable-diffusion-main/ldm/modules/diffusionmodules/openaimodel.py", line 746, in forward
    h = th.cat([h, hs.pop()], dim=1)
RuntimeError: Sizes of tensors must match except in dimension 1. Expected size 20 but got size 19 for tensor number 1 in the list.

How to fix it?

**Comment by fat-tire** [comment]
Need to be multiples of 64
