### ISSUE TITLE
Call to print error

### ISSUE THREAD

**Issue by Zondakage** [CompVis/stable-diffusion#130]
Any ideas on how to fix this?

Traceback (most recent call last):
  File "C:\Users\KageStudio\stable-diffusion\scripts\txt2img.py", line 17, in <module>
    from ldm.util import instantiate_from_config
  File "C:\Users\KageStudio\AppData\Roaming\Python\Python39\site-packages\ldm.py", line 20
    print self.face_rec_model_path
          ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(self.face_rec_model_path)?
(ldm) PS C:\Users\KageStudio>

**Comment by qexat** [comment]
`ldm.py` seems to use the Python 2 syntax for printing, but apparently you are in Python 3.9

**Comment by qexat** [comment]
I checked and sadly `ldm` does not have a Python 3 compatible version... seems outdated and abandoned :(

**Comment by ClayShoaf** [comment]
Is there any plan to update this or should I just run python 2 in a virtual environment?
