### ISSUE TITLE
No such file or directory: 'models/ldm/stable-diffusion-v1/model.ckpt'

### ISSUE THREAD

**Issue by sebademasi10** [CompVis/stable-diffusion#159]
Hello everyone

When I run the sample script: 

```bash
 python scripts/txt2img.py --prompt "a photograph of an astronaut riding a horse" --plms
```
I get the following: 

```bash
Loading model from models/ldm/stable-diffusion-v1/model.ckpt
Traceback (most recent call last):
  File "scripts/txt2img.py", line 344, in <module>
    main()
  File "scripts/txt2img.py", line 240, in main
    model = load_model_from_config(config, f"{opt.ckpt}")
  File "scripts/txt2img.py", line 50, in load_model_from_config
    pl_sd = torch.load(ckpt, map_location="cpu")
  File "/home/sebastian/anaconda3/envs/ldm/lib/python3.8/site-packages/torch/serialization.py", line 699, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/home/sebastian/anaconda3/envs/ldm/lib/python3.8/site-packages/torch/serialization.py", line 231, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/home/sebastian/anaconda3/envs/ldm/lib/python3.8/site-packages/torch/serialization.py", line 212, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'models/ldm/stable-diffusion-v1/model.ckpt'
```
I've already downloaded the weights: 
```bash
$ ll sd-v1-4.ckpt 
-rw-rw-r-- 1 sebastian sebastian 4265380512 sep  1 11:48 sd-v1-4.ckpt
```
And linked in the corresponding directory:
```bash
$ ll models/ldm/stable-diffusion-v1/
total 8
drwxrwxr-x 2 sebastian sebastian 4096 sep  1 11:56 ./
drwxrwxr-x 3 sebastian sebastian 4096 sep  1 11:56 ../
lrwxrwxrwx 1 sebastian sebastian   12 sep  1 11:56 model.ckpt -> sd-v1-4.ckpt
```
What am I doing wrong? Thanks in advance.

**Comment by sebademasi10** [comment]
I solved this issue by using directly the `sd-v1-4.ckpt` renamed as `model.ckpt` inside `models/ldm/stable-diffusion-v1/`

**Comment by danieldaugherty** [comment]
I believe this is not solved, since the README still says to `ln -s` the model file...

**Comment by ThadeuFerreira** [comment]
I got the same problem after I copy the Colab notbook to my personal Google Drive.

**Comment by deanxizian** [comment]
This issue can be solved by using absolute paths instead of relative paths when using `ln -s`.
