### ISSUE TITLE
UnpicklingError when using model

### ISSUE THREAD

**Issue by BoazKG93** [CompVis/stable-diffusion#169]
I've followed the guide to start, set up my conda ldm environment without a problem, downloaded the original weight model, and then when running the example prompt I'm getting this error. Any idea what went wrong?
```
(ldm) ubuntu@ip-172-31-54-51:~/stable-diffusion-main$ python scripts/txt2img.py --prompt "a photograph of an astronaut riding a horse" --plms 
Global seed set to 42
Loading model from models/ldm/stable-diffusion-v1/model.ckpt
Traceback (most recent call last):
  File "scripts/txt2img.py", line 344, in <module>
    main()
  File "scripts/txt2img.py", line 240, in main
    model = load_model_from_config(config, f"{opt.ckpt}")
  File "scripts/txt2img.py", line 50, in load_model_from_config
    pl_sd = torch.load(ckpt, map_location="cpu")
  File "/home/ubuntu/.conda/envs/ldm/lib/python3.8/site-packages/torch/serialization.py", line 713, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/home/ubuntu/.conda/envs/ldm/lib/python3.8/site-packages/torch/serialization.py", line 920, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, 'v'.
```

**Comment by hkiang01** [comment]
I'm guessing it's trying to read the git lfs config vs the actual checkpoint file and is picking 'v' as in 'version'. I ran into that as well.

**Comment by hkiang01** [comment]
From https://huggingface.co/CompVis/stable-diffusion-v1-4/tree/main you just have clone the weights using lfs

```
git lfs install
git clone https://huggingface.co/CompVis/stable-diffusion-v1-4
```

**Comment by convexalpha** [comment]
How did you solve it?

**Comment by tzwel** [comment]
"I ran into that as well"
very helpful
