### ISSUE TITLE
Running examples after linking `sd-v1-3.ckpt` causes error

### ISSUE THREAD

**Issue by akhilsathuluri** [CompVis/stable-diffusion#19]
The `scripts/txt2img.py` identifies the `ckpt` but throws an error while loading it,
```
Global seed set to 42
Loading model from models/ldm/stable-diffusion-v1/model.ckpt
Traceback (most recent call last):
  File "scripts/txt2img.py", line 279, in <module>
    main()
  File "scripts/txt2img.py", line 188, in main
    model = load_model_from_config(config, f"{opt.ckpt}")
  File "scripts/txt2img.py", line 27, in load_model_from_config
    pl_sd = torch.load(ckpt, map_location="cpu")
  File "/home/asathuluri/anaconda3/envs/ldm/lib/python3.8/site-packages/torch/serialization.py", line 713, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/home/asathuluri/anaconda3/envs/ldm/lib/python3.8/site-packages/torch/serialization.py", line 920, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, 'v'.

```
Is there a compatibility issue between this branch and the checkpoint used?

**Comment by akhilsathuluri** [comment]
Ah, `git-lfs` didnt download the complete model as expected. Downloading it manually did the trick.
