### ISSUE TITLE
AttributeError: module 'ldm.modules.encoders.modules' has no attribute 'FrozenCLIPEmbedder'

### ISSUE THREAD

**Issue by sike2017** [CompVis/stable-diffusion#190]
```
Global seed set to 42
Loading model from models/ldm/stable-diffusion-v1/model.ckpt
Global Step: 470000
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
making attention of type 'vanilla' with 512 in_channels
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
making attention of type 'vanilla' with 512 in_channels
Traceback (most recent call last):
  File "d:\code\stable-diffusion\scripts\img2img.py", line 293, in <module>
    main()
  File "d:\code\stable-diffusion\scripts\img2img.py", line 200, in main
    model = load_model_from_config(config, f"{opt.ckpt}")
  File "d:\code\stable-diffusion\scripts\img2img.py", line 34, in load_model_from_config
    model = instantiate_from_config(config.model)
  File "D:\ProgramData\Anaconda3\envs\dmodel2\lib\site-packages\ldm\util.py", line 78, in instantiate_from_config
    return get_obj_from_str(config["target"])(**config.get("params", dict()))
  File "D:\ProgramData\Anaconda3\envs\dmodel2\lib\site-packages\ldm\models\diffusion\ddpm.py", line 461, in __init__
    self.instantiate_cond_stage(cond_stage_config)
  File "D:\ProgramData\Anaconda3\envs\dmodel2\lib\site-packages\ldm\models\diffusion\ddpm.py", line 519, in instantiate_cond_stage
    model = instantiate_from_config(config)
  File "D:\ProgramData\Anaconda3\envs\dmodel2\lib\site-packages\ldm\util.py", line 78, in instantiate_from_config
    return get_obj_from_str(config["target"])(**config.get("params", dict()))
  File "D:\ProgramData\Anaconda3\envs\dmodel2\lib\site-packages\ldm\util.py", line 86, in get_obj_from_str
    return getattr(importlib.import_module(module, package=None), cls)
AttributeError: module 'ldm.modules.encoders.modules' has no attribute 'FrozenCLIPEmbedder'
```

**Comment by KleinXin** [comment]
Any one knows how to solve this issue？

**Comment by KleinXin** [comment]
It is said this issue is solved in this post

https://github.com/CompVis/stable-diffusion/issues/59

I tried the method they mentioned, but the problem is still unsolved.

**Comment by TheLastBen** [comment]
copy the folder **ldm** from the main repo to the folder : **scripts**

**Comment by KleinXin** [comment]
> Copy the folder **ldm** from the main repo to the folder : **scripts**

thx

After deleting /opt/conda/lib/python3.8/site-packages/ldm/ , copying ldm folder in the main repo to /opt/conda/lib/python3.8/site-packages/ldm/ and comment the 4th line of  /opt/conda/lib/python3.8/site-packages/ldm/modules/encoders/modules.py where clip is imported, the demo can run successfully.

By the way, pytorch 1.11.0 with cuda 10.2 is needed.

@sike2017 You can also try this method.

**Comment by sike2017** [comment]
I’ve already solve this problem successfully. Thank you very much.


发件人: ***@***.***>
发送时间: 2022年9月23日 00:22:40
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [CompVis/stable-diffusion] AttributeError: module 'ldm.modules.encoders.modules' has no attribute 'FrozenCLIPEmbedder' (Issue #190)


Copy the folder ldm from the main repo to the folder : scripts

thx

After deleting /opt/conda/lib/python3.8/site-packages/ldm/ , copying ldm folder in the main repo to /opt/conda/lib/python3.8/site-packages/ldm/ and comment the 4th line of /opt/conda/lib/python3.8/site-packages/ldm/modules/encoders/modules.py where clip is imported, the demo can run successfully.

By the way, pytorch 1.11.0 with cuda 10.2 is needed.

@sike2017<https://github.com/sike2017> You can also try this method.

―

**Comment by TheLastBen** [comment]
Does at prevent the Webui from functioning  ?

**Comment by vfyang** [comment]
With out the fix, the webui.py failed to load and quit.

> 

With fixing it, the webui.py filed to load

**Comment by CyrusWang57** [comment]
> 

it works!!! thanks very much!!

**Comment by CyrusWang57** [comment]
> 我发现了问题： 升级（更新代码）后，我得到了两个编码器文件夹： ./ldm/modules/encoders ./src/latent-diffusion/ldm/modules/encoders两个 都有modules.py，一个是8K另一个4K。不一致。
> 
> 我通过删除 ./src/latent-diffusion/ldm/modules/encoders 解决了这个问题。（实际上将 ./ldm/modules/encoders 复制到 ./src/latent-diffusion/ldm/modules/encoders 上也可以解决问题。
> 
> 修复代码并使其保持一致会很好。


it works!!! thanks very much!!

**Comment by zsh2000** [comment]
For me, it is because some inconsistency of several code versions. For some versions, the class is called FrozenCLIPEmbedder, with "models" having default value "ViT-L/14". For others, it is called FrozenClipEmbedder, with no default value for "model".

**Comment by Kittensx** [comment]
The actual fix to this is a bit more complicated than  let's get rid of the error message so the program will load. If thats all you want to do, then you won't actually get it to work.

You need to download the correct LDM and the correct clip. These aren't versions that are in PIP install. The correct version of clip has load and it is located here: https://github.com/openai/CLIP . The best way to get what you need is just to clone it into a folder, and find the files you need and paste it in your venv. 

For LDM it's a bit more complicated. Same principle: you need to go here: https://github.com/CompVis/latent-diffusion 

and grab what you need. You'll have to edit some things.

At some point you'll need to grab what you need from taming: https://github.com/CompVis/taming-transformers/tree/master/taming/modules 

For quantizer which you'll place inside next to ldm/models/autoencoder you can find it here: https://github.com/MishaLaskin/vqvae/blob/d761a999e2267766400dc646d82d3ac3657771d4/models/quantizer.py 

you'll need to use a local import: at the top of autoencoder: from .quantize import VectorQuantizer2 as VectorQuantizer

inside ldm/modules/encoders you'll need to find clip from before and drop it in here. It's best to clone into that repository. You'll want to grab these too: clip, model, and simple tokenizer. Inside modules all you'll need to do is do a local import and i found the best way to grab load is to do it like this: from .clip import load as d_clip

next, anywhere in this file where you see clip.load you'll need to replace it with "d_clip" because that's what you imported it as. You can import as "anything you want" but I decided to use d_clip. 

You will also need to import tokenize, i did both like this:
from .clip import load as d_clip
from .clip import tokenize as t_clip

Then anywhere in this file where you see clip.load replace with d_clip.
Anywhere in this file where you see clip.tokenize replace with t_clip.

You will also need to find this file: https://github.com/openai/CLIP/blob/main/clip/bpe_simple_vocab_16e6.txt.gz and put it in the same place with clip, model, and simple tokenizer. 

That should fix your problems here. Next up on the list - fixing torch\amp\autocast_mode.py", line 361, in __enter__
    torch.set_autocast_enabled(self.device, self._enabled)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: set_autocast_enabled(): argument 'enabled' (position 2) must be bool, not str....but that's all for me for today. Good luck all!


Edit: 
I forgot to add this - inside modules.py - somewhere down the line they are looking for: FrozenCLIPEmbedder --- but I couldn't find the program that needed that so I could correct it to FrozenCLIPtextEmbedder. So I took the cowards way out and just duplicated the code for the text embedder and named it what the program wanted. 

So that fix was copying the entire class of FrozenCLIPTextEmbedder pasting it below, then renaming it as FrozenCLIPEmbedder . ... And then all the errors fixed above, to get the program to run a little more. 

I ended up fixing the entire thing wrong with LDM and Clip but we're moving on to torch\amp\autocast_mode :)
