### ISSUE TITLE
img2img.py get an error

### ISSUE THREAD

**Issue by Kiode** [CompVis/stable-diffusion#191]
Traceback (most recent call last):
  File "img2img.py", line 293, in <module>
    main()
  File "img2img.py", line 261, in main
    samples = sampler.decode(z_enc, c, t_enc, unconditional_guidance_scale=opt.scale,
  File "/public/yangxi/anaconda3/envs/ldm/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/public/yangxi/stable-diffusion/ldm/models/diffusion/ddim.py", line 238, in decode
    x_dec, _ = self.p_sample_ddim(x_dec, cond, ts, index=index, use_original_steps=use_original_steps,
  File "/public/yangxi/anaconda3/envs/ldm/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/public/yangxi/stable-diffusion/ldm/models/diffusion/ddim.py", line 177, in p_sample_ddim
    e_t_uncond, e_t = self.model.apply_model(x_in, t_in, c_in).chunk(2)
  File "/public/yangxi/stable-diffusion/ldm/models/diffusion/ddpm.py", line 987, in apply_model
    x_recon = self.model(x_noisy, t, **cond)
  File "/public/yangxi/anaconda3/envs/ldm/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/public/yangxi/stable-diffusion/ldm/models/diffusion/ddpm.py", line 1410, in forward
    out = self.diffusion_model(x, t, context=cc)
  File "/public/yangxi/anaconda3/envs/ldm/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/public/yangxi/stable-diffusion/ldm/modules/diffusionmodules/openaimodel.py", line 736, in forward
    h = th.cat([h, hs.pop()], dim=1)
RuntimeError: Sizes of tensors must match except in dimension 1. Expected size 12 but got size 11 for tensor number 1 in the list.

**Comment by BeaverInGreenland** [comment]
What are the dimensions of your input image ?

**Comment by Kiode** [comment]
> What are the dimensions of your input image ?

(Pdb) init_image.shape
torch.Size([1, 3, 352, 288])

**Comment by junpengqiu** [comment]
> 

the example demonstrated in README does not use a squared image though

**Comment by emersondelemmus** [comment]
@Kiode The image dimensions need to be a multiple of 64!
