### ISSUE TITLE
please Help with this error

### ISSUE THREAD

**Issue by DataPharmacy** [CompVis/stable-diffusion#205]
python scripts/txt2img.py --prompt "god" --plms --ckpt sd-v1-4.ckpt --skip_grid --n_samples 1

Global seed set to 42
Loading model from sd-v1-4.ckpt
Traceback (most recent call last):
  File "scripts/txt2img.py", line 344, in <module>
    main()
  File "scripts/txt2img.py", line 240, in main
    model = load_model_from_config(config, f"{opt.ckpt}")
  File "scripts/txt2img.py", line 50, in load_model_from_config
    pl_sd = torch.load(ckpt, map_location="cpu")
  File "/home/useradd/anaconda3/envs/ldm/lib/python3.8/site-packages/torch/serialization.py", line 713, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/home/useradd/anaconda3/envs/ldm/lib/python3.8/site-packages/torch/serialization.py", line 920, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, 'W'.

**Comment by Shroototem** [comment]
Same issue here!

**Comment by ParthGaneriwala** [comment]
Try downloading ```sd-v1-4.ckpt``` file again. 
```_pickle.UnpicklingError``` is an error when the file it is loading is broken. Download the file again and make sure the ```sha256sum``` is the same.

**Comment by DataPharmacy** [comment]
yes

> Try downloading `sd-v1-4.ckpt` file again. `_pickle.UnpicklingError` is an error when the file it is loading is broken. Download the file again and make sure the `sha256sum` is the same.

thanks for your response I think you're right because the file sd-v1-4.ckpt in my directory was only 1kb so I think it is broken need to download again, Here is a download link:
https://www.googleapis.com/storage/v1/b/aai-blog-files/o/sd-v1-4.ckpt?alt=media

**Comment by Devopsik404** [comment]
Try to use python 3.9 and above, this error does not occur there.

**Comment by aleff-github** [comment]
Try to solve like this https://github.com/CompVis/stable-diffusion/issues/432
