### ISSUE TITLE
no module named 'torch.ao'

### ISSUE THREAD

**Issue by prismspecs** [CompVis/stable-diffusion#229]
`python scripts/txt2img.py --prompt "a photograph of a huge bear, style of TIME magazine" --plms 
/home/grayson/miniconda3/envs/ldm/lib/python3.8/site-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: libtorch_cuda_cu.so: cannot open shared object file: No such file or directory
  warn(f"Failed to load image Python extension: {e}")
Traceback (most recent call last):
  File "scripts/txt2img.py", line 11, in <module>
    from torchvision.utils import make_grid
  File "/home/grayson/miniconda3/envs/ldm/lib/python3.8/site-packages/torchvision/__init__.py", line 7, in <module>
    from torchvision import models
  File "/home/grayson/miniconda3/envs/ldm/lib/python3.8/site-packages/torchvision/models/__init__.py", line 18, in <module>
    from . import quantization
  File "/home/grayson/miniconda3/envs/ldm/lib/python3.8/site-packages/torchvision/models/quantization/__init__.py", line 1, in <module>
    from .mobilenet import *
  File "/home/grayson/miniconda3/envs/ldm/lib/python3.8/site-packages/torchvision/models/quantization/mobilenet.py", line 1, in <module>
    from .mobilenetv2 import QuantizableMobileNetV2, mobilenet_v2, __all__ as mv2_all
  File "/home/grayson/miniconda3/envs/ldm/lib/python3.8/site-packages/torchvision/models/quantization/mobilenetv2.py", line 5, in <module>
    from torch.ao.quantization import QuantStub, DeQuantStub
ModuleNotFoundError: No module named 'torch.ao'
`

**Comment by str1der1** [comment]
Also hitting this issue

**Comment by yunbingbing** [comment]
me too! did you solve this problem?

**Comment by davide-coccomini** [comment]
Me too
