### ISSUE TITLE
chcp problem.

### ISSUE THREAD

**Issue by ExterrMatt** [CompVis/stable-diffusion#235]
I get this issue in the cmd after I run the 'conda env create -f environment.yaml' command

`Pip subprocess error:
'chcp' is not recognized as an internal or external command,
operable program or batch file.
'chcp' is not recognized as an internal or external command,
operable program or batch file.
'chcp' is not recognized as an internal or external command,
operable program or batch file.

failed

CondaEnvException: Pip failed`

**Comment by David-337** [comment]
Same here, it appears to be an issue with the "taming transformers" package...

`Installing pip dependencies: \ Ran pip subprocess with arguments:
['/opt/conda/envs/ldm/bin/python', '-m', 'pip', 'install', '-U', '-r', '/dockerx/rocm/stable-diffusion/condaenv.og0g7t8_.requirements.txt']
Pip subprocess output:
Obtaining taming-transformers from git+https://github.com/CompVis/taming-transformers.git@master#egg=taming-transformers (from -r /dockerx/rocm/stable-diffusion/condaenv.og0g7t8_.requirements.txt (line 17))

Pip subprocess error:
ERROR: Exception:
Traceback (most recent call last):
  File "/opt/conda/envs/ldm/lib/python3.8/site-packages/pip/_vendor/resolvelib/resolvers.py", line 171, in _merge_into_criterion
    crit = self.state.criteria[name]
KeyError: 'taming-transformers'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/envs/ldm/lib/python3.8/site-packages/pip/_internal/vcs/git.py", line 322, in get_remote_url
    found_remote = remotes[0]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/envs/ldm/lib/python3.8/site-packages/pip/_internal/cli/base_command.py", line 224, in _main
    status = self.run(options, args)
  File "/opt/conda/envs/ldm/lib/python3.8/site-packages/pip/_internal/cli/req_command.py", line 180, in wrapper
    return func(self, options, args)
  File "/opt/conda/envs/ldm/lib/python3.8/site-packages/pip/_internal/commands/install.py", line 320, in run
    requirement_set = resolver.resolve(
  File "/opt/conda/envs/ldm/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 121, in resolve
    self._result = resolver.resolve(
  File "/opt/conda/envs/ldm/lib/python3.8/site-packages/pip/_vendor/resolvelib/resolvers.py", line 445, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "/opt/conda/envs/ldm/lib/python3.8/site-packages/pip/_vendor/resolvelib/resolvers.py", line 310, in resolve
    name, crit = self._merge_into_criterion(r, parent=None)
  File "/opt/conda/envs/ldm/lib/python3.8/site-packages/pip/_vendor/resolvelib/resolvers.py", line 173, in _merge_into_criterion
    crit = Criterion.from_requirement(self._p, requirement, parent)
  File "/opt/conda/envs/ldm/lib/python3.8/site-packages/pip/_vendor/resolvelib/resolvers.py", line 79, in from_requirement
    cands = build_iter_view(provider.find_matches([requirement]))
  File "/opt/conda/envs/ldm/lib/python3.8/site-packages/pip/_vendor/resolvelib/structs.py", line 148, in build_iter_view
    matches = list(matches)
  File "/opt/conda/envs/ldm/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 255, in <genexpr>
    if constraint.is_satisfied_by(c)
  File "/opt/conda/envs/ldm/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/base.py", line 66, in is_satisfied_by
    return self.specifier.contains(candidate.version, prereleases=True)
  File "/opt/conda/envs/ldm/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 194, in version
    self._version = self.dist.parsed_version
  File "/opt/conda/envs/ldm/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 239, in dist
    self._prepare()
  File "/opt/conda/envs/ldm/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 226, in _prepare
    dist = self._prepare_distribution()
  File "/opt/conda/envs/ldm/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 346, in _prepare_distribution
    return self._factory.preparer.prepare_editable_requirement(self._ireq)
  File "/opt/conda/envs/ldm/lib/python3.8/site-packages/pip/_internal/operations/prepare.py", line 573, in prepare_editable_requirement
    req.update_editable(self.download_dir is None)
  File "/opt/conda/envs/ldm/lib/python3.8/site-packages/pip/_internal/req/req_install.py", line 655, in update_editable
    vcs_backend.obtain(self.source_dir, url=hidden_url)
  File "/opt/conda/envs/ldm/lib/python3.8/site-packages/pip/_internal/vcs/versioncontrol.py", line 654, in obtain
    existing_url = self.get_remote_url(dest)
  File "/opt/conda/envs/ldm/lib/python3.8/site-packages/pip/_internal/vcs/git.py", line 324, in get_remote_url
    raise RemoteNotFoundError
pip._internal.vcs.versioncontrol.RemoteNotFoundError

failed

CondaEnvException: Pip failed
`

**Comment by Aupuma** [comment]
Same problem here

**Comment by scythe000** [comment]
Same
