### ISSUE TITLE
TypeError when trying to run

### ISSUE THREAD

**Issue by Zenahr** [CompVis/stable-diffusion#246]
Stacktrace:

```
(ldm) C:\SoftwareDevelopment\StabilityAI\stable-diffusion>python scripts/txt2img.py --prompt "cat" --precision=full 
Global seed set to 42
Loading model from models/ldm/stable-diffusion-v1/model.ckpt
Global Step: 470000
Traceback (most recent call last):
  File "scripts/txt2img.py", line 344, in <module>
    main()
  File "scripts/txt2img.py", line 240, in main
    model = load_model_from_config(config, f"{opt.ckpt}")
  File "scripts/txt2img.py", line 54, in load_model_from_config
    model = instantiate_from_config(config.model)
  File "c:\softwaredevelopment\stabilityaiextended\stable-diffusion\ldm\util.py", line 89, in instantiate_from_config
    return get_obj_from_str(config['target'])(
TypeError: __init__() missing 1 required positional argument: 'personalization_config'
```

**Comment by Zenahr** [comment]
Recreating the env solved the problem.
