### ISSUE TITLE
What's the problem?

### ISSUE THREAD

**Issue by doraam** [CompVis/stable-diffusion#262]
`
(ldm) D:\codes\github\stable-diffusion>python scripts/txt2img.py --prompt "a photograph of an astronaut riding a horse" --plms
Traceback (most recent call last):
  File "D:\programs\Anaconda3\envs\ldm\lib\site-packages\urllib3\connectionpool.py", line 700, in urlopen
    self._prepare_proxy(conn)
  File "D:\programs\Anaconda3\envs\ldm\lib\site-packages\urllib3\connectionpool.py", line 996, in _prepare_proxy
    conn.connect()
  File "D:\programs\Anaconda3\envs\ldm\lib\site-packages\urllib3\connection.py", line 364, in connect
    self.sock = conn = self._connect_tls_proxy(hostname, conn)
  File "D:\programs\Anaconda3\envs\ldm\lib\site-packages\urllib3\connection.py", line 499, in _connect_tls_proxy
    socket = ssl_wrap_socket(
  File "D:\programs\Anaconda3\envs\ldm\lib\site-packages\urllib3\util\ssl_.py", line 453, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls)
  File "D:\programs\Anaconda3\envs\ldm\lib\site-packages\urllib3\util\ssl_.py", line 495, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock)
  File "D:\programs\Anaconda3\envs\ldm\lib\ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "D:\programs\Anaconda3\envs\ldm\lib\ssl.py", line 1040, in _create
    self.do_handshake()
  File "D:\programs\Anaconda3\envs\ldm\lib\ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
OSError: [Errno 0] Error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\programs\Anaconda3\envs\ldm\lib\site-packages\requests\adapters.py", line 489, in send
    resp = conn.urlopen(
  File "D:\programs\Anaconda3\envs\ldm\lib\site-packages\urllib3\connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "D:\programs\Anaconda3\envs\ldm\lib\site-packages\urllib3\util\retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /CompVis/stable-diffusion-safety-checker/resolve/main/preprocessor_config.json (Caused by ProxyError('Cannot connect to proxy.', OSError(0, 'Error')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\programs\Anaconda3\envs\ldm\lib\site-packages\transformers\feature_extraction_utils.py", line 403, in get_feature_extractor_dict
    resolved_feature_extractor_file = cached_path(
  File "D:\programs\Anaconda3\envs\ldm\lib\site-packages\transformers\utils\hub.py", line 282, in cached_path
    output_path = get_from_cache(
  File "D:\programs\Anaconda3\envs\ldm\lib\site-packages\transformers\utils\hub.py", line 485, in get_from_cache
    r = requests.head(url, headers=headers, allow_redirects=False, proxies=proxies, timeout=etag_timeout)
  File "D:\programs\Anaconda3\envs\ldm\lib\site-packages\requests\api.py", line 100, in head
    return request("head", url, **kwargs)
  File "D:\programs\Anaconda3\envs\ldm\lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "D:\programs\Anaconda3\envs\ldm\lib\site-packages\requests\sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "D:\programs\Anaconda3\envs\ldm\lib\site-packages\requests\sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "D:\programs\Anaconda3\envs\ldm\lib\site-packages\requests\adapters.py", line 559, in send
    raise ProxyError(e, request=request)
requests.exceptions.ProxyError: HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /CompVis/stable-diffusion-safety-checker/resolve/main/preprocessor_config.json (Caused by ProxyError('Cannot connect to proxy.', OSError(0, 'Error')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "scripts/txt2img.py", line 27, in <module>
    safety_feature_extractor = AutoFeatureExtractor.from_pretrained(safety_model_id)
  File "D:\programs\Anaconda3\envs\ldm\lib\site-packages\transformers\models\auto\feature_extraction_auto.py", line 270, in from_pretrained
    config_dict, _ = FeatureExtractionMixin.get_feature_extractor_dict(pretrained_model_name_or_path, **kwargs)
  File "D:\programs\Anaconda3\envs\ldm\lib\site-packages\transformers\feature_extraction_utils.py", line 443, in get_feature_extractor_dict
    raise EnvironmentError(
OSError: Can't load feature extractor for 'CompVis/stable-diffusion-safety-checker'. If you were trying to load it from 'https://huggingface.co/models', make sure you don't have a local directory with the same name. Otherwise, make sure 'CompVis/stable-diffusion-safety-checker' is the correct path to a directory containing a preprocessor_config.json file

`

**Comment by doraam** [comment]
Above it's the error reported while I run with vpn. This is the error while running without vpn:

(ldm) D:\codes\github\stable-diffusion>python scripts/txt2img.py --prompt "a photograph of an astronaut riding a horse" --plms
Global seed set to 42
Loading model from models/ldm/stable-diffusion-v1/model.ckpt
Global Step: 470000
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
making attention of type 'vanilla' with 512 in_channels
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
making attention of type 'vanilla' with 512 in_channels
Downloading: "https://github.com/DagnyT/hardnet/raw/master/pretrained/train_liberty_with_aug/checkpoint_liberty_with_aug.pth" to C:\Users\lms/.cache\torch\hub\checkpoints\checkpoint_liberty_with_aug.pth
Traceback (most recent call last):
  File "D:\programs\Anaconda3\envs\ldm\lib\urllib\request.py", line 1350, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "D:\programs\Anaconda3\envs\ldm\lib\http\client.py", line 1255, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "D:\programs\Anaconda3\envs\ldm\lib\http\client.py", line 1301, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "D:\programs\Anaconda3\envs\ldm\lib\http\client.py", line 1250, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "D:\programs\Anaconda3\envs\ldm\lib\http\client.py", line 1010, in _send_output
    self.send(msg)
  File "D:\programs\Anaconda3\envs\ldm\lib\http\client.py", line 950, in send
    self.connect()
  File "D:\programs\Anaconda3\envs\ldm\lib\http\client.py", line 1417, in connect
    super().connect()
  File "D:\programs\Anaconda3\envs\ldm\lib\http\client.py", line 921, in connect
    self.sock = self._create_connection(
  File "D:\programs\Anaconda3\envs\ldm\lib\socket.py", line 787, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "D:\programs\Anaconda3\envs\ldm\lib\socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11004] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "scripts/txt2img.py", line 344, in <module>
    main()
  File "scripts/txt2img.py", line 240, in main
    model = load_model_from_config(config, f"{opt.ckpt}")
  File "scripts/txt2img.py", line 54, in load_model_from_config
    model = instantiate_from_config(config.model)
  File "D:\codes\github\stable-diffusion\scripts\ldm\util.py", line 85, in instantiate_from_config
    return get_obj_from_str(config["target"])(**config.get("params", dict()))
  File "D:\codes\github\stable-diffusion\scripts\ldm\models\diffusion\ddpm.py", line 461, in __init__
    self.instantiate_cond_stage(cond_stage_config)
  File "D:\codes\github\stable-diffusion\scripts\ldm\models\diffusion\ddpm.py", line 519, in instantiate_cond_stage
    model = instantiate_from_config(config)
  File "D:\codes\github\stable-diffusion\scripts\ldm\util.py", line 85, in instantiate_from_config
    return get_obj_from_str(config["target"])(**config.get("params", dict()))
  File "D:\codes\github\stable-diffusion\scripts\ldm\util.py", line 93, in get_obj_from_str
    return getattr(importlib.import_module(module, package=None), cls)
  File "D:\programs\Anaconda3\envs\ldm\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "D:\codes\github\stable-diffusion\scripts\ldm\modules\encoders\modules.py", line 7, in <module>
    import kornia
  File "D:\programs\Anaconda3\envs\ldm\lib\site-packages\kornia\__init__.py", line 10, in <module>
    from . import (
  File "D:\programs\Anaconda3\envs\ldm\lib\site-packages\kornia\augmentation\__init__.py", line 43, in <module>
    from .container import AugmentationSequential, ImageSequential, PatchSequential, VideoSequential
  File "D:\programs\Anaconda3\envs\ldm\lib\site-packages\kornia\augmentation\container\__init__.py", line 1, in <module>
    from .augment import AugmentationSequential
  File "D:\programs\Anaconda3\envs\ldm\lib\site-packages\kornia\augmentation\container\augment.py", line 17, in <module>
    from .patch import PatchSequential
  File "D:\programs\Anaconda3\envs\ldm\lib\site-packages\kornia\augmentation\container\patch.py", line 9, in <module>
    from kornia.contrib.extract_patches import extract_tensor_patches
  File "D:\programs\Anaconda3\envs\ldm\lib\site-packages\kornia\contrib\__init__.py", line 4, in <module>
    from .image_stitching import ImageStitcher
  File "D:\programs\Anaconda3\envs\ldm\lib\site-packages\kornia\contrib\image_stitching.py", line 7, in <module>
    from kornia.feature import LocalFeatureMatcher, LoFTR
  File "D:\programs\Anaconda3\envs\ldm\lib\site-packages\kornia\feature\__init__.py", line 4, in <module>
    from .integrated import (
  File "D:\programs\Anaconda3\envs\ldm\lib\site-packages\kornia\feature\integrated.py", line 52, in <module>
    class LAFDescriptor(nn.Module):
  File "D:\programs\Anaconda3\envs\ldm\lib\site-packages\kornia\feature\integrated.py", line 65, in LAFDescriptor
    patch_descriptor_module: nn.Module = HardNet(True),
  File "D:\programs\Anaconda3\envs\ldm\lib\site-packages\kornia\feature\hardnet.py", line 66, in __init__
    pretrained_dict = torch.hub.load_state_dict_from_url(
  File "D:\programs\Anaconda3\envs\ldm\lib\site-packages\torch\hub.py", line 591, in load_state_dict_from_url
    download_url_to_file(url, cached_file, hash_prefix, progress=progress)
  File "D:\programs\Anaconda3\envs\ldm\lib\site-packages\torch\hub.py", line 457, in download_url_to_file
    u = urlopen(req)
  File "D:\programs\Anaconda3\envs\ldm\lib\urllib\request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "D:\programs\Anaconda3\envs\ldm\lib\urllib\request.py", line 531, in open
    response = meth(req, response)
  File "D:\programs\Anaconda3\envs\ldm\lib\urllib\request.py", line 640, in http_response
    response = self.parent.error(
  File "D:\programs\Anaconda3\envs\ldm\lib\urllib\request.py", line 563, in error
    result = self._call_chain(*args)
  File "D:\programs\Anaconda3\envs\ldm\lib\urllib\request.py", line 502, in _call_chain
    result = func(*args)
  File "D:\programs\Anaconda3\envs\ldm\lib\urllib\request.py", line 755, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "D:\programs\Anaconda3\envs\ldm\lib\urllib\request.py", line 525, in open
    response = self._open(req, data)
  File "D:\programs\Anaconda3\envs\ldm\lib\urllib\request.py", line 542, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "D:\programs\Anaconda3\envs\ldm\lib\urllib\request.py", line 502, in _call_chain
    result = func(*args)
  File "D:\programs\Anaconda3\envs\ldm\lib\urllib\request.py", line 1393, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "D:\programs\Anaconda3\envs\ldm\lib\urllib\request.py", line 1353, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 11004] getaddrinfo failed>

**Comment by Ouro17** [comment]
Seems not able to connect to some place.
Did you install all your dependencies before running?

**Comment by tariqshams** [comment]
how did you install/build it @doraam and is all of your python setup on windows through anaconda ?

**Comment by Zov9** [comment]
Problem solved? Same problem.

**Comment by o5f2y** [comment]
Same problem

**Comment by euuen** [comment]
seam long problem

**Comment by fangmuyuan** [comment]
same problem
