### ISSUE TITLE
Hit issue running img2img.py

### ISSUE THREAD

**Issue by sandgrules** [CompVis/stable-diffusion#268]
I've been able to run text2img.py successfully a number of times, but when I try to run img2img.py I get the following error:
RuntimeError: Sizes of tensors must match except in dimension 1. Expected size 6 but got size 5 for tensor number 1 in the list.

Full stack trace: 
Sampling:   0%|                                                                                                                                                                                             | 0/1 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "scripts/img2img.py", line 294, in <module>
    main()
  File "scripts/img2img.py", line 262, in main
    samples = sampler.decode(z_enc, c, t_enc, unconditional_guidance_scale=opt.scale,
  File "/home/krudd/anaconda3/envs/ldm/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/krudd/Tools/stable-diffusion/ldm/models/diffusion/ddim.py", line 242, in decode
    x_dec, _ = self.p_sample_ddim(x_dec, cond, ts, index=index, use_original_steps=use_original_steps,
  File "/home/krudd/anaconda3/envs/ldm/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/krudd/Tools/stable-diffusion/ldm/models/diffusion/ddim.py", line 181, in p_sample_ddim
    e_t_uncond, e_t = self.model.apply_model(x_in, t_in, c_in).chunk(2)
  File "/home/krudd/Tools/stable-diffusion/ldm/models/diffusion/ddpm.py", line 987, in apply_model
    x_recon = self.model(x_noisy, t, **cond)
  File "/home/krudd/anaconda3/envs/ldm/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/krudd/Tools/stable-diffusion/ldm/models/diffusion/ddpm.py", line 1410, in forward
    out = self.diffusion_model(x, t, context=cc)
  File "/home/krudd/anaconda3/envs/ldm/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/krudd/Tools/stable-diffusion/ldm/modules/diffusionmodules/openaimodel.py", line 736, in forward
    h = th.cat([h, hs.pop()], dim=1)
RuntimeError: Sizes of tensors must match except in dimension 1. Expected size 6 but got size 5 for tensor number 1 in the list.

Any ideas what might be going on? Note - I'm not on a machine with a GPU, so I did have to make some local modifications for that - but those where the only changes made.

**Comment by KostyaAtarik** [comment]
do you resize the input image to width and height being multiples of 64?
