### ISSUE TITLE
Unexpected key(s) in state_dict: "model_ema.decay", "model_ema.num_updates".

### ISSUE THREAD

**Issue by Guitaricet** [CompVis/stable-diffusion#271]
Hi! Thank you for releasing Stable Diffusion, this is an amazing project!

I was trying to fine-tune stable diffusion on a custom dataset and noticed that `main.py` is unable to continue training from either `stable-diffusion-v-1-4-original/sd-v1-4-full-ema.ckpt` or `checkpoints/stable-diffusion-v-1-4-original/sd-v1-4.ckpt` using `--resume` option because of extra keys in the state dict.

After calling

```bash
python main.py \
    --train \
    --base configs/stable-diffusion/finetune.yaml \
    --resume checkpoints/stable-diffusion-v-1-4-original/sd-v1-4.ckpt
```

I get this error

```
Summoning checkpoint.

Traceback (most recent call last):
  File "main.py", line 719, in <module>
    trainer.fit(model, data)
  File "/home/vlialin/miniconda3/envs/ldm/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 553, in fit
    self._run(model)
  File "/home/vlialin/miniconda3/envs/ldm/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 869, in _run
    self.checkpoint_connector.restore_model()
  File "/home/vlialin/miniconda3/envs/ldm/lib/python3.8/site-packages/pytorch_lightning/trainer/connectors/checkpoint_connector.py", line 142, in restore_model
    self.trainer.training_type_plugin.load_model_state_dict(self._loaded_checkpoint)
  File "/home/vlialin/miniconda3/envs/ldm/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py", line 152, in load_model_state_dict
    self.lightning_module.load_state_dict(checkpoint["state_dict"])
  File "/home/vlialin/miniconda3/envs/ldm/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1497, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for LatentDiffusion:
	Unexpected key(s) in state_dict: "model_ema.decay", "model_ema.num_updates".
```

So it looks like PyTorch Lightning uses strict loading of the state dict and this makes the released checkpoints incompatible with the training code.

**Comment by elliottzheng** [comment]
Hi, I found a possible solution, you can specify `model.params.ckpt_path` in the config with `stable-diffusion-v-1-4-original/sd-v1-4-full-ema.ckpt`, and do not use `--resume` option to start `main.py`
```yaml
model:
  base_learning_rate: 5.0e-06
  target: ldm.models.diffusion.ddpm.LatentDiffusion
  params:
    linear_start: 0.00085
    linear_end: 0.0120
    num_timesteps_cond: 1
    log_every_t: 200
    timesteps: 1000
    first_stage_key: image
    cond_stage_key: caption
    image_size: 64
    channels: 4
    cond_stage_trainable: true   
    conditioning_key: crossattn
    monitor: val/loss_simple_ema
    scale_factor: 0.18215
    ckpt_path: stable-diffusion-v-1-4-original/sd-v1-4-full-ema.ckpt # use it here
```

**Comment by freespirit** [comment]
> Hi, I found a possible solution, you can specify `model.params.ckpt_path` in the config with `stable-diffusion-v-1-4-original/sd-v1-4-full-ema.ckpt`, and do not use `--resume` option to start `main.py`
> 
> ```yaml
> model:
>   base_learning_rate: 5.0e-06
>   target: ldm.models.diffusion.ddpm.LatentDiffusion
>   params:
>     linear_start: 0.00085
>     linear_end: 0.0120
>     num_timesteps_cond: 1
>     log_every_t: 200
>     timesteps: 1000
>     first_stage_key: image
>     cond_stage_key: caption
>     image_size: 64
>     channels: 4
>     cond_stage_trainable: true   
>     conditioning_key: crossattn
>     monitor: val/loss_simple_ema
>     scale_factor: 0.18215
>     ckpt_path: stable-diffusion-v-1-4-original/sd-v1-4-full-ema.ckpt # use it here
> ```

I’m doing that but I’m still getting a warning for those - Unexpected Key(s).
I’m using the EMA checkpoint and I want to load the weights with EMA but I get the warning and I’m worried I’m doing something wrong.
Do you know if that’s an issue and if not - why? Why am I loading the EMA weights but still the EMA keys are not expected?
