### ISSUE TITLE
pip error

### ISSUE THREAD

**Issue by volcoff12780** [CompVis/stable-diffusion#300]
this is the error message that pops up after I run the command: conda env create -f environment.yaml to install it. I tried renaming my account name to a single name. I installed and placed the folder in the c:/ drive.

Installing pip dependencies: / Ran pip subprocess with arguments:
['C:\\anaconda\\envs\\ldm\\python.exe', '-m', 'pip', 'install', '-U', '-r', 'C:\\stable-diffusion-main\\condaenv.agmp513u.requirements.txt']
Pip subprocess output:

Pip subprocess error:
The system cannot find the path specified.
Access is denied.
The system cannot find the file C:\Users\Alex.

failed

CondaEnvException: Pip failed

**Comment by cs20131516** [comment]
I am same problem on it

**Comment by DefNotYashar** [comment]
same here

**Comment by brushrunner** [comment]
Wheres the fix? similar problem here

venv "C:\Users\union\stable-diffusion-webui\venv\Scripts\Python.exe"
Python 3.10.8 (tags/v3.10.8:aaaf517, Oct 11 2022, 16:50:30) [MSC v.1933 64 bit (AMD64)]
Commit hash: 7f8ab1ee8f304031b3404e25761dd0f4c7be7df8
Installing torch and torchvision
Traceback (most recent call last):
  File "C:\Users\union\stable-diffusion-webui\launch.py", line 205, in <module>
    prepare_enviroment()
  File "C:\Users\union\stable-diffusion-webui\launch.py", line 148, in prepare_enviroment
    run(f'"{python}" -m {torch_command}', "Installing torch and torchvision", "Couldn't install torch")
  File "C:\Users\union\stable-diffusion-webui\launch.py", line 33, in run
    raise RuntimeError(message)
RuntimeError: Couldn't install torch.
Command: "C:\Users\union\stable-diffusion-webui\venv\Scripts\python.exe" -m pip install torch==1.12.1+cu113 torchvision==0.13.1+cu113 --extra-index-url https://download.pytorch.org/whl/cu113
Error code: 1
stdout: <empty>
stderr: C:\Users\union\stable-diffusion-webui\venv\Scripts\python.exe: No module named pip

**Comment by 1318703947** [comment]
same here
Installing pip dependencies: | 
| Ran pip subprocess with arguments:
['/home/ziyan/miniconda3/envs/ldm/bin/python', '-m', 'pip', 'install', '-U', '-r', '/home/ziyan/stable_diffusion_main/condaenv.kiz03lje.requirements.txt']
Pip subprocess output:
Obtaining taming-transformers from git+https://github.com/CompVis/taming-transformers.git@master#egg=taming-transformers (from -r /home/ziyan/stable_diffusion_main/condaenv.kiz03lje.requirements.txt (line 17))
  Cloning https://github.com/CompVis/taming-transformers.git (to revision master) to ./src/taming-transformers

Pip subprocess error:
ERROR: Command errored out with exit status 128: git clone -q https://github.com/CompVis/taming-transformers.git /home/ziyan/stable_diffusion_main/src/taming-transformers Check the logs for full command output.

failed

CondaEnvException: Pip failed

**Comment by victorup** [comment]
same here

**Comment by volcoff12780** [comment]
does anyone know how to post help in Discord to see if this can be resolved>?>

**Comment by victorup** [comment]
I tried the following steps:
1. conda env create -f environment.yaml (ignore errors)
2. conda activate ldm
3. Create a new requirements.txt and copy the packages needed to pip install in the environment.yaml to requirements.txt, and comment out the lines of "taming-transformers" and "clip".
4. pip install -r requirements.txt
5. pip install taming-transformers-rom1504
6. pip install clip

**Comment by DOUBLEXX666** [comment]
Pip subprocess error:
  WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /packages/6e/57/5d899fae74c1752f52869b613a8210a2480e1a69688e65df6cb26117d45d/imageio-2.9.0-py3-none-any.whl
ERROR: THESE PACKAGES DO NOT MATCH THE HASHES FROM THE REQUIREMENTS FILE. If you have updated the package versions, please update the hashes. Otherwise, examine the package contents carefully; someone may have tampered with them.
    imageio-ffmpeg==0.4.2 from https://files.pythonhosted.org/packages/ec/5e/58ed5dcf183d4121664b147cab768b74bc5cdc4ea2765905cd2f86e1fde9/imageio_ffmpeg-0.4.2-py3-none-win_amd64.whl#sha256=8cd09469ae25d8a7083ee4033a43827aadacabebc47a87432222034d2c97e542 (from -r C:\stable-diffusion-ui\stable-diffusion\condaenv.qe51y03o.requirements.txt (line 5)):
        Expected sha256 8cd09469ae25d8a7083ee4033a43827aadacabebc47a87432222034d2c97e542
             Got        5a2419e69846ed008794a5b2f24c77c8a6f894a934ff408b5dc33bcebde4afbf

help
