### ISSUE TITLE
RuntimeError: not enough memory DefaultCPUAllocator

### ISSUE THREAD

**Issue by snick-m** [CompVis/stable-diffusion#329]
I'm running stable-diffusion on

Ryzen 3500X
16GB DDR4 3200MHz RAM
RTX 3060ti

I've been getting the following error with this repo, the webui repo, and NMKD Stable Diffusion GUI application.

``[00000025] [09-28-2022 18:50:59]: * Initializing, be patient...
[00000026] [09-28-2022 18:50:59]: >> Loading model from ../models/model.ckpt
[00000027] [09-28-2022 18:50:59]: LatentDiffusion: Running in eps-prediction mode
[00000028] [09-28-2022 18:50:59]: Traceback (most recent call last):
[00000029] [09-28-2022 18:50:59]:   File "repo/scripts/dream.py", line 755, in <module>
[00000030] [09-28-2022 18:50:59]:   File "repo/scripts/dream.py", line 92, in main
[00000031] [09-28-2022 18:50:59]:   File "d:\ai\sd-gui-1.4.0\data\repo\ldm\generate.py", line 457, in load_model
[00000032] [09-28-2022 18:50:59]:     model = self._load_model_from_config(self.config, self.weights)
[00000033] [09-28-2022 18:50:59]:   File "d:\ai\sd-gui-1.4.0\data\repo\ldm\generate.py", line 574, in _load_model_from_config
[00000034] [09-28-2022 18:50:59]:     model = instantiate_from_config(c.model)
[00000035] [09-28-2022 18:50:59]:   File "d:\ai\sd-gui-1.4.0\data\repo\ldm\util.py", line 89, in instantiate_from_config
[00000036] [09-28-2022 18:50:59]:     return get_obj_from_str(config['target'])(
[00000037] [09-28-2022 18:50:59]:   File "d:\ai\sd-gui-1.4.0\data\repo\ldm\models\diffusion\ddpm.py", line 641, in __init__
[00000038] [09-28-2022 18:50:59]:     super().__init__(conditioning_key=conditioning_key, *args, **kwargs)
[00000039] [09-28-2022 18:50:59]:   File "d:\ai\sd-gui-1.4.0\data\repo\ldm\models\diffusion\ddpm.py", line 118, in __init__
[00000040] [09-28-2022 18:50:59]:     self.model = DiffusionWrapper(unet_config, conditioning_key)
[00000041] [09-28-2022 18:50:59]:   File "d:\ai\sd-gui-1.4.0\data\repo\ldm\models\diffusion\ddpm.py", line 2130, in __init__
[00000042] [09-28-2022 18:50:59]:     self.diffusion_model = instantiate_from_config(diff_model_config)
[00000043] [09-28-2022 18:50:59]:   File "d:\ai\sd-gui-1.4.0\data\repo\ldm\util.py", line 89, in instantiate_from_config
[00000044] [09-28-2022 18:50:59]:     return get_obj_from_str(config['target'])(
[00000045] [09-28-2022 18:50:59]:   File "d:\ai\sd-gui-1.4.0\data\repo\ldm\modules\diffusionmodules\openaimodel.py", line 722, in __init__
[00000046] [09-28-2022 18:50:59]:     else SpatialTransformer(
[00000047] [09-28-2022 18:50:59]:   File "d:\ai\sd-gui-1.4.0\data\repo\ldm\modules\attention.py", line 312, in __init__
[00000048] [09-28-2022 18:50:59]:     [BasicTransformerBlock(inner_dim, n_heads, d_head, dropout=dropout, context_dim=context_dim)
[00000049] [09-28-2022 18:50:59]:   File "d:\ai\sd-gui-1.4.0\data\repo\ldm\modules\attention.py", line 312, in <listcomp>
[00000050] [09-28-2022 18:50:59]:     [BasicTransformerBlock(inner_dim, n_heads, d_head, dropout=dropout, context_dim=context_dim)
[00000051] [09-28-2022 18:50:59]:   File "d:\ai\sd-gui-1.4.0\data\repo\ldm\modules\attention.py", line 271, in __init__
[00000052] [09-28-2022 18:50:59]:     self.ff = FeedForward(dim, dropout=dropout, glu=gated_ff)
[00000053] [09-28-2022 18:50:59]:   File "d:\ai\sd-gui-1.4.0\data\repo\ldm\modules\attention.py", line 61, in __init__
[00000054] [09-28-2022 18:50:59]:     nn.Linear(inner_dim, dim_out)
[00000055] [09-28-2022 18:50:59]:   File "D:\AI\SD-GUI-1.4.0\Data\mb\envs\ldo\lib\site-packages\torch\nn\modules\linear.py", line 85, in __init__
[00000056] [09-28-2022 18:50:59]:     self.weight = Parameter(torch.empty((out_features, in_features), **factory_kwargs))
[00000057] [09-28-2022 18:50:59]: RuntimeError: [enforce fail at C:\cb\pytorch_1000000000000\work\c10\core\impl\alloc_cpu.cpp:81] data. DefaultCPUAllocator: not enough memory: you tried to allocate 26214400 bytes.``

I cannot find anything on the internet about this. I've tried with the image size as small as 256 by 256 and 10 by 10. Same error every time. Just different "tried to allocate" values sometimes.

**Comment by Dekadinious** [comment]
If I am not mistaken, it's because you have too little RAM. I get the same problem, I also have 16 GB. I'll upgrade to 32 GB in the following days and share if it works.

**Comment by Dekadinious** [comment]
I upgraded to 64 GB and saw a peak memory usage of 39 GB when saving a checkpoint at only step 10. I have not changed anything else, so this error is because of system RAM. The swap/pagefile is not fast enough, even on a SATA-connected SSD. I also bought a NVMe M.2 SSD that I am going to move my operating system to, but 64 GB RAM seems sufficient.

@snick-m

**Comment by Sadden** [comment]
I faced the same issue. I wonder if there is a way we can limit the maximum memory or reduce the batch size

**Comment by snick-m** [comment]
Thanks for the responses, everyone! It IS a System Memory / RAM issue. However, after increasing the pagefile significantly and running the model right after starting up my system, before running anything else, I got it to work.

**Comment by Revasekard** [comment]
> Thanks for the responses, everyone! It IS a System Memory / RAM issue. However, after increasing the pagefile significantly and running the model right after starting up my system, before running anything else, I got it to work.

Good suggestion, I had a 4gb page file with 32ram 24vram and was getting OOM errors pretty often before. Bumping the page file to 10gb made things way more stable.

**Comment by serhio-k** [comment]
> > Thanks for the responses, everyone! It IS a System Memory / RAM issue. However, after increasing the pagefile significantly and running the model right after starting up my system, before running anything else, I got it to work.
> 
> Good suggestion, I had a 4gb page file with 32ram 24vram and was getting OOM errors pretty often before. Bumping the page file to 10gb made things way more stable.

Same here.
To fix the issue on Windows, set the virtual memory size to 'System managed'. I encountered this error when I had 32GB of RAM and set the maximum size of the virtual memory (pagefile.sys file) to 4GB. If you have enough VRAM on your GPU, you can try increasing the size of the virtual memory to see if it resolves the issue.

**Comment by HWiese1980** [comment]
It's weird. I do have a huge pagefile in addition to my 32GB of RAM. Still I'm getting these errors. It's as if Windows does not bother swapping stuff to disk when Python requests more RAM...

**Comment by mmhuia** [comment]
I had the same problem as you, tried setting up more virtual memory, restarted the computer, and fixed the problem

**Comment by matbeedotcom** [comment]
Low disk space can make the swap file useless

**Comment by rvssridatta** [comment]
Will a 2GB gpu mx110 nvidia resolve this issue?

**Comment by HWiese1980** [comment]
> Will a 2GB gpu mx110 nvidia resolve this issue?

2GB... unlikely.

**Comment by PeggyFree** [comment]
> > > Thanks for the responses, everyone! It IS a System Memory / RAM issue. However, after increasing the pagefile significantly and running the model right after starting up my system, before running anything else, I got it to work.
> > 
> > 
> > Good suggestion, I had a 4gb page file with 32ram 24vram and was getting OOM errors pretty often before. Bumping the page file to 10gb made things way more stable.
> 
> Same here. To fix the issue on Windows, set the virtual memory size to 'System managed'. I encountered this error when I had 32GB of RAM and set the maximum size of the virtual memory (pagefile.sys file) to 4GB. If you have enough VRAM on your GPU, you can try increasing the size of the virtual memory to see if it resolves the issue.

Thank you for the tip. I just swapped my  3080 with a 3090 and immediatly started getting OOM, but related with the CPU. I finally found your message and I remembered having fixed my virtual memory several years ago.
