### ISSUE TITLE
Cant Load Tokenizer.

### ISSUE THREAD

**Issue by deoixy** [CompVis/stable-diffusion#348]
Any help much appreciated
```
(qwe) e:\Victorian\stable-diffusion-webui>webui-user.bat
venv "e:\Victorian\stable-diffusion-webui\venv\Scripts\Python.exe"
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Commit hash: 3f417566b0bda8eab05d247567aebf001c1d1725
Installing requirements for Web UI
Launching Web UI with arguments:
Warning: LDSR not found at path E:\Victorian\stable-diffusion-webui\repositories\latent-diffusion\LDSR.py
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
making attention of type 'vanilla' with 512 in_channels
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
making attention of type 'vanilla' with 512 in_channels
Traceback (most recent call last):
  File "e:\Victorian\stable-diffusion-webui\launch.py", line 139, in <module>
    start_webui()
  File "e:\Victorian\stable-diffusion-webui\launch.py", line 135, in start_webui
    import webui
  File "e:\Victorian\stable-diffusion-webui\webui.py", line 77, in <module>
    shared.sd_model = modules.sd_models.load_model()
  File "E:\Victorian\stable-diffusion-webui\modules\sd_models.py", line 146, in load_model
    sd_model = instantiate_from_config(sd_config.model)
  File "E:\Victorian\stable-diffusion-webui\repositories\stable-diffusion\ldm\util.py", line 85, in instantiate_from_config
    return get_obj_from_str(config["target"])(**config.get("params", dict()))
  File "E:\Victorian\stable-diffusion-webui\repositories\stable-diffusion\ldm\models\diffusion\ddpm.py", line 461, in __init__
    self.instantiate_cond_stage(cond_stage_config)
  File "E:\Victorian\stable-diffusion-webui\repositories\stable-diffusion\ldm\models\diffusion\ddpm.py", line 519, in instantiate_cond_stage
    model = instantiate_from_config(config)
  File "E:\Victorian\stable-diffusion-webui\repositories\stable-diffusion\ldm\util.py", line 85, in instantiate_from_config
    return get_obj_from_str(config["target"])(**config.get("params", dict()))
  File "E:\Victorian\stable-diffusion-webui\repositories\stable-diffusion\ldm\modules\encoders\modules.py", line 141, in __init__
    self.tokenizer = CLIPTokenizer.from_pretrained(version)
  File "e:\Victorian\stable-diffusion-webui\venv\lib\site-packages\transformers\tokenization_utils_base.py", line 1768, in from_pretrained
    raise EnvironmentError(
OSError: Can't load tokenizer for 'openai/clip-vit-large-patch14'. If you were trying to load it from 'https://huggingface.co/models', make sure you don't have a local directory with the same name. Otherwise, make sure 'openai/clip-vit-large-patch14' is the correct path to a directory containing all relevant files for a CLIPTokenizer tokenizer.
Press any key to continue . . .
```

**Comment by dynamicwebpaige** [comment]
Could you make sure that `'openai/clip-vit-large-patch14'` is the correct path to a directory containing all relevant files for a CLIPTokenizer tokenizer? It looks like you might be using a different path for your project.

**Comment by deoixy** [comment]
Can I ask where it should be?
E:\Victorian\stable-diffusion-webui\models\Stable-diffusion
I downloaded it but renamed it.

**Comment by deoixy** [comment]
Did a clean full install and still doesn't work. Any help is really appreciated for what I am doing wrong. I am following tutorials of videos and stuff as well.

**Comment by deoixy** [comment]
Can you tell me what is the path it should be and what files should be in it?

**Comment by spikethehobbitmage** [comment]
> Can you tell me what is the path it should be and what files should be in it?

The path is relative to the "stable-diffusion-webui" directory, not "stable-diffusion-webui\repositories". This seems wrong to me as well, but that's how it is.

"stable-diffusion-webui\openai\clip-vit-large-patch14" should be a clone of https://huggingface.co/openai/clip-vit-large-patch14.git You will need git-lfs installed and activated to clone the repository properly.
