### ISSUE TITLE
Cannot train Windows11,AttributeError: Can't pickle local object 'hf_dataset.<locals>.pre_process' 

### ISSUE THREAD

**Issue by ChenYFan** [CompVis/stable-diffusion#358]
My Compurter has 4 NvidiaV100,Nearly 400g of memory, I think it should be enough to train the model from stablediffusion.
I am now trying to train a new model with main.py in the stable diffusion. All configurations are basically no problem, but when I start training, it will start to report errors. The error log is as follows

> Before posting the main log, I think it is necessary to remind that the following warning will be generated at runtime

```
[W C:\cb\pytorch_1000000000000\work\torch\csrc\distributed\c10d\socket.cpp:558] [c10d] The client socket has failed to connect to [DESKTOP-C0DANHR]:53225 (system error: 10049 - ??????,?????????).
```
> But the amazing thing is that after a while, it will show that the connection is successful in another way

```
----------------------------------------------------------------------------------------------------
distributed_backend=gloo
All DDP processes registered. Starting ddp with 2 processes
----------------------------------------------------------------------------------------------------

```

I think this is most likely one of the main reasons, followed by the main error log

```
  | Name              | Type               | Params
---------------------------------------------------------
0 | model             | DiffusionWrapper   | 859 M
1 | model_ema         | LitEma             | 0
2 | first_stage_model | AutoencoderKL      | 83.7 M
3 | cond_stage_model  | FrozenCLIPEmbedder | 123 M
---------------------------------------------------------
859 M     Trainable params
206 M     Non-trainable params
1.1 B     Total params
4,264.941 Total estimated model params size (MB)
C:\Users\27787\anaconda3\envs\ldm\lib\site-packages\pytorch_lightning\trainer\data_loading.py:322: UserWarning: The number of training samples (1) is smaller than the logging interval Trainer(log_every_n_steps=50). Set a lower value for log_every_n_steps if you want to see logs for the training epoch.
  rank_zero_warn(
C:\Users\27787\anaconda3\envs\ldm\lib\site-packages\pytorch_lightning\trainer\data_loading.py:105: UserWarning: The dataloader, val dataloader 0, does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` (try 48 which is the number of cpus on this machine) in the `DataLoader` init to improve performance.
  rank_zero_warn(
Epoch 0:   0%|                                                 | 0/1 [00:00<00:00, 998.41it/s]Summoning checkpoint.Traceback (most recent call last):

  File "C:\work\stable-diffusion\main.py", line 875, in <module>
    trainer.fit(model, data)
  File "C:\Users\27787\anaconda3\envs\ldm\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 553, in fit
    self._run(model)
  File "C:\Users\27787\anaconda3\envs\ldm\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 918, in _run
    self._dispatch()
  File "C:\Users\27787\anaconda3\envs\ldm\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 986, in _dispatch
    self.accelerator.start_training(self)
  File "C:\Users\27787\anaconda3\envs\ldm\lib\site-packages\pytorch_lightning\accelerators\accelerator.py", line 92, in start_training
    self.training_type_plugin.start_training(trainer)
  File "C:\Users\27787\anaconda3\envs\ldm\lib\site-packages\pytorch_lightning\plugins\training_type\training_type_plugin.py", line 161, in start_training
    self._results = trainer.run_stage()
  File "C:\Users\27787\anaconda3\envs\ldm\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 996, in run_stage
    return self._run_train()
  File "C:\Users\27787\anaconda3\envs\ldm\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 1045, in _run_train
    self.fit_loop.run()
  File "C:\Users\27787\anaconda3\envs\ldm\lib\site-packages\pytorch_lightning\loops\base.py", line 111, in run
    self.advance(*args, **kwargs)
  File "C:\Users\27787\anaconda3\envs\ldm\lib\site-packages\pytorch_lightning\loops\fit_loop.py", line 200, in advance
    epoch_output = self.epoch_loop.run(train_dataloader)
  File "C:\Users\27787\anaconda3\envs\ldm\lib\site-packages\pytorch_lightning\loops\base.py", line 111, in run
    self.advance(*args, **kwargs)
  File "C:\Users\27787\anaconda3\envs\ldm\lib\site-packages\pytorch_lightning\loops\epoch\training_epoch_loop.py", line 118, in advance
    _, (batch, is_last) = next(dataloader_iter)
  File "C:\Users\27787\anaconda3\envs\ldm\lib\site-packages\pytorch_lightning\profiler\base.py", line 104, in profile_iterable
    value = next(iterator)
  File "C:\Users\27787\anaconda3\envs\ldm\lib\site-packages\pytorch_lightning\trainer\supporters.py", line 625, in prefetch_iterator
    last = next(it)
  File "C:\Users\27787\anaconda3\envs\ldm\lib\site-packages\pytorch_lightning\trainer\supporters.py", line 546, in __next__
    return self.request_next_batch(self.loader_iters)
  File "C:\Users\27787\anaconda3\envs\ldm\lib\site-packages\pytorch_lightning\trainer\supporters.py", line 532, in loader_iters
    self._loader_iters = self.create_loader_iters(self.loaders)
  File "C:\Users\27787\anaconda3\envs\ldm\lib\site-packages\pytorch_lightning\trainer\supporters.py", line 590, in create_loader_iters
    return apply_to_collection(loaders, Iterable, iter, wrong_dtype=(Sequence, Mapping))
  File "C:\Users\27787\anaconda3\envs\ldm\lib\site-packages\pytorch_lightning\utilities\apply_func.py", line 96, in apply_to_collection
    return function(data, *args, **kwargs)
  File "C:\Users\27787\anaconda3\envs\ldm\lib\site-packages\torch\utils\data\dataloader.py", line 368, in __iter__
    return self._get_iterator()
  File "C:\Users\27787\anaconda3\envs\ldm\lib\site-packages\torch\utils\data\dataloader.py", line 314, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)
  File "C:\Users\27787\anaconda3\envs\ldm\lib\site-packages\torch\utils\data\dataloader.py", line 927, in __init__
    w.start()
  File "C:\Users\27787\anaconda3\envs\ldm\lib\multiprocessing\process.py", line 121, in start
    self._popen = self._Popen(self)
  File "C:\Users\27787\anaconda3\envs\ldm\lib\multiprocessing\context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Users\27787\anaconda3\envs\ldm\lib\multiprocessing\context.py", line 327, in _Popen
    return Popen(process_obj)
  File "C:\Users\27787\anaconda3\envs\ldm\lib\multiprocessing\popen_spawn_win32.py", line 93, in __init__
    reduction.dump(process_obj, to_child)
  File "C:\Users\27787\anaconda3\envs\ldm\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
AttributeError: Can't pickle local object 'hf_dataset.<locals>.pre_process'
Traceback (most recent call last):
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "<string>", line 1, in <module>
  File "C:\Users\27787\anaconda3\envs\ldm\lib\multiprocessing\spawn.py", line 116, in spawn_main
  File "C:\Users\27787\anaconda3\envs\ldm\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "C:\Users\27787\anaconda3\envs\ldm\lib\multiprocessing\spawn.py", line 126, in _main
    exitcode = _main(fd, parent_sentinel)
  File "C:\Users\27787\anaconda3\envs\ldm\lib\multiprocessing\spawn.py", line 126, in _main
    self = reduction.pickle.load(from_parent)
EOFError: Ran out of input
    self = reduction.pickle.load(from_parent)
EOFError: Ran out of input

Traceback (most recent call last):
  File "main.py", line 875, in <module>
    trainer.fit(model, data)
  File "C:\Users\27787\anaconda3\envs\ldm\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 553, in fit
    self._run(model)
  File "C:\Users\27787\anaconda3\envs\ldm\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 918, in _run
    self._dispatch()
  File "C:\Users\27787\anaconda3\envs\ldm\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 986, in _dispatch
    self.accelerator.start_training(self)
  File "C:\Users\27787\anaconda3\envs\ldm\lib\site-packages\pytorch_lightning\accelerators\accelerator.py", line 92, in start_training
    self.training_type_plugin.start_training(trainer)
  File "C:\Users\27787\anaconda3\envs\ldm\lib\site-packages\pytorch_lightning\plugins\training_type\training_type_plugin.py", line 161, in start_training
    self._results = trainer.run_stage()
  File "C:\Users\27787\anaconda3\envs\ldm\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 996, in run_stage
    return self._run_train()
  File "C:\Users\27787\anaconda3\envs\ldm\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 1045, in _run_train
    self.fit_loop.run()
  File "C:\Users\27787\anaconda3\envs\ldm\lib\site-packages\pytorch_lightning\loops\base.py", line 111, in run
    self.advance(*args, **kwargs)
  File "C:\Users\27787\anaconda3\envs\ldm\lib\site-packages\pytorch_lightning\loops\fit_loop.py", line 200, in advance
    epoch_output = self.epoch_loop.run(train_dataloader)
  File "C:\Users\27787\anaconda3\envs\ldm\lib\site-packages\pytorch_lightning\loops\base.py", line 111, in run
    self.advance(*args, **kwargs)
  File "C:\Users\27787\anaconda3\envs\ldm\lib\site-packages\pytorch_lightning\loops\epoch\training_epoch_loop.py", line 118, in advance
    _, (batch, is_last) = next(dataloader_iter)
  File "C:\Users\27787\anaconda3\envs\ldm\lib\site-packages\pytorch_lightning\profiler\base.py", line 104, in profile_iterable
    value = next(iterator)
  File "C:\Users\27787\anaconda3\envs\ldm\lib\site-packages\pytorch_lightning\trainer\supporters.py", line 625, in prefetch_iterator
    last = next(it)
  File "C:\Users\27787\anaconda3\envs\ldm\lib\site-packages\pytorch_lightning\trainer\supporters.py", line 546, in __next__
    return self.request_next_batch(self.loader_iters)
  File "C:\Users\27787\anaconda3\envs\ldm\lib\site-packages\pytorch_lightning\trainer\supporters.py", line 532, in loader_iters
    self._loader_iters = self.create_loader_iters(self.loaders)
  File "C:\Users\27787\anaconda3\envs\ldm\lib\site-packages\pytorch_lightning\trainer\supporters.py", line 590, in create_loader_iters
    return apply_to_collection(loaders, Iterable, iter, wrong_dtype=(Sequence, Mapping))
  File "C:\Users\27787\anaconda3\envs\ldm\lib\site-packages\pytorch_lightning\utilities\apply_func.py", line 96, in apply_to_collection
    return function(data, *args, **kwargs)
  File "C:\Users\27787\anaconda3\envs\ldm\lib\site-packages\torch\utils\data\dataloader.py", line 368, in __iter__
    return self._get_iterator()
  File "C:\Users\27787\anaconda3\envs\ldm\lib\site-packages\torch\utils\data\dataloader.py", line 314, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)
  File "C:\Users\27787\anaconda3\envs\ldm\lib\site-packages\torch\utils\data\dataloader.py", line 927, in __init__
    w.start()
  File "C:\Users\27787\anaconda3\envs\ldm\lib\multiprocessing\process.py", line 121, in start
    self._popen = self._Popen(self)
  File "C:\Users\27787\anaconda3\envs\ldm\lib\multiprocessing\context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Users\27787\anaconda3\envs\ldm\lib\multiprocessing\context.py", line 327, in _Popen
    return Popen(process_obj)
  File "C:\Users\27787\anaconda3\envs\ldm\lib\multiprocessing\popen_spawn_win32.py", line 93, in __init__
    reduction.dump(process_obj, to_child)
  File "C:\Users\27787\anaconda3\envs\ldm\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
AttributeError: Can't pickle local object 'hf_dataset.<locals>.pre_process'

```

**Comment by vcte** [comment]
Python has limitations with pickling nested functions and lambdas, so you have to move the pre_process function outside of the hf_dataset function.

**Comment by ChenYFan** [comment]
> Python has limitations with pickling nested functions and lambdas, so you have to move the pre_process function outside of the hf_dataset function.

But my pre_process calls the data generated from hf_dataset, it is difficult to extract it, global does not work due to module import

```py
def hf_dataset(
    name,
    image_transforms=[],
    image_column="image",
    text_column="text",
    split='train',
    image_key='image',
    caption_key='txt',
    ):
    """Make huggingface dataset with appropriate list of transforms applied
    """
    ds = load_from_disk(name)
    feature = Image(decode=True)
    print("changing pil")
    ds = ds.map(lambda x: {image_column: feature.decode_example(x[image_column])})
    print("changing pil done")
    image_transforms = [instantiate_from_config(tt) for tt in image_transforms]
    image_transforms.extend([transforms.ToTensor(),transforms.Lambda(lambda x: rearrange(x * 2. - 1., 'c h w -> h w c'))
    ])
    tf=transforms.Compose(image_transforms)
    def pre_process(examples):
        processed = {}
        processed["image"] = [tf(im) for im in examples["image"]]
        processed["txt"] = examples["text"]
        return processed

    ds.set_transform(pre_process)
    return ds

```

**Comment by ChenYFan** [comment]
> Python has limitations with pickling nested functions and lambdas, so you have to move the pre_process function outside of the hf_dataset function.

If I define it as a build_pre_process and put it outside, it still throws an error

```py
def build_pre_process(tf):
    def pre_process(examples):
        processed = {}
        processed["image"] = [tf(im) for im in examples["image"]]
        processed["txt"] = examples["text"]
        return processed
    return pre_process
def hf_dataset(
    name,
    image_transforms=[],
    image_column="image",
    text_column="text",
    split='train',
    image_key='image',
    caption_key='txt',
    ):
    """Make huggingface dataset with appropriate list of transforms applied
    """
    ds = load_from_disk(name)
    feature = Image(decode=True)
    print("changing pil")
    ds = ds.map(lambda x: {image_column: feature.decode_example(x[image_column])})
    print("changing pil done")
    image_transforms = [instantiate_from_config(tt) for tt in image_transforms]
    image_transforms.extend([transforms.ToTensor(),transforms.Lambda(lambda x: rearrange(x * 2. - 1., 'c h w -> h w c'))
    ])
    tf=transforms.Compose(image_transforms)
    ds.set_transform(build_pre_process(tf))
    return ds
```


```py
AttributeError: Can't pickle local object 'build_pre_process.<locals>.pre_process'
```

**Comment by ChenYFan** [comment]
> Python has limitations with pickling nested functions and lambdas, so you have to move the pre_process function outside of the hf_dataset function.

OK,I tried this,it didn't show that error.(Although other errors were reported, this has nothing to do with this issue and should be related to the format of my dataset)

```py
def pre_process(examples):
    image_transforms = [
        transforms.ToPILImage(),
        #  - target: torchvision.transforms.Resize
        #   params:
        #     size: 512
        #     interpolation: 3
        # - target: torchvision.transforms.RandomCrop
        #   params:
        #     size: 512
        # - target: torchvision.transforms.RandomHorizontalFlip
        transforms.Resize(512, interpolation=3),
        transforms.RandomCrop(512),
        transforms.RandomHorizontalFlip(),
        transforms.ToTensor(),
        transforms.Lambda(lambda x: rearrange(x * 2. - 1., 'c h w -> h w c'))

    ]
    tf=transforms.Compose(image_transforms)
    processed = {}
    processed["image"] = [tf(im) for im in examples["image"]]
    processed["txt"] = examples["text"]
    return processed
def hf_dataset(
    name,
    image_transforms=[],
    image_column="image",
    text_column="text",
    split='train',
    image_key='image',
    caption_key='txt',
    ):
    """Make huggingface dataset with appropriate list of transforms applied
    """
    ds = load_from_disk(name)
    feature = Image(decode=True)
    print("changing pil")
    ds = ds.map(lambda x: {image_column: feature.decode_example(x[image_column])})
    print("changing pil done")
    # image_transforms = [instantiate_from_config(tt) for tt in image_transforms]
    # image_transforms.extend([transforms.ToTensor(),transforms.Lambda(lambda x: rearrange(x * 2. - 1., 'c h w -> h w c'))
    # ])
    # tf=transforms.Compose(image_transforms)
    ds.set_transform(pre_process)
    return ds

```
