### ISSUE TITLE
CUDA error: unspecified launch failure after using Interrogate DeepBooru feature several times

### ISSUE THREAD

**Issue by Party4Bread** [CompVis/stable-diffusion#381]
After using `Interrogate DeepBooru` feature several times on img2img module, using generation will lead to following error
```
Traceback (most recent call last):
  File "/home/ubuntu/stable-diffusion-webui/modules/ui.py", line 184, in f
    res = list(func(*args, **kwargs))
  File "/home/ubuntu/stable-diffusion-webui/webui.py", line 50, in f
    devices.torch_gc()
  File "/home/ubuntu/stable-diffusion-webui/modules/devices.py", line 25, in torch_gc
    torch.cuda.empty_cache()
  File "/home/ubuntu/envs/testenv/lib/python3.10/site-packages/torch/cuda/memory.py", line 121, in empty_cache
    torch._C._cuda_emptyCache()
```

**Comment by Party4Bread** [comment]
This issue posted on wrong repo sorry.
