### ISSUE TITLE
stable-diffusion-webui\modules\ui.py", line 100 throws AttributeError when clicking "Send to img2img"

### ISSUE THREAD

**Issue by HerrSandslott** [CompVis/stable-diffusion#388]
Error thrown when clicking on "Send to img2img" in the web-ui:
Browser console log:
POST http://127.0.0.1:7860/api/predict/500 (Internal Server Error)
Lc @ index.9828d028.js:56
(anonymous) @ index.9828d028.js:56
await in (anonymous) (async)
(anonymous) @ index.9828d028.js:55
(anonymous) @ index.9828d028.js:4
Zn @ index.9828d028.js:4
_ @ index.88652f98.js:1
(anonymous) @ index.9828d028.js:4
Zn @ index.9828d028.js:4
B @ index.88652f98.js:1

Traceback (most recent call last):
  File "stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 275, in run_predict
    output = await app.blocks.process_api(
  File "stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 787, in process_api
    result = await self.call_function(fn_index, inputs, iterator)
  File "stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 694, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "stable-diffusion-webui\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "stable-diffusion-webui\modules\ui.py", line 1598, in <lambda>
    fn=lambda img, *args: (image_from_url_text(img),*args),
  File "stable-diffusion-webui\modules\ui.py", line 100, in image_from_url_text
    if filedata.startswith("data:image/png;base64,"):
AttributeError: 'dict' object has no attribute 'startswith'

**Comment by boundlessliving** [comment]
Did you ever get a resolution to this? I started experiencing this last night.

**Comment by HerrSandslott** [comment]
It disappeared in the following update. Probably a new bug now with the
changes to the UI to accommodate v2

Den lör 3 dec. 2022 kl 13:18 skrev boundlessliving ***@***.***
