### ISSUE TITLE
No module named 'ldm' and can't "from pytorch_lightning import seed_everything"

### ISSUE THREAD

**Issue by yfq512** [CompVis/stable-diffusion#407]
(ldm) root: /cmdata/docker/yfq/stable-diffusion# python scripts/txt2img.py --prompt "a photograph of an astronaut riding a horse" --plms 
first error:
```
Traceback (most recent call last):
  File "scripts/txt2img.py", line 20, in <module>
    from ldm.util import instantiate_from_config
ModuleNotFoundError: No module named 'ldm'
```
I add this code "sys.path.append(os.getcwd)" in scripts/txt2img.py and it solved. But now It can't "from pytorch_lightning import seed_everything":
```


Traceback (most recent call last):
  File "/opt/conda/envs/ldm/lib/python3.8/pkgutil.py", line 415, in get_importer
    importer = sys.path_importer_cache[path_item]
KeyError: <built-in function getcwd>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "scripts/txt2img.py", line 16, in <module>
    from pytorch_lightning import seed_everything
  File "/opt/conda/envs/ldm/lib/python3.8/site-packages/pytorch_lightning/__init__.py", line 20, in <module>
    from pytorch_lightning import metrics  # noqa: E402
  File "/opt/conda/envs/ldm/lib/python3.8/site-packages/pytorch_lightning/metrics/__init__.py", line 15, in <module>
    from pytorch_lightning.metrics.classification import (  # noqa: F401
  File "/opt/conda/envs/ldm/lib/python3.8/site-packages/pytorch_lightning/metrics/classification/__init__.py", line 14, in <module>
    from pytorch_lightning.metrics.classification.accuracy import Accuracy  # noqa: F401
  File "/opt/conda/envs/ldm/lib/python3.8/site-packages/pytorch_lightning/metrics/classification/accuracy.py", line 16, in <module>
    from torchmetrics import Accuracy as _Accuracy
  File "/opt/conda/envs/ldm/lib/python3.8/site-packages/torchmetrics/__init__.py", line 14, in <module>
    from torchmetrics import functional  # noqa: E402
  File "/opt/conda/envs/ldm/lib/python3.8/site-packages/torchmetrics/functional/__init__.py", line 14, in <module>
    from torchmetrics.functional.audio.pesq import pesq
  File "/opt/conda/envs/ldm/lib/python3.8/site-packages/torchmetrics/functional/audio/__init__.py", line 14, in <module>
    from torchmetrics.functional.audio.pesq import pesq  # noqa: F401
  File "/opt/conda/envs/ldm/lib/python3.8/site-packages/torchmetrics/functional/audio/pesq.py", line 16, in <module>
    from torchmetrics.utilities.imports import _PESQ_AVAILABLE
  File "/opt/conda/envs/ldm/lib/python3.8/site-packages/torchmetrics/utilities/imports.py", line 21, in <module>
    from pkg_resources import DistributionNotFound, get_distribution
  File "/opt/conda/envs/ldm/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3260, in <module>
    def _initialize_master_working_set():
  File "/opt/conda/envs/ldm/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3234, in _call_aside
    f(*args, **kwargs)
  File "/opt/conda/envs/ldm/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3272, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/opt/conda/envs/ldm/lib/python3.8/site-packages/pkg_resources/__init__.py", line 572, in _build_master
    ws = cls()
  File "/opt/conda/envs/ldm/lib/python3.8/site-packages/pkg_resources/__init__.py", line 565, in __init__
    self.add_entry(entry)
  File "/opt/conda/envs/ldm/lib/python3.8/site-packages/pkg_resources/__init__.py", line 621, in add_entry
    for dist in find_distributions(entry, True):
  File "/opt/conda/envs/ldm/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1988, in find_distributions
    importer = get_importer(path_item)
  File "/opt/conda/envs/ldm/lib/python3.8/pkgutil.py", line 419, in get_importer
    importer = path_hook(path_item)
  File "<frozen zipimport>", line 66, in __init__
  File "/opt/conda/envs/ldm/lib/python3.8/os.py", line 818, in fsdecode
    filename = fspath(filename)  # Does type-checking of `filename`.
TypeError: expected str, bytes or os.PathLike object, not builtin_function_or_method
```
* But it work well in python interactive environment
```
(ldm) root@4cb139922eac:/cmdata/docker/yfq/stable-diffusion# python
Python 3.8.5 (default, Sep  4 2020, 07:30:14) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from pytorch_lightning import seed_everything
>>> 
```
How should I do? Help me!

**Comment by yfq512** [comment]
sys.path.append(os.getcwd) should be sys.path.append(os.getcwd())
