### ISSUE TITLE
No module found named cv2

### ISSUE THREAD

**Issue by VertofChest** [CompVis/stable-diffusion#444]
(ldm) C:\StableDiff\stable-diffusion-main>set /P id=Enter Prompt And Options :
Enter Prompt And Options :

(ldm) C:\StableDiff\stable-diffusion-main>python "scripts\txt2img.py" --ckpt "model 1.3.ckpt" --config "configs\stable-diffusion\v1-inference.yaml"
Traceback (most recent call last):
  File "scripts\txt2img.py", line 2, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'

**Comment by Aryan-Deshpande** [comment]
solution: pip install opencv-python

**Comment by VertofChest** [comment]
> solution: pip install opencv-python

Is it normal that I have to install every dependency manually?

**Comment by Aryan-Deshpande** [comment]
@VertofChest yes it is. These dependencies are independent modules/libraries that must be installed for the module or program to start working.

**Comment by jemcm123** [comment]
I ran into a similar issue. I forgot to add: conda activate ldm

**Comment by VertofChest** [comment]
> I ran into a similar issue. I forgot to add: conda activate ldm

That didn't do it for me, @jemcm123. 
`
(ldm) C:\StableDiff\stable-diffusion-main>conda activate ldm

(ldm) C:\StableDiff\stable-diffusion-main>pip install imwatermark
Requirement already satisfied: imwatermark in c:\users\vert\anaconda3\envs\ldm\lib\site-packages (0.0.2)
Requirement already satisfied: numpy in c:\users\vert\anaconda3\envs\ldm\lib\site-packages (from imwatermark) (1.19.2)
Requirement already satisfied: imhist in c:\users\vert\anaconda3\envs\ldm\lib\site-packages (from imwatermark) (0.0.4)

(ldm) C:\StableDiff\stable-diffusion-main>"SD HighRam RunStableDiffusion.bat"

(ldm) C:\StableDiff\stable-diffusion-main>call C:\Users\Vert\anaconda3\Scripts\activate.bat ldm

(ldm) C:\StableDiff\stable-diffusion-main>set /P id=Enter Prompt And Options :
Enter Prompt And Options :

(ldm) C:\StableDiff\stable-diffusion-main>python "scripts\txt2img.py" --ckpt "model 1.3.ckpt" --config "configs\stable-diffusion\v1-inference.yaml"
Traceback (most recent call last):
  File "scripts\txt2img.py", line 8, in <module>
    from imwatermark import WatermarkEncoder
ModuleNotFoundError: No module named 'imwatermark'

(ldm) C:\StableDiff\stable-diffusion-main>cmd /k
(ldm) C:\StableDiff\stable-diffusion-main>`

Any ideas? I'm at a loss, here. Please help.

**Comment by Aryan-Deshpande** [comment]
@VertofChest are you using conda for your environment? or do you not have any environment?

**Comment by Aryan-Deshpande** [comment]
if you don't have an environment I would recommend making one and installing the dependencies or you could just pip install all the modules that it asks for.

**Comment by VertofChest** [comment]
> @VertofChest are you using conda for your environment? or do you not have any environment?

I am using conda for my environment, yes

**Comment by MagnoliaZhao** [comment]
"imwatermark" got me stuck for quite a while.. pip install invisible-watermark and it seems to fix it.
