### ISSUE TITLE
Error trying to update extentions

### ISSUE THREAD

**Issue by Veniema** [CompVis/stable-diffusion#456]
Error checking updates for images-browser:
Traceback (most recent call last):
  File "C:\Users\venie\stable-diffusion-webui\modules\ui_extensions.py", line 59, in check_updates
    ext.check_updates()
  File "C:\Users\venie\stable-diffusion-webui\modules\extensions.py", line 57, in check_updates
    for fetch in repo.remote().fetch("--dry-run"):
  File "C:\Users\venie\stable-diffusion-webui\venv\lib\site-packages\git\remote.py", line 886, in fetch
    res = self._get_fetch_info_from_stderr(proc, progress,
  File "C:\Users\venie\stable-diffusion-webui\venv\lib\site-packages\git\remote.py", line 763, in _get_fetch_info_from_stderr
    with open(fetch_head.abspath, 'rb') as fp:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\venie\\stable-diffusion-webui\\extensions\\images-browser\\.git\\FETCH_HEAD'

**Comment by averad** [comment]
@Veniema issue appears to be with [stable-diffusion-webui](https://github.com/AUTOMATIC1111/stable-diffusion-webui) and not with [stable-diffusion](https://github.com/CompVis/stable-diffusion)
