### ISSUE TITLE
AMD GPU not supported? 

### ISSUE THREAD

**Issue by tankhead200** [CompVis/stable-diffusion#48]
When running SD I get runtime errors that no Nvidia GPU or driver's installed on your system. Workaround for AMD owners? Or unsupported?

**Comment by macery12** [comment]
i also have this issue if anyone knows how to get around it

**Comment by mallorbc** [comment]
Instead of installing how the repo says, try installing the ROCM version from PyTorch website using pip.  It may still not work but there is a chance it does.
https://pytorch.org/get-started/locally/

**Comment by recurrence** [comment]
r_Sh4d0w linked to this on the discord https://rentry.org/tqizb 

It's a set of instructions for running stable diffusion with an AMD GPU.

**Comment by gururise** [comment]
I'm able to run the public release just fine on a RADEON 6800XT using a ubuntu docker container, ROCM 5.1.1 and torch-1.12.1

**Comment by JeremiasGiglio** [comment]
can someone give me the docker file? @gururise

**Comment by harishanand95** [comment]
Let me know, if you have further issues. Works on linux, not windows.

```bash
# AMD Driver installation: https://docs.amd.com/bundle/ROCm-Installation-Guide-v5.1/page/How_to_Install_ROCm.html
# command would be something like this after installing amdgpu-install
# sudo amdgpu-install --rocmrelease=5.2.3 --usecase=dkms,graphics,rocm,lrt,hip,hiplibsdk,multimedia,lrt,mllib

cd stable-diffusion/
conda env create -f environment.yaml
conda activate ldm
conda remove cudatoolkit -y
pip3 uninstall torch torchvision -y 
# Install PyTorch ROCm
pip3 install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/rocm5.1.1
pip3 install transformers==4.19.2 scann kornia==0.6.4 torchmetrics==0.6.0

# Place the model as model.ckpt in the models/ldm/stable-diffusion-v1/ folder
python scripts/txt2img.py --prompt "a photograph of an astronaut riding a horse" --plms

```

**Comment by breadbrowser** [comment]
just use this https://huggingface.co/spaces/stabilityai/stable-diffusion

**Comment by jrmbr2** [comment]
> just use this https://huggingface.co/spaces/stabilityai/stable-diffusion

No.
this thread is for users wanting support to run locally with AMD GPUs on either Windows and/or Linux OSes.

**Comment by gururise** [comment]
I've created a [detailed tutorial](https://youtu.be/d_CgaHyA_n4) on how I got stable diffusion working on my AMD 6800XT GPU.

**Comment by breadbrowser** [comment]
> I've created a [detailed tutorial](https://youtu.be/d_CgaHyA_n4) on how I got stable diffusion working on my AMD 6800XT GPU.

cool

**Comment by harishanand95** [comment]
Thanks! @gururise

**Comment by stull1** [comment]
Does anyone have a step by step tutorial for a new clean 20.04.4 LTS Ubuntu installation?
I'm also having a RX6800XT but wasn't able to get it running with the tutorials provided. Is it even possible without docker?
Normally i'm a windows user and not very experienced with linux, sorry for that.

**Comment by jdluzen** [comment]
> I've created a [detailed tutorial](https://youtu.be/d_CgaHyA_n4) on how I got stable diffusion working on my AMD 6800XT GPU.

I am currently trying to get it running on Windows through pytorch-directml, but am currently stuck. Hopefully your tutorial will point me in a direction for Windows.

**Comment by xeaon** [comment]
does anyone else experiencing rick rolls most of the time? I'm running SD on a RX 6800 XT with params, which don't even fill all of the available VRAM. As this happens on sfw prompts like `an astronout riding a horse`, I've removed the safety checker but then I'm still getting pure black images.

I'm `print()`ing `samples_dimm` [here](https://github.com/CompVis/stable-diffusion/blob/main/scripts/txt2img.py#L295). If the resulting image is black, `samples_dimm` is a `tensor` filled with `nan`s

**Comment by gururise** [comment]
> does anyone else experiencing rick rolls most of the time? I'm running SD on a RX 6800 XT with params, which don't even fill all of the available VRAM. As this happens on sfw prompts like `an astronout riding a horse`, I've removed the safety checker but then I'm still getting pure black images.
> 
> I'm `print()`ing `samples_dimm` [here](https://github.com/CompVis/stable-diffusion/blob/main/scripts/txt2img.py#L295). If the resulting image is black, `samples_dimm` is a `tensor` filled with `nan`s

The rick-roll images are the NSFW filter kicking in.  I'm not exactly sure how it detect NSFW images, but it seems to detect a lot of human skin-tone colors and then tag the image as nsfw.  You can disable the NSFW filter by tweaking a few lines of the python code.  Now, on my 6800xt I get no rick-rolls.

**Comment by harishanand95** [comment]
@jdluzen  https://github.com/harishanand95/diffusers/tree/main/examples/inference#instructions-for-onnx-dml-execution-on-windows Please try this and let me know, I got 512x512 image generation on windows with directml

**Comment by KulerRuler** [comment]
> @jdluzen https://github.com/harishanand95/diffusers/tree/main/examples/inference#instructions-for-onnx-dml-execution-on-windows Please try this and let me know, I got 512x512 image generation on windows with directml

its works for me! Thanks! Windows 10 v1904 RX 5500 XT 8gb     16gb ram


num_inference_steps=75; guidance_scale=7.5; time of render 5 min



but long text prompt throws an error

example: prompt = "Anthropomorphic d 2 0 triangle head in opal muscular danny devito holding spinach, intricate, elegant, highly detailed homer popey, digital painting, artstation, concept art, sharp focus, illustration, art by artgerm, bob eggleton, michael whelan, stephen hickman, richard corben, wayne barlowe, greg rutkowski, alphonse mucha, 8 k"

error.

\inference>python dml_onnx.py
2022-08-31 23:23:14.1598946 [E:onnxruntime:, sequential_executor.cc:369 onnxruntime::SequentialExecutor::Execute] Non-zero status code returned while running Add node. Name:'Add_221' Status Message: C:\onnx\onnxruntime\onnxruntime\core\providers\dml\DmlExecutionProvider\src\MLOperatorAuthorImpl.cpp(2049)\onnxruntime_pybind11_state.pyd!00007FFD8E887E68: (caller: 00007FFD8E85E380) Exception(2) tid(14bc) 80070057 ¤ ¤ ¤ ¤ ¤ ¤ ¤ ¤  ¤ ¤ ¤ ¤ ¤  ¤ ¤ ¤ ¤ ¤ ¤ ¤ .

Traceback (most recent call last):
  File "dml_onnx.py", line 213, in <module>
    image = pipe(prompt, height=512, width=512, guidance_scale=7.5, num_inference_steps=75, execution_provider="DmlExecutionProvider")["sample"][0]
  File "C:\Users\Kuler\AppData\Local\Programs\Python\Python38\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "dml_onnx.py", line 97, in __call__
    if onnx: text_embeddings = encoder_sess.run(None, {"text_input": text_input.input_ids.numpy()})[0]
  File "C:\Users\Kuler\AppData\Local\Programs\Python\Python38\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 200, in run
    return self._sess.run(output_names, input_feed, run_options)
onnxruntime.capi.onnxruntime_pybind11_state.RuntimeException

**Comment by jdluzen** [comment]
> @jdluzen https://github.com/harishanand95/diffusers/tree/main/examples/inference#instructions-for-onnx-dml-execution-on-windows Please try this and let me know, I got 512x512 image generation on windows with directml

it works! Getting around 3.5s/it on a 5700XT. I also appreciate that the models are in ONNX, as I am more familiar with the ecosystem.

**Comment by harishanand95** [comment]
Thanks, FYI I just updated the url to point to dml branch than main.. So the new link is https://github.com/harishanand95/diffusers/blob/dml/examples/inference/readme.md#instructions-for-onnx-dml-execution-on-windows. I had previously committed to main branch :/. Anyways, I'll try to get some of these changes in diffusers library than maintaining in fork.

**Comment by LifeIsStrange** [comment]
> Getting around 3.5s/it on a 5700XT

I wonder what are the correponding inference time for a 3060 ti or 3070 ti

**Comment by gitgudchannel** [comment]
I've made a [guide on how to run it on a Windows machine with an AMD GPU](https://youtu.be/ngVBjeu66QI), enjoy!

**Comment by sleepless-ninja** [comment]
> I've made a [guide on how to run it on a Windows machine with an AMD GPU](https://youtu.be/ngVBjeu66QI), enjoy!

Thanks for the guide! The only one I managed to get to work. I have a 6700XT and running at around 1.6s/it.

Now it's time I learn a bit of python. XD

**Comment by KillYourFM** [comment]
How would one do this, but using the Stable Diffusion webUI instead of command line?

**Comment by stull1** [comment]
> I've made a [guide on how to run it on a Windows machine with an AMD GPU](https://youtu.be/ngVBjeu66QI), enjoy!

This worked for me, thx. I optimized the script a little bit for multiple outputs and random seeds. I get around 1.0s/it with a 6800XT.
Is it possible to change the model for example to 1.5 when it's released?

**Comment by gururise** [comment]
> > I've made a [guide on how to run it on a Windows machine with an AMD GPU](https://youtu.be/ngVBjeu66QI), enjoy!
> 
> This worked for me, thx. I optimized the script a little bit for multiple outputs and random seeds. I get around 1.0s/it with a 6800XT. Is it possible to change the model for example to 1.5 when it's released? And what about img2img?

I'm getting around 4.5it/s on my 6800XT running on Linux.

**Comment by xeaon** [comment]
> > does anyone else experiencing rick rolls most of the time? I'm running SD on a RX 6800 XT with params, which don't even fill all of the available VRAM. As this happens on sfw prompts like `an astronout riding a horse`, I've removed the safety checker but then I'm still getting pure black images.
> > I'm `print()`ing `samples_dimm` [here](https://github.com/CompVis/stable-diffusion/blob/main/scripts/txt2img.py#L295). If the resulting image is black, `samples_dimm` is a `tensor` filled with `nan`s
> 
> The rick-roll images are the NSFW filter kicking in. I'm not exactly sure how it detect NSFW images, but it seems to detect a lot of human skin-tone colors and then tag the image as nsfw. You can disable the NSFW filter by tweaking a few lines of the python code. Now, on my 6800xt I get no rick-rolls. The black images are a sign that you probably didn't remove the nsfw filter properly. Try using this [method](https://www.reddit.com/r/StableDiffusion/comments/wv2nw0/tutorial_how_to_remove_the_safety_filter_in_5/) to remove the filter.

This wasn't the issue. As I've stated in my comment, the safetychecker was disabled. My card was slightly undervolted/overclocked and as it seems, it crashed softly during image creation. Turning settings back to normal eliminated black images.

**Comment by raphaelmatto** [comment]
> I've made a [guide on how to run it on a Windows machine with an AMD GPU](https://youtu.be/ngVBjeu66QI), enjoy!

Works for me as well, on a 2018 MacBook Pro running Bootcamp w/a Radeon VII in a Razer Core X. Getting about 2s per iteration ... I ran into an error when trying to run save_onyx.py at 1024x1024. I have 32gb ram. So I can only generate at lower resolutions.

**Comment by chaos4455** [comment]
Guys im getting an error post_quant_conv.onnx no exist folowing this tutorial : https://rentry.co/ayymd-stable-diffustion-v1_4-guide

Anyone here can help me run with radeon rx 6500 xt?

Help and thanks.

**Comment by harishanand95** [comment]
Hi all, diffusers folks updated their code to support onnx now, so you don't need to use my branch/repo to work. 
Here are the steps to install it, 
https://gist.github.com/harishanand95/75f4515e6187a6aa3261af6ac6f61269

**Comment by agizmo** [comment]
First off, thanks to everyone on this thread for getting stable diffusion working on AMD. I took the work of [harishanand95](https://github.com/harishanand95), a blog post at [https://www.travelneil.com/stable-diffusion-windows-amd.html](https://www.travelneil.com/stable-diffusion-windows-amd.html), and my own ideas to create a script that replicates some of the argument options found in this repo's `txt2img.py` script. Not all the argument options are available but the basics work, like image size, # of samples, # of steps, seed #, and guidance scale. I also added the option to render using the CPU and to request a random seed. Check it out at the link below. Follow harishanand95's instructions above for getting everything setup.

[https://github.com/agizmo/ONNX-txt2img](https://github.com/agizmo/ONNX-txt2img)

**Comment by maikelsz** [comment]
does anybody knows how to run save_onnx.py with a already downloaded model checkpoint?

**Comment by maniac-0s** [comment]
[harishanand95](https://github.com/harishanand95) didn't work for me 

(ldm) bla@blaLT:~/projects/stable-diffusion$ python3 scripts/txt2img.py --prompt "a photograph of an astronaut riding a horse" --plms 

/home/bla/miniconda3/envs/ldm/lib/python3.8/site-packages/torch/cuda/__init__.py:83: UserWarning: HIP initialization: Unexpected error from hipGetDeviceCount(). Did you run some cuda functions before calling NumHipDevices() that might have already set an error? Error 101: hipErrorInvalidDevice (Triggered internally at  ../c10/hip/HIPFunctions.cpp:110.)
  return torch._C._cuda_getDeviceCount() > 0
Some weights of the model checkpoint at openai/clip-vit-large-patch14 were not used when initializing CLIPTextModel: (...)

RuntimeError: Unexpected error from hipGetDeviceCount(). Did you run some cuda functions before calling NumHipDevices() that might have already set an error? Error 101: hipErrorInvalidDevice

**Comment by muhademan** [comment]
how to use stable diffusion on amd in windows 10?

**Comment by averad** [comment]
@harishanand95 here are updated install instructions for running StableDiffusion on AMD Videocard(s) using DirectML and the latest Diffusers

Stable Diffusion for AMD GPUs on Windows using DirectML
https://gist.github.com/averad/256c507baa3dcc9464203dc14610d674

**Comment by raphaelmatto** [comment]
@averad's branch worked for me. For others: this time the onnx model is included inside the repo so you don't need to generate it locally. That's nice, but makes the repos huge.

Has anyone got the AMD version working w/the popular web GUI shown here? https://www.youtube.com/watch?v=ycQJDJ-qNI8

I might give it a shot, unless others have already done the work.

**Comment by john1089** [comment]
i'm running into an issue same with @KulerRuler,but it happens even when the prompt is short

**Comment by VitaliyAT** [comment]
is it possible run SD on AMD Radeon Pro W6800 Workstation 32GB ?
