### ISSUE TITLE
im having this problem while installing stable diffusion 

### ISSUE THREAD

**Issue by Marzouqi2000** [CompVis/stable-diffusion#481]
Hello, im trying to install StableDiffusion i followed step by step a tutorial but im having this error, i searched elsewhere but couldn't find a solution.
Idk what to do, some help would be nice !

```
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Commit hash: <none>
Installing gfpgan
Traceback (most recent call last):
  File "C:\Users\user\Desktop\stable\stable-diffusion-webui\[launch.py](https://launch.py/)", line 255, in <module>
    prepare_enviroment()
  File "C:\Users\user\Desktop\stable\stable-diffusion-webui\[launch.py](https://launch.py/)", line 179, in prepare_enviroment
    run_pip(f"install {gfpgan_package}", "gfpgan")
  File "C:\Users\user\Desktop\stable\stable-diffusion-webui\[launch.py](https://launch.py/)", line 63, in run_pip
    return run(f'"{python}" -m pip {args} --prefer-binary{index_url_line}', desc=f"Installing {desc}", errdesc=f"Couldn't install {desc}")
  File "C:\Users\user\Desktop\stable\stable-diffusion-webui\[launch.py](https://launch.py/)", line 34, in run
    raise RuntimeError(message)
RuntimeError: Couldn't install gfpgan.
Command: "C:\Users\user\Desktop\stable\stable-diffusion-webui\venv\Scripts\python.exe" -m pip install git+https://github.com/TencentARC/GFPGAN.git@8d2447a2d918f8eba5a4a01463fd48e45126a379 --prefer-binary
Error code: 1
stdout: Collecting git+https://github.com/TencentARC/GFPGAN.git@8d2447a2d918f8eba5a4a01463fd48e45126a379
  Cloning https://github.com/TencentARC/GFPGAN.git (to revision 8d2447a2d918f8eba5a4a01463fd48e45126a379) to c:\users\user\appdata\local\temp\pip-req-build-76uty_r8

stderr:   ERROR: Error [WinError 2] Le fichier spcifi est introuvable while executing command git version
ERROR: Cannot find command 'git' - do you have 'git' installed and in your PATH?
```

**Comment by GLKSA** [comment]
git is required to add dependent packages during setup. Try downloading and installing git  from https://git-scm.com/download/win and agree to an install for "All Users". When done, check that the path to git appears in a command window command c:> echo %PATH%
