### ISSUE TITLE
Unable to Install Stable Diffusion

### ISSUE THREAD

**Issue by Galimba96** [CompVis/stable-diffusion#484]
Please Help, I am not a coder but I am having issues installing Stable Diffusion. In theory from my understanding at the end I should receive a URL link to go to stablke diffusion but it doesn't appears. I see a lot of error messages here, what do I need to do? 
Thanks

venv "D:\STABLE DIFFUSION\stable-diffusion-webui\venv\Scripts\Python.exe"
Python 3.10.7 (tags/v3.10.7:6cc6b13, Sep  5 2022, 14:08:36) [MSC v.1933 64 bit (AMD64)]
Commit hash: 98947d173e3f1667eba29c904f681047dea9de90
Installing torch and torchvision
Traceback (most recent call last):
  File "D:\STABLE DIFFUSION\stable-diffusion-webui\launch.py", line 255, in <module>
    prepare_enviroment()
  File "D:\STABLE DIFFUSION\stable-diffusion-webui\launch.py", line 173, in prepare_enviroment
    run(f'"{python}" -m {torch_command}', "Installing torch and torchvision", "Couldn't install torch")
  File "D:\STABLE DIFFUSION\stable-diffusion-webui\launch.py", line 34, in run
    raise RuntimeError(message)
RuntimeError: Couldn't install torch.
Command: "D:\STABLE DIFFUSION\stable-diffusion-webui\venv\Scripts\python.exe" -m pip install torch==1.12.1+cu113 torchvision==0.13.1+cu113 --extra-index-url https://download.pytorch.org/whl/cu113
Error code: 2
stdout: Looking in indexes: https://pypi.org/simple, https://download.pytorch.org/whl/cu113
Collecting torch==1.12.1+cu113
  Downloading https://download.pytorch.org/whl/cu113/torch-1.12.1%2Bcu113-cp310-cp310-win_amd64.whl (2143.8 MB)
     ----------------------                   1.2/2.1 GB 9.1 MB/s eta 0:01:43

stderr: ERROR: Exception:
Traceback (most recent call last):
  File "D:\STABLE DIFFUSION\stable-diffusion-webui\venv\lib\site-packages\pip\_vendor\urllib3\response.py", line 435, in _error_catcher
    yield
  File "D:\STABLE DIFFUSION\stable-diffusion-webui\venv\lib\site-packages\pip\_vendor\urllib3\response.py", line 516, in read
    data = self._fp.read(amt) if not fp_closed else b""
  File "D:\STABLE DIFFUSION\stable-diffusion-webui\venv\lib\site-packages\pip\_vendor\cachecontrol\filewrapper.py", line 90, in read
    data = self.__fp.read(amt)
  File "C:\Users\franc\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 465, in read
    s = self.fp.read(amt)
  File "C:\Users\franc\AppData\Local\Programs\Python\Python310\lib\socket.py", line 705, in readinto
    return self._sock.recv_into(b)
  File "C:\Users\franc\AppData\Local\Programs\Python\Python310\lib\ssl.py", line 1274, in recv_into
    return self.read(nbytes, buffer)
  File "C:\Users\franc\AppData\Local\Programs\Python\Python310\lib\ssl.py", line 1130, in read
    return self._sslobj.read(len, buffer)
TimeoutError: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\STABLE DIFFUSION\stable-diffusion-webui\venv\lib\site-packages\pip\_internal\cli\base_command.py", line 167, in exc_logging_wrapper
    status = run_func(*args)
  File "D:\STABLE DIFFUSION\stable-diffusion-webui\venv\lib\site-packages\pip\_internal\cli\req_command.py", line 247, in wrapper
    return func(self, options, args)
  File "D:\STABLE DIFFUSION\stable-diffusion-webui\venv\lib\site-packages\pip\_internal\commands\install.py", line 369, in run
    requirement_set = resolver.resolve(
  File "D:\STABLE DIFFUSION\stable-diffusion-webui\venv\lib\site-packages\pip\_internal\resolution\resolvelib\resolver.py", line 92, in resolve
    result = self._result = resolver.resolve(
  File "D:\STABLE DIFFUSION\stable-diffusion-webui\venv\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 481, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "D:\STABLE DIFFUSION\stable-diffusion-webui\venv\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 348, in resolve
    self._add_to_criteria(self.state.criteria, r, parent=None)
  File "D:\STABLE DIFFUSION\stable-diffusion-webui\venv\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 172, in _add_to_criteria
    if not criterion.candidates:
  File "D:\STABLE DIFFUSION\stable-diffusion-webui\venv\lib\site-packages\pip\_vendor\resolvelib\structs.py", line 151, in __bool__
    return bool(self._sequence)
  File "D:\STABLE DIFFUSION\stable-diffusion-webui\venv\lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 155, in __bool__
    return any(self)
  File "D:\STABLE DIFFUSION\stable-diffusion-webui\venv\lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 143, in <genexpr>
    return (c for c in iterator if id(c) not in self._incompatible_ids)
  File "D:\STABLE DIFFUSION\stable-diffusion-webui\venv\lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 47, in _iter_built
    candidate = func()
  File "D:\STABLE DIFFUSION\stable-diffusion-webui\venv\lib\site-packages\pip\_internal\resolution\resolvelib\factory.py", line 206, in _make_candidate_from_link
    self._link_candidate_cache[link] = LinkCandidate(
  File "D:\STABLE DIFFUSION\stable-diffusion-webui\venv\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 297, in __init__
    super().__init__(
  File "D:\STABLE DIFFUSION\stable-diffusion-webui\venv\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 162, in __init__
    self.dist = self._prepare()
  File "D:\STABLE DIFFUSION\stable-diffusion-webui\venv\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 231, in _prepare
    dist = self._prepare_distribution()
  File "D:\STABLE DIFFUSION\stable-diffusion-webui\venv\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 308, in _prepare_distribution
    return preparer.prepare_linked_requirement(self._ireq, parallel_builds=True)
  File "D:\STABLE DIFFUSION\stable-diffusion-webui\venv\lib\site-packages\pip\_internal\operations\prepare.py", line 438, in prepare_linked_requirement
    return self._prepare_linked_requirement(req, parallel_builds)
  File "D:\STABLE DIFFUSION\stable-diffusion-webui\venv\lib\site-packages\pip\_internal\operations\prepare.py", line 483, in _prepare_linked_requirement
    local_file = unpack_url(
  File "D:\STABLE DIFFUSION\stable-diffusion-webui\venv\lib\site-packages\pip\_internal\operations\prepare.py", line 165, in unpack_url
    file = get_http_url(
  File "D:\STABLE DIFFUSION\stable-diffusion-webui\venv\lib\site-packages\pip\_internal\operations\prepare.py", line 106, in get_http_url
    from_path, content_type = download(link, temp_dir.path)
  File "D:\STABLE DIFFUSION\stable-diffusion-webui\venv\lib\site-packages\pip\_internal\network\download.py", line 147, in __call__
    for chunk in chunks:
  File "D:\STABLE DIFFUSION\stable-diffusion-webui\venv\lib\site-packages\pip\_internal\cli\progress_bars.py", line 53, in _rich_progress_bar
    for chunk in iterable:
  File "D:\STABLE DIFFUSION\stable-diffusion-webui\venv\lib\site-packages\pip\_internal\network\utils.py", line 63, in response_chunks
    for chunk in response.raw.stream(
  File "D:\STABLE DIFFUSION\stable-diffusion-webui\venv\lib\site-packages\pip\_vendor\urllib3\response.py", line 573, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "D:\STABLE DIFFUSION\stable-diffusion-webui\venv\lib\site-packages\pip\_vendor\urllib3\response.py", line 509, in read
    with self._error_catcher():
  File "C:\Users\franc\AppData\Local\Programs\Python\Python310\lib\contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "D:\STABLE DIFFUSION\stable-diffusion-webui\venv\lib\site-packages\pip\_vendor\urllib3\response.py", line 440, in _error_catcher
    raise ReadTimeoutError(self._pool, None, "Read timed out.")
pip._vendor.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='download.pytorch.org', port=443): Read timed out.

[notice] A new release of pip available: 22.2.2 -> 22.3.1
[notice] To update, run: D:\STABLE DIFFUSION\stable-diffusion-webui\venv\Scripts\python.exe -m pip install --upgrade pip

Press any key to continue . . .

**Comment by GLKSA** [comment]
On win 10 I had no luck at all using virtual environments due to incompatible usage of environment variables. I downloaded base versions of everything (Python, Miniconda, git) and let them alter the system and user variables. then run "git clone https://github.com/CompVis/stable-diffusion.git"  Then start a miniconda3 window from the win10 Anaconda2 menu. cd to the stable-diffusion project folder. Use this window to run all your conda and python code, otherwise you can't run conda. Do "conda install --file environment.yaml" in the folder you cloned into. Then run "python scripts/txt2img.py --prompt "a photograph of an ballet dancer riding a horse" --plms --n_samples 1" in the miniconda window in the project folder. best of luck!

**Comment by GLKSA** [comment]
also you need  "conda activate ldm" everytime you open the miniconda window.

**Comment by reecelightning** [comment]
I'm having the exact same problem, I'd appreciate some help please

**Comment by Galimba96** [comment]
> also you need "conda activate ldm" everytime you open the miniconda window.

After you did all of this it worked fine?

**Comment by Galimba96** [comment]
> I'm having the exact same problem, I'd appreciate some help please

Hello, So now it worked for me (you can try this). Ps: I didn't follow the previous suggestion because I wanted to try something first. 

So what I did is follow this video (like the first time I did). https://www.youtube.com/watch?v=vg8-NSbaWZI&ab_channel=Aitrepreneur

So 0) I uninstalled everything (pyton, git, stable diffusion) and deleted all the files 1) I downloaded the 3 softwares he requested. 2) I created a new folder on the C: disk (my error last time was to create the folder on the desktop i think) 3) I moved directly the files from the lower bar of the internet browser into the new folder 4) I installed pyton as he suggested 5) I downloaded git like he suggested but I have used the same new folder I created as the file location. (so now the git app is together with the other exe files and rar.) 6) i extracted the files he suggested into the new folder. 7) when you need to copy the same text on the code panel i did like this. (I have opened the page and copied the url, then on the code page I wrote git clone and pasted the url). The final result needs to be identical to his. 8) I followed all the other steps and it worked. 

Let me know if this works for you :)

**Comment by reecelightning** [comment]
> > I'm having the exact same problem, I'd appreciate some help please
> 
> Hello, So now it worked for me (you can try this). Ps: I didn't follow the previous suggestion because I wanted to try something first.
> 
> So what I did is follow this video (like the first time I did). https://www.youtube.com/watch?v=vg8-NSbaWZI&ab_channel=Aitrepreneur
> 
> So 0) I uninstalled everything (pyton, git, stable diffusion) and deleted all the files 1) I downloaded the 3 softwares he requested. 2) I created a new folder on the C: disk (my error last time was to create the folder on the desktop i think) 3) I moved directly the files from the lower bar of the internet browser into the new folder 4) I installed pyton as he suggested 5) I downloaded git like he suggested but I have used the same new folder I created as the file location. (so now the git app is together with the other exe files and rar.) 6) i extracted the files he suggested into the new folder. 7) when you need to copy the same text on the code panel i did like this. (I have opened the page and copied the url, then on the code page I wrote git clone and pasted the url). The final result needs to be identical to his. 8) I followed all the other steps and it worked.
> 
> Let me know if this works for you :)

Thanks for trying to help but I tried your instructions and watched the video. I attempted it twice and ended up with the same result and problem you and I had last time. I'm keeping my folder in my C: disk and i'm using all the links in the video but still just keep getting the same errors.

If anyone could help that'd be great

**Comment by GLKSA** [comment]
Hi reecelightning, please post your error. also confirm you are using "base" installs of the 3 software ( installed on your actual OS), not virtual environments except the one referenced in environment.yaml, which is confusingly named "ldm".

**Comment by reecelightning** [comment]
Yes I am using the 2 base installs of the software installed on my OS. My error is the exact same as the one posted above by Galimba

**Comment by r-set** [comment]
@Galimba96 Try using python version 3.10.6, make sure you are using 64-bit version. It won't get an error with "Couldn't install torch"

**Comment by reecelightning** [comment]
Having a new issue now. Can anyone help with this?

Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Commit hash: 828438b4a190759807f9054932cae3a8b880ddf1
Traceback (most recent call last):
  File "C:\Ai\Stable-Diffusion\stable-diffusion-webui\launch.py", line 250, in <module>
    prepare_enviroment()
  File "C:\Ai\Stable-Diffusion\stable-diffusion-webui\launch.py", line 174, in prepare_enviroment
    run_python("import torch; assert torch.cuda.is_available(), 'Torch is not able to use GPU; add --skip-torch-cuda-test to COMMANDLINE_ARGS variable to disable this check'")
  File "C:\Ai\Stable-Diffusion\stable-diffusion-webui\launch.py", line 58, in run_python
    return run(f'"{python}" -c "{code}"', desc, errdesc)
  File "C:\Ai\Stable-Diffusion\stable-diffusion-webui\launch.py", line 34, in run
    raise RuntimeError(message)
RuntimeError: Error running command.
Command: "C:\Ai\Stable-Diffusion\stable-diffusion-webui\venv\Scripts\python.exe" -c "import torch; assert torch.cuda.is_available(), 'Torch is not able to use GPU; add --skip-torch-cuda-test to COMMANDLINE_ARGS variable to disable this check'"
Error code: 1
stdout: <empty>
stderr: C:\Ai\Stable-Diffusion\stable-diffusion-webui\venv\lib\site-packages\torch\cuda\__init__.py:83: UserWarning: CUDA initialization: CUDA driver initialization failed, you might not have a CUDA gpu. (Triggered internally at  ..\c10\cuda\CUDAFunctions.cpp:109.)
  return torch._C._cuda_getDeviceCount() > 0
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AssertionError: Torch is not able to use GPU; add --skip-torch-cuda-test to COMMANDLINE_ARGS variable to disable this check

**Comment by arcanorca** [comment]
If anyone tried all the options and still can't fix it yet, try this: after uninstalling python there are still some files at users/yourusername/AppData. I installed and uninstalled for like 6-7 times with all different options like trying a different HDD, different root name etc. and still gave "Couldn't install torch" error. I don't know how, but it worked for me when I deleted all Python and pip files at AppData and then tried a clean installation of Python and Stable Diffusion WebUI. Good luck.

**Comment by raybuay** [comment]
Same here, i have already tried all python versions from 3.10.6 to 3.11.0 and all i have is FRUSTRATION. Here are my errors:
C:\StableDifusion\stable-diffusion-webui>pause
Press any key to continue . . .
venv "C:\StableDifusion\stable-diffusion-webui\venv\Scripts\Python.exe"
Python 3.10.8 (tags/v3.10.8:aaaf517, Oct 11 2022, 16:50:30) [MSC v.1933 64 bit (AMD64)]
Commit hash: 828438b4a190759807f9054932cae3a8b880ddf1
Installing requirements for Web UI
Launching Web UI with arguments:
Traceback (most recent call last):
  File "C:\StableDifusion\stable-diffusion-webui\launch.py", line 251, in <module>
    start()
  File "C:\StableDifusion\stable-diffusion-webui\launch.py", line 242, in start
    import webui
  File "C:\StableDifusion\stable-diffusion-webui\webui.py", line 13, in <module>
    from modules import devices, sd_samplers, upscaler, extensions, localization
  File "C:\StableDifusion\stable-diffusion-webui\modules\sd_samplers.py", line 11, in <module>
    from modules import prompt_parser, devices, processing, images
  File "C:\StableDifusion\stable-diffusion-webui\modules\processing.py", line 11, in <module>
    import cv2
  File "C:\StableDifusion\stable-diffusion-webui\venv\lib\site-packages\cv2\__init__.py", line 181, in <module>
    bootstrap()
  File "C:\StableDifusion\stable-diffusion-webui\venv\lib\site-packages\cv2\__init__.py", line 153, in bootstrap
    native_module = importlib.import_module("cv2")
  File "C:\Users\raymond\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: DLL load failed while importing cv2: The specified module could not be found.
Press any key to continue . . .

**Comment by r-set** [comment]
@raybuay miniconda installed?
If yes, then try to copy python3.dll file from python folder to miniconda folder
C:\Users\you\AppData\Local\Programs\Python\Python310 → C:\Users\you\miniconda3

**Comment by wiebenor** [comment]
I'm having similar issues myself, where it's getting "Readtimeouterror" messages, and not sure where to go from here... Will try that video probably next, but idk... I just HATE Python in general for this very reason, that being that it's hard to work with... Question for anyone who has gotten stable diffusion to work, have any of you been able to set the environment up on one machine, then after torch is installed and whatnot, just copy the entire git clone including downloaded dependencies for torchvision, to an external drive then install into a different (and not portable, high end) system, and run it, so long as it's installed in the same place(without needing to reinstall torchvision)??? I don't have internet at home and my cell phone internet doesn't like this whole torchvision install stuff, I'm thinking, therefore I do most of my main stuff on a laptop whenceforth it's portable enough that I can hop on WiFi anywhere locally where I have free access to it

**Comment by GreenMario94** [comment]
I have the same problem as raybuay. I tried installing miniconda and copying python3.dll, but it didn't help. I tried Python 3.11, but then Torch wouldn't install.

Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Commit hash: 4b3c5bc24bffdf429c463a465763b3077fe55eb8
Installing requirements for Web UI
Launching Web UI with arguments:
Traceback (most recent call last):
  File "C:\Users\J\Desktop\stable-diffusion-webui\launch.py", line 294, in <module>
    start()
  File "C:\Users\J\Desktop\stable-diffusion-webui\launch.py", line 285, in start
    import webui
  File "C:\Users\J\Desktop\stable-diffusion-webui\webui.py", line 14, in <module>
    from modules import shared, devices, sd_samplers, upscaler, extensions, localization, ui_tempdir
  File "C:\Users\J\Desktop\stable-diffusion-webui\modules\sd_samplers.py", line 11, in <module>
    from modules import prompt_parser, devices, processing, images
  File "C:\Users\J\Desktop\stable-diffusion-webui\modules\processing.py", line 11, in <module>
    import cv2
  File "C:\Users\J\Desktop\stable-diffusion-webui\venv\lib\site-packages\cv2\__init__.py", line 181, in <module>
    bootstrap()
  File "C:\Users\J\Desktop\stable-diffusion-webui\venv\lib\site-packages\cv2\__init__.py", line 153, in bootstrap
    native_module = importlib.import_module("cv2")
  File "C:\Users\J\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: DLL load failed while importing cv2: The specified module could not be found.
Press any key to continue . . .

Does anyone know how to solve this?

**Comment by raybuay** [comment]
I have the exact same problem as you greenMario. And i have tried in different machines and they all give the same end result. some with windows 10 updated all the way and some with a slight delay in update. I'm really giving up on this collaboration, there is for sure something wrong here.

**Comment by raybuay** [comment]
> C:\Users\you\AppData\Local\Programs\Python\Python310

yes, that didn't work, nothing does. and what's funny is that all youtube installation instructions are the same and none work right now!

**Comment by r-set** [comment]
@reecelightning try install Python 3.7

**Comment by r-set** [comment]
@raybuay @GreenMario94 check installation Media Feature Pack https://support.microsoft.com/en-us/topic/media-feature-pack-list-for-windows-n-editions-c1c6fffa-d052-8338-7a79-a4bb980a700a
Make sure you have Visual C++ redistributable 2015 installed
Check if folders cv2 and opencv_python exists in miniconda. Try deleting folders maybe they conflict. Path \lib\site-packages\
Then running pip install opencv-python

**Comment by raybuay** [comment]
r-set, thank you for trying to help but the exact same thing continues to happen. I'm really disgusted by this severely. It seems so easy in every youtube video there is but THEY all state the same procedure and it is just giving me the same result:

venv "C:\ai\stable-diffusion-webui\venv\Scripts\Python.exe"
Python 3.10.7 (tags/v3.10.7:6cc6b13, Sep  5 2022, 14:08:36) [MSC v.1933 64 bit (AMD64)]
Commit hash: 46b0d230e7c13e247eabb22e1103ce512e7ed6b1
Installing requirements for Web UI
Launching Web UI with arguments:
Traceback (most recent call last):
  File "C:\ai\stable-diffusion-webui\launch.py", line 294, in <module>
    start()
  File "C:\ai\stable-diffusion-webui\launch.py", line 285, in start
    import webui
  File "C:\ai\stable-diffusion-webui\webui.py", line 14, in <module>
    from modules import shared, devices, sd_samplers, upscaler, extensions, localization, ui_tempdir
  File "C:\ai\stable-diffusion-webui\modules\sd_samplers.py", line 12, in <module>
    from modules import prompt_parser, devices, processing, images
  File "C:\ai\stable-diffusion-webui\modules\processing.py", line 11, in <module>
    import cv2
  File "C:\ai\stable-diffusion-webui\venv\lib\site-packages\cv2\__init__.py", line 181, in <module>
    bootstrap()
  File "C:\ai\stable-diffusion-webui\venv\lib\site-packages\cv2\__init__.py", line 153, in bootstrap
    native_module = importlib.import_module("cv2")
  File "C:\Users\raymond\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: DLL load failed while importing cv2: The specified module could not be found.

THIS IS SO NOT COOL.

**Comment by raybuay** [comment]
Ok, I just keep trying and it finally install.
python 3.10.6 was the version that worked
also the extra media install did help.
All is good
thanks
r.y

**Comment by GreenMario94** [comment]
@r-set Thank you, after I installed the Media Feature Pack it started to work.

**Comment by QuackersDown** [comment]
I decided to do something extremely stupid, I did exactly as the launcher told me to do and put it in the Documents tab and somehow that just.. Fixed it. I'm by no means a technician, coder or such and don't even know the name of it. But that worked! I just wish they'd told us where to put it.

![Capture](https://user-images.githubusercontent.com/98381442/206856052-8a737037-c618-4713-9032-5be136ad75e3.PNG)

**Comment by KT1199** [comment]
Same here.

venv "C:\stable-diffusion-webui-master\venv\Scripts\Python.exe"
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Commit hash: <none>
Installing torch and torchvision
Traceback (most recent call last):
  File "C:\stable-diffusion-webui-master\launch.py", line 294, in <module>
    prepare_environment()
  File "C:\stable-diffusion-webui-master\launch.py", line 206, in prepare_environment
    run(f'"{python}" -m {torch_command}', "Installing torch and torchvision", "Couldn't install torch")
  File "C:\stable-diffusion-webui-master\launch.py", line 49, in run
    raise RuntimeError(message)
RuntimeError: Couldn't install torch.
Command: "C:\stable-diffusion-webui-master\venv\Scripts\python.exe" -m pip install torch==1.12.1+cu113 torchvision==0.13.1+cu113 --extra-index-url https://download.pytorch.org/whl/cu113
Error code: 1
stdout: <empty>
stderr: C:\stable-diffusion-webui-master\venv\Scripts\python.exe: No module named pip


Oddly enough, Exit code 3 and error code 1 are occurring a lot. 
also I checked the App data folder, but it only contained the 3.10 version folder. But I still get error code 1.

**Comment by troy232** [comment]
> > > I'm having the exact same problem, I'd appreciate some help please
> > 
> > 
> > Hello, So now it worked for me (you can try this). Ps: I didn't follow the previous suggestion because I wanted to try something first.
> > So what I did is follow this video (like the first time I did). https://www.youtube.com/watch?v=vg8-NSbaWZI&ab_channel=Aitrepreneur
> > So 0) I uninstalled everything (pyton, git, stable diffusion) and deleted all the files 1) I downloaded the 3 softwares he requested. 2) I created a new folder on the C: disk (my error last time was to create the folder on the desktop i think) 3) I moved directly the files from the lower bar of the internet browser into the new folder 4) I installed pyton as he suggested 5) I downloaded git like he suggested but I have used the same new folder I created as the file location. (so now the git app is together with the other exe files and rar.) 6) i extracted the files he suggested into the new folder. 7) when you need to copy the same text on the code panel i did like this. (I have opened the page and copied the url, then on the code page I wrote git clone and pasted the url). The final result needs to be identical to his. 8) I followed all the other steps and it worked.
> > Let me know if this works for you :)
> 
> Thanks for trying to help but I tried your instructions and watched the video. I attempted it twice and ended up with the same result and problem you and I had last time. I'm keeping my folder in my C: disk and i'm using all the links in the video but still just keep getting the same errors.
> 
> If anyone could help that'd be great

in which part of the video?

**Comment by dajanaelez** [comment]
Hello, I am having a problem with outdated driver - any sugggestion which update can I make for Win 10 ?

stderr: C:\AI\stable-diffusion-webui\venv\lib\site-packages\torch\cuda\__init__.py:88: UserWarning: CUDA initialization: The NVIDIA driver on your system is too old (found version 10010). Please update your GPU driver by downloading and installing a new version from the URL: http://www.nvidia.com/Download/index.aspx Alternatively, go to: https://pytorch.org to install a PyTorch version that has been compiled with your version of the CUDA driver

**Comment by akuo8181** [comment]
> 

HOW?
I already have python 3.10.6 and it's on the Desktop but still do not work, what to do?

OSError: [WinError 126] The specified module could not be found. Error loading "C:\Users\user\Desktop\l;skdjv\stable-diffusion-webui-master\venv\lib\site-packages\torch\lib\caffe2_nvrtc.dll" or one of its dependencies.

**Comment by rinaldop** [comment]
Same error here.

**Comment by vomitting** [comment]
Ребята, выручайте. Суть такая, имеется ПК:
AMD Ryzen 7 5700X 4641MHz
GigaByte B550 AORUS ELITE V2
Kingston FURY Beast Black RGB 3600mhz 32gb
Radeon RX 580 GAMING OC X 8G
Samsung SSD 850 EVO 250GB
Samsung SSD 970 EVO 500GB
WD Purple 3 Тб + Green 1 ТБ
Chieftec 700W cft-700-14cs
Deepcool gammaxx 400EX

Скачал и настроил stable diffusion, а именно stable-diffusion-webui-directml-master.
В конфиге при запуске:
@echo off

set PYTHON=
set GIT=
set VENV_DIR=
set GIT_SSL_NO_VERIFY=true

set COMMANDLINE_ARGS=--lowvram --precision full --no-half --no-half-vae --opt-sub-quad-attention --opt-split-attention --opt-split-attention-v1 --disable-nan-check --autolaunch --theme=dark --skip-torch-cuda-test --no-half --disable-nan-check


call webui.bat

Так вот, Веб-интерфейс запускается и мало того, запускается процесс генерации, Но, при заключительной стадии, а именно сохранение проекта в папку output, компьютер отключается и не включается до тех пор пока я его не обесточу. То есть, это стабильно в один и тот же момент происходит, именно при сохранении, во время генерации все проходит нормально и быстро.

Драйвера, Amernimezone + SAM настройка для активации более 4G above.

Может у кого-нибудь есть идеи?
