### ISSUE TITLE
Upscaler LDSR gives 'ldm.models.autoencoder' has no attribute 'VQModelInterface' error

### ISSUE THREAD

**Issue by ebziw** [CompVis/stable-diffusion#510]
Lastest code, image created with SD 2.0, F222.ckpt, 768x768. Select LDSR upscaler, error occurs:

To create a public link, set `share=True` in `launch()`.
Loading model from /home/liyong/stable-diffusion-webui/models/LDSR/model.ckpt
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 113.62 M params.
Keeping EMAs of 308.
Error completing request
Arguments: (0, 0, <PIL.Image.Image image mode=RGB size=768x768 at 0x7FB4211727F0>, None, '', '', True, 0, 0, 0, 4, 512, 512, True, 3, 0, 1, False) {}
Traceback (most recent call last):
  File "/home/liyong/stable-diffusion-webui/modules/ui.py", line 169, in f
    res = list(func(*args, **kwargs))
  File "/home/liyong/stable-diffusion-webui/webui.py", line 58, in f
    res = func(*args, **kwargs)
  File "/home/liyong/stable-diffusion-webui/modules/extras.py", line 189, in run_extras
    image, info = op(image, info)
  File "/home/liyong/stable-diffusion-webui/modules/extras.py", line 150, in run_upscalers_blend
    res = upscale(image, *upscale_args)
  File "/home/liyong/stable-diffusion-webui/modules/extras.py", line 118, in upscale
    res = upscaler.scaler.upscale(image, resize, upscaler.data_path)
  File "/home/liyong/stable-diffusion-webui/modules/upscaler.py", line 64, in upscale
    img = self.do_upscale(img, selected_model)
  File "/home/liyong/stable-diffusion-webui/modules/ldsr_model.py", line 54, in do_upscale
    return ldsr.super_resolution(img, ddim_steps, self.scale)
  File "/home/liyong/stable-diffusion-webui/modules/ldsr_model_arch.py", line 87, in super_resolution
    model = self.load_model_from_config(half_attention)
  File "/home/liyong/stable-diffusion-webui/modules/ldsr_model_arch.py", line 25, in load_model_from_config
    model = instantiate_from_config(config.model)
  File "/home/liyong/stable-diffusion-webui/repositories/stable-diffusion-stability-ai/ldm/util.py", line 79, in instantiate_from_config
    return get_obj_from_str(config["target"])(**config.get("params", dict()))
  File "/home/liyong/stable-diffusion-webui/repositories/stable-diffusion-stability-ai/ldm/models/diffusion/ddpm.py", line 562, in __init__
    self.instantiate_first_stage(first_stage_config)
  File "/home/liyong/stable-diffusion-webui/repositories/stable-diffusion-stability-ai/ldm/models/diffusion/ddpm.py", line 614, in instantiate_first_stage
    model = instantiate_from_config(config)
  File "/home/liyong/stable-diffusion-webui/repositories/stable-diffusion-stability-ai/ldm/util.py", line 79, in instantiate_from_config
    return get_obj_from_str(config["target"])(**config.get("params", dict()))
  File "/home/liyong/stable-diffusion-webui/repositories/stable-diffusion-stability-ai/ldm/util.py", line 87, in get_obj_from_str
    return getattr(importlib.import_module(module, package=None), cls)
AttributeError: module 'ldm.models.autoencoder' has no attribute 'VQModelInterface'

**Comment by JoyceLiu-LQ** [comment]
同问

**Comment by booker-max** [comment]
同问，您解决了么

**Comment by Songxx-7** [comment]
同问，为什么出现在ldm.models.autoencoder中无法获取类'VQModelTorch'的情况？

**Comment by Songxx-7** [comment]
> 同问，为什么出现在ldm.models.autoencoder中无法获取类'VQModelTorch'的情况？

应该是当前环境下有另外一个同名的ldm script, 所以报错了，我把文件夹的名称ldm改为了latentDM（反正改一下就行了），虽然在project里面ls了一下没有别的ldm冲突但是应该是在我看不到的地方冲突了。

**Comment by Songxx-7** [comment]
> 同问，为什么出现在ldm.models.autoencoder中无法获取类'VQModelTorch'的情况？
该问题已解决，应该是当前环境下有另外一个同名的ldm script, 所以报错了，我把文件夹的名称ldm改为了latentDM（反正改一下就行了）。
