### ISSUE TITLE
Unable to use SD2.0 model: Files downloading is interrupted

### ISSUE THREAD

**Issue by Iory1998** [CompVis/stable-diffusion#515]
I am using the latest update of the webHi,
I downloaded the SD2.0 model and the config.yaml file from https://huggingface.co/stabilityai/stable-diffusion-2/blob/main/768-v-ema.ckpt, renamed the config.yaml exactly the same name (sd_v2.0-768-v-ema.ckpt and sd_v2.0-768-v-ema.yaml) and put them in the models\Stable-diffusion folder. This is pretty standard and I've been doing it for many models.

The issue starts when I switch to use the sd_v2.0-768-v-ema.ckpt in the webui. I see in the following:
Loading config from: D:\StabDiff\webui\models\Stable-diffusion\Stable Diffusion\sd_v2.0-768-v-ema.yaml
LatentDiffusion: Running in v-prediction mode
DiffusionWrapper has 865.91 M params.
Downloading:   3%|██
After downloading (God knows what) for a while, the downloading process stops due to the following errors.

File "D:\StabDiff\webui\venv\lib\site-packages\urllib3\response.py", line 443, in _error_catcher
    yield
  File "D:\StabDiff\webui\venv\lib\site-packages\urllib3\response.py", line 566, in read
    data = self._fp_read(amt) if not fp_closed else b""
  File "D:\StabDiff\webui\venv\lib\site-packages\urllib3\response.py", line 532, in _fp_read
    return self._fp.read(amt) if amt is not None else self._fp.read()
  File "C:\Users\l\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 465, in read
    s = self.fp.read(amt)
  File "C:\Users\\AppData\Local\Programs\Python\Python310\lib\socket.py", line 705, in readinto
    return self._sock.recv_into(b)
  File "C:\Users\\AppData\Local\Programs\Python\Python310\lib\ssl.py", line 1274, in recv_into
    return self.read(nbytes, buffer)
  File "C:\Users\\AppData\Local\Programs\Python\Python310\lib\ssl.py", line 1130, in read
    return self._sslobj.read(len, buffer)
TimeoutError: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\StabDiff\webui\venv\lib\site-packages\requests\models.py", line 753, in generate
    for chunk in self.raw.stream(chunk_size, decode_content=True):
  File "D:\StabDiff\webui\venv\lib\site-packages\urllib3\response.py", line 627, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "D:\StabDiff\webui\venv\lib\site-packages\urllib3\response.py", line 565, in read
    with self._error_catcher():
  File "C:\Users\Abdelhak Khalil\AppData\Local\Programs\Python\Python310\lib\contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "D:\StabDiff\webui\venv\lib\site-packages\urllib3\response.py", line 448, in _error_catcher
    raise ReadTimeoutError(self._pool, None, "Read timed out.")
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='cdn-lfs.huggingface.co', port=443): Read timed out.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\StabDiff\webui\venv\lib\site-packages\gradio\routes.py", line 284, in run_predict
    output = await app.blocks.process_api(
  File "D:\StabDiff\webui\venv\lib\site-packages\gradio\blocks.py", line 982, in process_api
    result = await self.call_function(fn_index, inputs, iterator)
  File "D:\StabDiff\webui\venv\lib\site-packages\gradio\blocks.py", line 824, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "D:\StabDiff\webui\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "D:\StabDiff\webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "D:\StabDiff\webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "D:\StabDiff\webui\modules\ui.py", line 1603, in <lambda>
    fn=lambda value, k=k: run_settings_single(value, key=k),
  File "D:\StabDiff\webui\modules\ui.py", line 1444, in run_settings_single
    if not opts.set(key, value):
  File "D:\StabDiff\webui\modules\shared.py", line 477, in set
    self.data_labels[key].onchange()
  File "D:\StabDiff\webui\modules\call_queue.py", line 15, in f
    res = func(*args, **kwargs)
  File "D:\StabDiff\webui\webui.py", line 62, in <lambda>
    shared.opts.onchange("sd_model_checkpoint", wrap_queued_call(lambda: modules.sd_models.reload_model_weights()))
  File "D:\StabDiff\webui\modules\sd_models.py", line 292, in reload_model_weights
    load_model(checkpoint_info)
  File "D:\StabDiff\webui\modules\sd_models.py", line 260, in load_model
    sd_model = instantiate_from_config(sd_config.model)
  File "D:\StabDiff\webui\repositories\stable-diffusion-stability-ai\ldm\util.py", line 79, in instantiate_from_config
    return get_obj_from_str(config["target"])(**config.get("params", dict()))
  File "D:\StabDiff\webui\repositories\stable-diffusion-stability-ai\ldm\models\diffusion\ddpm.py", line 563, in __init__
    self.instantiate_cond_stage(cond_stage_config)
  File "D:\StabDiff\webui\repositories\stable-diffusion-stability-ai\ldm\models\diffusion\ddpm.py", line 630, in instantiate_cond_stage
    model = instantiate_from_config(config)
  File "D:\StabDiff\webui\repositories\stable-diffusion-stability-ai\ldm\util.py", line 79, in instantiate_from_config
    return get_obj_from_str(config["target"])(**config.get("params", dict()))
  File "D:\StabDiff\webui\repositories\stable-diffusion-stability-ai\ldm\modules\encoders\modules.py", line 147, in __init__
    model, _, _ = open_clip.create_model_and_transforms(arch, device=torch.device('cpu'), pretrained=version)
  File "D:\StabDiff\webui\venv\lib\site-packages\open_clip\factory.py", line 201, in create_model_and_transforms
    model = create_model(
  File "D:\StabDiff\webui\venv\lib\site-packages\open_clip\factory.py", line 159, in create_model
    checkpoint_path = download_pretrained(pretrained_cfg, cache_dir=cache_dir)
  File "D:\StabDiff\webui\venv\lib\site-packages\open_clip\pretrained.py", line 312, in download_pretrained
    target = download_pretrained_from_hf(model_id, cache_dir=cache_dir)
  File "D:\StabDiff\webui\venv\lib\site-packages\open_clip\pretrained.py", line 282, in download_pretrained_from_hf
    cached_file = hf_hub_download(model_id, filename, revision=revision, cache_dir=cache_dir)
  File "D:\StabDiff\webui\venv\lib\site-packages\huggingface_hub\file_download.py", line 1226, in hf_hub_download
    http_get(
  File "D:\StabDiff\webui\venv\lib\site-packages\huggingface_hub\file_download.py", line 490, in http_get
    for chunk in r.iter_content(chunk_size=1024):
  File "D:\StabDiff\webui\venv\lib\site-packages\requests\models.py", line 760, in generate
    raise ConnectionError(e)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='cdn-lfs.huggingface.co', port=443): Read timed out.
Downloading:   3%|██                                                            | 131M/3.94G [27:31<33:46:23, 31.4kB/s]

So, anyone knows why do I get this error? Am I missing something?

**Comment by Iory1998** [comment]
Downloaded open_clip_pytorch_model.bin from https://huggingface.co/laion/CLIP-ViT-H-14-laion2B-s32B-b79K/tree/main and then put it in C:\Users\username\.cache\huggingface\hub\models--laion--CLIP-ViT-H-14-laion2B-s32B-b79K\snapshots\58a1e03a7acfacbe6b95ebc24ae0394eda6a14fc
This should work.
