### ISSUE TITLE
Error in loop everytime i put an image on inpaint

### ISSUE THREAD

**Issue by Dleeps** [CompVis/stable-diffusion#519]
Traceback (most recent call last):
  File "C:\ai\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 284, in run_predict
    output = await app.blocks.process_api(
  File "C:\ai\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 980, in process_api
    inputs = self.preprocess_data(fn_index, inputs, state)
  File "C:\ai\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 891, in preprocess_data
    processed_input.append(block.preprocess(inputs[i]))
  File "C:\ai\stable-diffusion-webui\venv\lib\site-packages\gradio\components.py", line 1374, in preprocess
    mask_im = processing_utils.decode_base64_to_image(mask)
  File "C:\ai\stable-diffusion-webui\venv\lib\site-packages\gradio\processing_utils.py", line 45, in decode_base64_to_image
    content = encoding.split(";")[1]
AttributeError: 'NoneType' object has no attribute 'split'
Traceback (most recent call last):
  File "C:\ai\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 284, in run_predict
    output = await app.blocks.process_api(
  File "C:\ai\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 982, in process_api
    result = await self.call_function(fn_index, inputs, iterator)
  File "C:\ai\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 824, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\ai\stable-diffusion-webui\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\ai\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "C:\ai\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "C:\ai\stable-diffusion-webui\modules\ui.py", line 799, in update_orig
    same_size = state is not None and state.size == image.size
AttributeError: 'dict' object has no attribute 'size'

It keep just looping in this error

**Comment by Dleeps** [comment]
Already fixed, it was a bug
