### ISSUE TITLE
im having this problem while installing stable diffusion

### ISSUE THREAD

**Issue by alisabbah92** [CompVis/stable-diffusion#526]
venv "C:\AI\stable-diffusion-webui\venv\Scripts\Python.exe"
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Commit hash: 44c46f0ed395967cd3830dd481a2db759fda5b3b
Traceback (most recent call last):
  File "C:\AI\stable-diffusion-webui\launch.py", line 294, in <module>
    prepare_enviroment()
  File "C:\AI\stable-diffusion-webui\launch.py", line 209, in prepare_enviroment
    run_python("import torch; assert torch.cuda.is_available(), 'Torch is not able to use GPU; add --skip-torch-cuda-test to COMMANDLINE_ARGS variable to disable this check'")
  File "C:\AI\stable-diffusion-webui\launch.py", line 73, in run_python
    return run(f'"{python}" -c "{code}"', desc, errdesc)
  File "C:\AI\stable-diffusion-webui\launch.py", line 49, in run
    raise RuntimeError(message)
RuntimeError: Error running command.
Command: "C:\AI\stable-diffusion-webui\venv\Scripts\python.exe" -c "import torch; assert torch.cuda.is_available(), 'Torch is not able to use GPU; add --skip-torch-cuda-test to COMMANDLINE_ARGS variable to disable this check'"
Error code: 1
stdout: <empty>
stderr: Traceback (most recent call last):
  File "<string>", line 1, in <module>
AssertionError: Torch is not able to use GPU; add --skip-torch-cuda-test to COMMANDLINE_ARGS variable to disable this check

**Comment by Alex-Buvin** [comment]
Hi, I'm having the same error now when installing, most likely due to the fact that we both have an AMD GPU.  I have managed to find a solution to this problem. 

You need to open the launch.py file in the Stable Diffusion folder and edit line 163. Add `--skip-torch-cuda-test` to the `commandline_args`. You should end up with `commandline_args = os.environ.get('COMMANDLINE_ARGS', "--skip-torch-cuda-test")`
