### ISSUE TITLE
Stable Diffusion 2.1 Install Error- can't get past the webui.bat install

### ISSUE THREAD

**Issue by FeuerPferd66** [CompVis/stable-diffusion#534]
I have been running into similar problems while installing 2.1
Everything up to running the WEBUI.BAT file seemed fine.
But once I run the batch file, I keep getting the below errors and am unsure how to solve it. My gut feeling tells me that it might be a PYTHON issue, but I had installed the recommended 3.10.6 version, but as you can see, it seems to be referring to 3.7.9. 
** any help would be greatly appreciated **

venv "C:\StableDiffusion\venv\Scripts\Python.exe"
Python 3.7.9 (tags/v3.7.9:13c94747c7, Aug 17 2020, 18:58:18) [MSC v.1900 64 bit (AMD64)]
Commit hash: 685f9631b56ff8bd43bce24ff5ce0f9a0e9af490
Installing requirements for Web UI
Traceback (most recent call last):
  File "launch.py", line 294, in <module>
    prepare_environment()
  File "launch.py", line 246, in prepare_environment
    run_pip(f"install -r {requirements_file}", "requirements for Web UI")
  File "launch.py", line 78, in run_pip
    return run(f'"{python}" -m pip {args} --prefer-binary{index_url_line}', desc=f"Installing {desc}", errdesc=f"Couldn't install {desc}")
  File "launch.py", line 49, in run
    raise RuntimeError(message)
RuntimeError: Couldn't install requirements for Web UI.
Command: "C:\StableDiffusion\venv\Scripts\python.exe" -m pip install -r requirements_versions.txt --prefer-binary
Error code: 1
stdout: Collecting transformers==4.19.2
  Using cached transformers-4.19.2-py3-none-any.whl (4.2 MB)
Collecting accelerate==0.12.0
  Using cached accelerate-0.12.0-py3-none-any.whl (143 kB)
Requirement already satisfied: basicsr==1.4.2 in c:\stablediffusion\venv\lib\site-packages (from -r requirements_versions.txt (line 3)) (1.4.2)
Collecting gfpgan==1.3.8
  Using cached gfpgan-1.3.8-py3-none-any.whl (52 kB)
Collecting gradio==3.9
  Using cached gradio-3.9-py3-none-any.whl (11.6 MB)

stderr: ERROR: Ignored the following versions that require a different python version: 1.22.0 Requires-Python >=3.8; 1.22.0rc1 Requires-Python >=3.8; 1.22.0rc2 Requires-Python >=3.8; 1.22.0rc3 Requires-Python >=3.8; 1.22.1 Requires-Python >=3.8; 1.22.2 Requires-Python >=3.8; 1.22.3 Requires-Python >=3.8; 1.22.4 Requires-Python >=3.8; 1.23.0 Requires-Python >=3.8; 1.23.0rc1 Requires-Python >=3.8; 1.23.0rc2 Requires-Python >=3.8; 1.23.0rc3 Requires-Python >=3.8; 1.23.1 Requires-Python >=3.8; 1.23.2 Requires-Python >=3.8; 1.23.3 Requires-Python >=3.8; 1.23.4 Requires-Python >=3.8; 1.23.5 Requires-Python >=3.8; 1.24.0rc1 Requires-Python >=3.8; 1.24.0rc2 Requires-Python >=3.8
ERROR: Could not find a version that satisfies the requirement numpy==1.23.3 (from versions: 1.3.0, 1.4.1, 1.5.0, 1.5.1, 1.6.0, 1.6.1, 1.6.2, 1.7.0, 1.7.1, 1.7.2, 1.8.0, 1.8.1, 1.8.2, 1.9.0, 1.9.1, 1.9.2, 1.9.3, 1.10.0.post2, 1.10.1, 1.10.2, 1.10.4, 1.11.0, 1.11.1, 1.11.2, 1.11.3, 1.12.0, 1.12.1, 1.13.0rc1, 1.13.0rc2, 1.13.0, 1.13.1, 1.13.3, 1.14.0rc1, 1.14.0, 1.14.1, 1.14.2, 1.14.3, 1.14.4, 1.14.5, 1.14.6, 1.15.0rc1, 1.15.0rc2, 1.15.0, 1.15.1, 1.15.2, 1.15.3, 1.15.4, 1.16.0rc1, 1.16.0rc2, 1.16.0, 1.16.1, 1.16.2, 1.16.3, 1.16.4, 1.16.5, 1.16.6, 1.17.0rc1, 1.17.0rc2, 1.17.0, 1.17.1, 1.17.2, 1.17.3, 1.17.4, 1.17.5, 1.18.0rc1, 1.18.0, 1.18.1, 1.18.2, 1.18.3, 1.18.4, 1.18.5, 1.19.0rc1, 1.19.0rc2, 1.19.0, 1.19.1, 1.19.2, 1.19.3, 1.19.4, 1.19.5, 1.20.0rc1, 1.20.0rc2, 1.20.0, 1.20.1, 1.20.2, 1.20.3, 1.21.0rc1, 1.21.0rc2, 1.21.0, 1.21.1, 1.21.2, 1.21.3, 1.21.4, 1.21.5, 1.21.6)
ERROR: No matching distribution found for numpy==1.23.3

Press any key to continue . . .

**Comment by AlexMBFlow** [comment]
Same!

**Comment by AlexMBFlow** [comment]
I closed the installation, reopened it. I did it several times

**Comment by WASasquatch** [comment]
Looks like you are not running the correct version of Python (3.10 I believe you need for WebUI), and you need to install Numpy `pip install numpy`
