### ISSUE TITLE
Stable diffusion automatic1111 error does not appear to have a file named preprocessor_config.json

### ISSUE THREAD

**Issue by Lastofthefirst** [CompVis/stable-diffusion#545]
I am usin the free collab, and trying to figure out how to embed some custom models (and so clearing, deleting my files from google drive, and restarting a few times).

After some attempts I tried to clear everything and just to a default run with the v2.1 512 files, however I keep hitting this error:

The similar issues/discussions didn't seem to match my situation. Any suggestions?

```

Converting to CKPT ...
The config attributes {'upcast_attention': True} were passed to UNet2DConditionModel, but are not expected and will be ignored. Please verify your config.json configuration file.
Traceback (most recent call last):
  File "/content/convertosdv2.py", line 1107, in <module>
    convert(args)
  File "/content/convertosdv2.py", line 1058, in convert
    pipe = StableDiffusionPipeline.from_pretrained(args.model_to_load, torch_dtype=load_dtype, tokenizer=None, safety_checker=None)
  File "/usr/local/lib/python3.8/dist-packages/diffusers/pipeline_utils.py", line 661, in from_pretrained
    loaded_sub_model = load_method(cached_folder, **loading_kwargs)
  File "/usr/local/lib/python3.8/dist-packages/transformers/feature_extraction_utils.py", line 306, in from_pretrained
    feature_extractor_dict, kwargs = cls.get_feature_extractor_dict(pretrained_model_name_or_path, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/transformers/feature_extraction_utils.py", line 402, in get_feature_extractor_dict
    resolved_feature_extractor_file = cached_file(
  File "/usr/local/lib/python3.8/dist-packages/transformers/utils/hub.py", line 380, in cached_file
    raise EnvironmentError(
OSError: /content/stable-diffusion-V2 does not appear to have a file named preprocessor_config.json. Checkout 'https://huggingface.co//content/stable-diffusion-V2/None' for available files.
Something went wrong, try again


```

**Comment by jenuk** [comment]
From the error-message I am assuming your question is about the [huggingface diffusers library](https://github.com/huggingface/diffusers/). Please be aware this is an independent codebase and we cannot provide any support for it. You may want to look into the [issues](https://github.com/huggingface/diffusers/issues?q=is%3Aissue) there, both closed and open to find out if other people have reported this problem before, or open a new issue if that is not the case.
