### ISSUE TITLE
Problem installing gfpgan

### ISSUE THREAD

**Issue by willjr08-pixel** [CompVis/stable-diffusion#548]
I tried installing gfpgan, but I got this error. It should be noted that I already used arguments to skip the CUDA install (I'm not sure if that's relevant). I'm using Python 10. Please help.

Installing gfpgan
Traceback (most recent call last):
  File "C:\Users\wgrah\Downloads\WebUIThing\launch.py", line 294, in <module>
    prepare_environment()
  File "C:\Users\wgrah\Downloads\WebUIThing\launch.py", line 212, in prepare_environment
    run_pip(f"install {gfpgan_package}", "gfpgan")
  File "C:\Users\wgrah\Downloads\WebUIThing\launch.py", line 78, in run_pip
    return run(f'"{python}" -m pip {args} --prefer-binary{index_url_line}', desc=f"Installing {desc}", errdesc=f"Couldn't install {desc}")
  File "C:\Users\wgrah\Downloads\WebUIThing\launch.py", line 49, in run
    raise RuntimeError(message)
RuntimeError: Couldn't install gfpgan.
Command: "C:\Users\wgrah\Downloads\WebUIThing\venv\Scripts\python.exe" -m pip install git+https://github.com/TencentARC/GFPGAN.git@8d2447a2d918f8eba5a4a01463fd48e45126a379 --prefer-binary
Error code: 1
stdout: Collecting git+https://github.com/TencentARC/GFPGAN.git@8d2447a2d918f8eba5a4a01463fd48e45126a379
  Cloning https://github.com/TencentARC/GFPGAN.git (to revision 8d2447a2d918f8eba5a4a01463fd48e45126a379) to c:\users\wgrah\appdata\local\temp\pip-req-build-knv7i04d
  Resolved https://github.com/TencentARC/GFPGAN.git to commit 8d2447a2d918f8eba5a4a01463fd48e45126a379
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'

stderr:   Running command git clone --filter=blob:none --quiet https://github.com/TencentARC/GFPGAN.git 'C:\Users\wgrah\AppData\Local\Temp\pip-req-build-knv7i04d'
  Running command git rev-parse -q --verify 'sha^8d2447a2d918f8eba5a4a01463fd48e45126a379'
  Running command git fetch -q https://github.com/TencentARC/GFPGAN.git 8d2447a2d918f8eba5a4a01463fd48e45126a379
  Running command git checkout -q 8d2447a2d918f8eba5a4a01463fd48e45126a379
  error: subprocess-exited-with-error

  python setup.py egg_info did not run successfully.
  exit code: 1

  [14 lines of output]
  Traceback (most recent call last):
    File "<string>", line 2, in <module>
    File "<pip-setuptools-caller>", line 14, in <module>
    File "C:\Users\wgrah\Downloads\WebUIThing\venv\lib\site-packages\setuptools\__init__.py", line 8, in <module>
      import _distutils_hack.override  # noqa: F401
    File "C:\Users\wgrah\Downloads\WebUIThing\venv\lib\site-packages\_distutils_hack\override.py", line 1, in <module>
      __import__('_distutils_hack').do_override()
    File "C:\Users\wgrah\Downloads\WebUIThing\venv\lib\site-packages\_distutils_hack\__init__.py", line 77, in do_override
      ensure_local_distutils()
    File "C:\Users\wgrah\Downloads\WebUIThing\venv\lib\site-packages\_distutils_hack\__init__.py", line 63, in ensure_local_distutils
      core = importlib.import_module('distutils.core')
    File "C:\Users\wgrah\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py", line 126, in import_module
      return _bootstrap._gcd_import(name[level:], package, level)
  ValueError: source code string cannot contain null bytes
  [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

Encountered error while generating package metadata.

See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by telnovas** [comment]
Hey! Did you manage to fix it?

**Comment by willjr08-pixel** [comment]
> Hey! Did you manage to fix it?

I did not; nothing I tried made it install.

**Comment by Rattaspi** [comment]
Same problem here

**Comment by jenuk** [comment]
From the error-message I am assuming your question is about the [stable diffusion webui by AUTOMATIC1111](https://github.com/AUTOMATIC1111/stable-diffusion-webui). Please be aware this is a third-party tool and we cannot provide any support for it. You may want to look into the [issues](https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues?q=is%3Aissue) there, both closed and open to find out if other people have reported this problem before, or open a new issue if that is not the case.
