### ISSUE TITLE
Cant install Stable Diffusion (RunTImeError: Can't install Torch. No module named pip)

### ISSUE THREAD

**Issue by ChaosDraku** [CompVis/stable-diffusion#561]
Installing torch and torchvision
Traceback (most recent call last):
  File "C:\StableDiffusion\stable-diffusion-webui\launch.py", line 294, in <module>
    prepare_environment()
  File "C:\StableDiffusion\stable-diffusion-webui\launch.py", line 206, in prepare_environment
    run(f'"{python}" -m {torch_command}', "Installing torch and torchvision", "Couldn't install torch")
  File "C:\StableDiffusion\stable-diffusion-webui\launch.py", line 49, in run
    raise RuntimeError(message)
RuntimeError: Couldn't install torch.
Command: "C:\StableDiffusion\stable-diffusion-webui\venv\Scripts\python.exe" -m pip install torch==1.12.1+cu113 torchvision==0.13.1+cu113 --extra-index-url https://download.pytorch.org/whl/cu113
Error code: 1
stdout: <empty>
stderr: C:\StableDiffusion\stable-diffusion-webui\venv\Scripts\python.exe: No module named pip
___________________________________________________________________________________________________________________________________
What happened? Why cant I install it? I even updated pip to the latest version, tried deleting the venv file but it came back to life
What the frick do I do?

**Comment by tschaerni** [comment]
As far as I know, torch needs a specific python version, try 3.10.6.

**Comment by ChaosDraku** [comment]
> As far as I know, torch needs a specific python version, try 3.10.6.

I already have 3.10.6 in it

**Comment by tschaerni** [comment]
> I already have 3.10.6 in it
Does it also get used? Or rather: is it selected as the default python executeable?
