### ISSUE TITLE
install failed

### ISSUE THREAD

**Issue by skytraveler** [CompVis/stable-diffusion#604]
When I execute:  conda env create -f environment.yaml

I got this problem 

Downloading and Extracting Packages
                                                                                
Preparing transaction: done                                                     
Verifying transaction: done
Executing transaction: done
Installing pip dependencies: \ Ran pip subprocess with arguments:
['/Users/lucas/miniconda3/envs/ldm/bin/python', '-m', 'pip', 'install', '-U', '-r', '/Users/lucas/Downloads/stable-diffusion/stable-diffusion-main/condaenv.e95j_k39.requirements.txt', '--exists-action=b']
Pip subprocess output:
Obtaining taming-transformers from git+https://github.com/CompVis/taming-transformers.git@master#egg=taming-transformers (from -r /Users/lucas/Downloads/stable-diffusion/stable-diffusion-main/condaenv.e95j_k39.requirements.txt (line 17))

Pip subprocess error:
ERROR: Exception:
Traceback (most recent call last):
  File "/Users/lucas/miniconda3/envs/ldm/lib/python3.8/site-packages/pip/_vendor/resolvelib/resolvers.py", line 171, in _merge_into_criterion
    crit = self.state.criteria[name]
KeyError: 'taming-transformers'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/lucas/miniconda3/envs/ldm/lib/python3.8/site-packages/pip/_internal/vcs/git.py", line 322, in get_remote_url
    found_remote = remotes[0]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/lucas/miniconda3/envs/ldm/lib/python3.8/site-packages/pip/_internal/cli/base_command.py", line 224, in _main
    status = self.run(options, args)
  File "/Users/lucas/miniconda3/envs/ldm/lib/python3.8/site-packages/pip/_internal/cli/req_command.py", line 180, in wrapper
    return func(self, options, args)
  File "/Users/lucas/miniconda3/envs/ldm/lib/python3.8/site-packages/pip/_internal/commands/install.py", line 320, in run
    requirement_set = resolver.resolve(
  File "/Users/lucas/miniconda3/envs/ldm/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 121, in resolve
    self._result = resolver.resolve(
  File "/Users/lucas/miniconda3/envs/ldm/lib/python3.8/site-packages/pip/_vendor/resolvelib/resolvers.py", line 445, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "/Users/lucas/miniconda3/envs/ldm/lib/python3.8/site-packages/pip/_vendor/resolvelib/resolvers.py", line 310, in resolve
    name, crit = self._merge_into_criterion(r, parent=None)
  File "/Users/lucas/miniconda3/envs/ldm/lib/python3.8/site-packages/pip/_vendor/resolvelib/resolvers.py", line 173, in _merge_into_criterion
    crit = Criterion.from_requirement(self._p, requirement, parent)
  File "/Users/lucas/miniconda3/envs/ldm/lib/python3.8/site-packages/pip/_vendor/resolvelib/resolvers.py", line 79, in from_requirement
    cands = build_iter_view(provider.find_matches([requirement]))
  File "/Users/lucas/miniconda3/envs/ldm/lib/python3.8/site-packages/pip/_vendor/resolvelib/structs.py", line 148, in build_iter_view
    matches = list(matches)
  File "/Users/lucas/miniconda3/envs/ldm/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 255, in <genexpr>
    if constraint.is_satisfied_by(c)
  File "/Users/lucas/miniconda3/envs/ldm/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/base.py", line 66, in is_satisfied_by
    return self.specifier.contains(candidate.version, prereleases=True)
  File "/Users/lucas/miniconda3/envs/ldm/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 194, in version
    self._version = self.dist.parsed_version
  File "/Users/lucas/miniconda3/envs/ldm/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 239, in dist
    self._prepare()
  File "/Users/lucas/miniconda3/envs/ldm/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 226, in _prepare
    dist = self._prepare_distribution()
  File "/Users/lucas/miniconda3/envs/ldm/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 346, in _prepare_distribution
    return self._factory.preparer.prepare_editable_requirement(self._ireq)
  File "/Users/lucas/miniconda3/envs/ldm/lib/python3.8/site-packages/pip/_internal/operations/prepare.py", line 573, in prepare_editable_requirement
    req.update_editable(self.download_dir is None)
  File "/Users/lucas/miniconda3/envs/ldm/lib/python3.8/site-packages/pip/_internal/req/req_install.py", line 655, in update_editable
    vcs_backend.obtain(self.source_dir, url=hidden_url)
  File "/Users/lucas/miniconda3/envs/ldm/lib/python3.8/site-packages/pip/_internal/vcs/versioncontrol.py", line 654, in obtain
    existing_url = self.get_remote_url(dest)
  File "/Users/lucas/miniconda3/envs/ldm/lib/python3.8/site-packages/pip/_internal/vcs/git.py", line 324, in get_remote_url
    raise RemoteNotFoundError
pip._internal.vcs.versioncontrol.RemoteNotFoundError

failed

CondaEnvException: Pip failed

more information:

(base) ➜  stable-diffusion-main conda --version 
conda 22.11.1

(base) ➜  stable-diffusion-main cat environment.yaml 
name: ldm
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.8.5
  - pip=20.3
  - cudatoolkit=9.0
  - pytorch=1.11.0
  - torchvision=0.12.0
  - numpy=1.19.2
  - pip:
    - albumentations==0.4.3
    - diffusers
    - opencv-python==4.1.2.30
    - pudb==2019.2
    - invisible-watermark
    - imageio==2.9.0
    - imageio-ffmpeg==0.4.2
    - pytorch-lightning==1.4.2
    - omegaconf==2.1.1
    - test-tube>=0.7.5
    - streamlit>=0.73.1
    - einops==0.3.0
    - torch-fidelity==0.3.0
    - transformers==4.19.2
    - torchmetrics==0.6.0
    - kornia==0.6
    - -e git+https://github.com/CompVis/taming-transformers.git@master#egg=taming-transformers
    - -e git+https://github.com/openai/CLIP.git@main#egg=clip
    - -e .

I think  someting wrong with
pip install -e git+https://github.com/CompVis/taming-transformers.git@master#egg=taming-transformers

because I got the same error
I am using the macbook intel chip. version:13.1 (22C65)

**Comment by liangbingzhao** [comment]
I think it is the taming-transformers repo too large; I download the zip of it, unzip and run the setup.py to install. Hope works for you.

**Comment by liangbingzhao** [comment]
And need to run:    `pip install -e .`     in the taming-transformers folder.

**Comment by berk-efe** [comment]
same issue
