### ISSUE TITLE
AttributeError: 'list' object has no attribute 'shape'

### ISSUE THREAD

**Issue by kako523** [CompVis/stable-diffusion#616]
When I run img2img.py, I get the following error, I don't know how to solve this problem.

> target t_enc is 40 steps
> data:   0%|                                                                                                                      | 0/1 [00:00<?, ?it/s]
> Sampling:   0%|                                                                                                                  | 0/1 [00:00<?, ?it/s]
> Traceback (most recent call last):
>   File "scripts/img2img.py", line 293, in <module>
>     main()
>   File "scripts/img2img.py", line 253, in main
>     uc = model.get_learned_conditioning(batch_size * [""])
>   File "/kako/1code/stable-diffusion-main/ldm/models/diffusion/ddpm.py", line 554, in get_learned_conditioning
>     c = self.cond_stage_model.encode(c)
>   File "/kako/1code/stable-diffusion-main/ldm/modules/encoders/modules.py", line 103, in encode
>     return self(text)
>   File "/home/ubuntu/anaconda3/envs/ldm/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
>     return forward_call(*input, **kwargs)
>   File "/kako/1code/stable-diffusion-main/ldm/modules/encoders/modules.py", line 98, in forward
>     z = self.transformer(tokens, return_embeddings=True)
>   File "/home/ubuntu/anaconda3/envs/ldm/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
>     return forward_call(*input, **kwargs)
>   File "/kako/1code/stable-diffusion-main/ldm/modules/x_transformer.py", line 609, in forward
>     b, n, device, num_mem = *x.shape, x.device, self.num_memory_tokens
> AttributeError: 'list' object has no attribute 'shape'

**Comment by mero20j1** [comment]
I have the same problem !
