### ISSUE TITLE
Issues on setting up sd

### ISSUE THREAD

**Issue by Chunq3** [CompVis/stable-diffusion#617]
Hello there I tried a few methods like getting python3.10, restart the whole thing by downloading zip file directly but it still dosen't work.
Appreciate it if there are some helps. Thank you so much!!!

Here's the log

Creating venv in directory D:\sd\stable-diffusion-webui-master\stable-diffusion-webui-master\venv using python "C:\Users\chun9\AppData\Local\Programs\Python\Python310\python.exe"
venv "D:\sd\stable-diffusion-webui-master\stable-diffusion-webui-master\venv\Scripts\Python.exe"
Python 3.10.0 (tags/v3.10.0:b494f59, Oct  4 2021, 19:00:18) [MSC v.1929 64 bit (AMD64)]
Commit hash: <none>
Installing torch and torchvision
Looking in indexes: https://pypi.org/simple, https://download.pytorch.org/whl/cu117
Collecting torch==1.13.1+cu117
  Using cached https://download.pytorch.org/whl/cu117/torch-1.13.1%2Bcu117-cp310-cp310-win_amd64.whl (2255.4 MB)
Collecting torchvision==0.14.1+cu117
  Using cached https://download.pytorch.org/whl/cu117/torchvision-0.14.1%2Bcu117-cp310-cp310-win_amd64.whl (4.8 MB)
Collecting typing-extensions
  Using cached typing_extensions-4.5.0-py3-none-any.whl (27 kB)
Collecting pillow!=8.3.*,>=5.3.0
  Using cached Pillow-9.4.0-cp310-cp310-win_amd64.whl (2.5 MB)
Collecting numpy
  Using cached numpy-1.24.2-cp310-cp310-win_amd64.whl (14.8 MB)
Collecting requests
  Using cached requests-2.28.2-py3-none-any.whl (62 kB)
Collecting idna<4,>=2.5
  Using cached idna-3.4-py3-none-any.whl (61 kB)
Collecting certifi>=2017.4.17
  Using cached certifi-2022.12.7-py3-none-any.whl (155 kB)
Collecting charset-normalizer<4,>=2
  Using cached charset_normalizer-3.0.1-cp310-cp310-win_amd64.whl (96 kB)
Collecting urllib3<1.27,>=1.21.1
  Using cached urllib3-1.26.14-py2.py3-none-any.whl (140 kB)
Installing collected packages: urllib3, typing-extensions, idna, charset-normalizer, certifi, torch, requests, pillow, numpy, torchvision
Successfully installed certifi-2022.12.7 charset-normalizer-3.0.1 idna-3.4 numpy-1.24.2 pillow-9.4.0 requests-2.28.2 torch-1.13.1+cu117 torchvision-0.14.1+cu117 typing-extensions-4.5.0 urllib3-1.26.14
WARNING: You are using pip version 21.2.3; however, version 23.0 is available.
You should consider upgrading via the 'D:\sd\stable-diffusion-webui-master\stable-diffusion-webui-master\venv\Scripts\python.exe -m pip install --upgrade pip' command.
Installing gfpgan
Installing clip
Installing open_clip
Installing requirements for CodeFormer
Installing requirements for Web UI
Launching Web UI with arguments:
No module 'xformers'. Proceeding without it.
Loading weights [dcd690123c] from D:\sd\stable-diffusion-webui-master\stable-diffusion-webui-master\models\Stable-diffusion\v2-1_768-ema-pruned.safetensors
loading stable diffusion model: ScannerError
Traceback (most recent call last):
  File "D:\sd\stable-diffusion-webui-master\stable-diffusion-webui-master\webui.py", line 111, in initialize
    modules.sd_models.load_model()
  File "D:\sd\stable-diffusion-webui-master\stable-diffusion-webui-master\modules\sd_models.py", line 384, in load_model
    sd_config = OmegaConf.load(checkpoint_config)
  File "D:\sd\stable-diffusion-webui-master\stable-diffusion-webui-master\venv\lib\site-packages\omegaconf\omegaconf.py", line 188, in load
    obj = yaml.load(f, Loader=get_yaml_loader())
  File "D:\sd\stable-diffusion-webui-master\stable-diffusion-webui-master\venv\lib\site-packages\yaml\__init__.py", line 81, in load
    return loader.get_single_data()
  File "D:\sd\stable-diffusion-webui-master\stable-diffusion-webui-master\venv\lib\site-packages\yaml\constructor.py", line 49, in get_single_data
    node = self.get_single_node()
  File "D:\sd\stable-diffusion-webui-master\stable-diffusion-webui-master\venv\lib\site-packages\yaml\composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "D:\sd\stable-diffusion-webui-master\stable-diffusion-webui-master\venv\lib\site-packages\yaml\composer.py", line 58, in compose_document
    self.get_event()
  File "D:\sd\stable-diffusion-webui-master\stable-diffusion-webui-master\venv\lib\site-packages\yaml\parser.py", line 118, in get_event
    self.current_event = self.state()
  File "D:\sd\stable-diffusion-webui-master\stable-diffusion-webui-master\venv\lib\site-packages\yaml\parser.py", line 193, in parse_document_end
    token = self.peek_token()
  File "D:\sd\stable-diffusion-webui-master\stable-diffusion-webui-master\venv\lib\site-packages\yaml\scanner.py", line 129, in peek_token
    self.fetch_more_tokens()
  File "D:\sd\stable-diffusion-webui-master\stable-diffusion-webui-master\venv\lib\site-packages\yaml\scanner.py", line 258, in fetch_more_tokens
    raise ScannerError("while scanning for the next token", None,
yaml.scanner.ScannerError: while scanning for the next token
found character '\t' that cannot start any token
  in "D:\sd\stable-diffusion-webui-master\stable-diffusion-webui-master\models\Stable-diffusion\v2-1_768-ema-pruned.yaml", line 3, column 1

Stable diffusion model failed to load, exiting
Press any key to continue . . .

**Comment by AlbertShown** [comment]
I can't find `stable-diffusion-webui-master` repo. But only `stable-diffusion-master`.

**Comment by jenuk** [comment]
From the error-message I am assuming your question is about the [stable diffusion webui by AUTOMATIC1111](https://github.com/AUTOMATIC1111/stable-diffusion-webui). Please be aware this is a third-party tool and we cannot provide any support for it. You may want to look into the [issues](https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues?q=is%3Aissue) there, both closed and open to find out if other people have reported this problem before, or open a new issue if that is not the case.
