### ISSUE TITLE
Please default to CPU-only PyTorch if no suitable GPU is detected.

### ISSUE THREAD

**Issue by fragmentshader2022** [CompVis/stable-diffusion#62]
PyTorch is defaulting to NVIDIA GPU, but it would be good to fall back to CPU-only if no suitable GPU is found. This would quickly provide support for unsupported GPU’s such as AMD while that support is being implemented. And for me and all my fellow devs who have no GPU and want to run locally.

**Comment by HenkPoley** [comment]
See: #56

**Comment by fragmentshader2022** [comment]
@HenkPoley Thanks!

**Comment by MojoJojo43** [comment]
> @HenkPoley Thanks!

Hi, I am pretty new but did you figure out how to get it to run with CPU only?

**Comment by MojoJojo43** [comment]
> right here https://huggingface.co/spaces/stabilityai/stable-diffusion

Hi, yeah that's a really great option albeit a limited one. Can't control the size of the images and also can't use any adult terms because it is censored.

**Comment by breadbrowser** [comment]
> > right here https://huggingface.co/spaces/stabilityai/stable-diffusion
> 
> Hi, yeah that's a really great option albeit a limited one. Can't control the size of the images and also can't use any adult terms because it is censored.

http://beta.dreamstudio.ai/

**Comment by MojoJojo43** [comment]
> > > right here https://huggingface.co/spaces/stabilityai/stable-diffusion
> > 
> > 
> > Hi, yeah that's a really great option albeit a limited one. Can't control the size of the images and also can't use any adult terms because it is censored.
> 
> http://beta.dreamstudio.ai/

and that one is paid unless you want to keep switching IP's and creating accounts and still censors your prompts.

**Comment by patrickvonplaten** [comment]
With diffusers it's quite easy to run it on CPU only:

```python
from diffusers import StableDiffusionPipeline

pipe = StableDiffusionPipeline.from_pretrained("CompVis/stable-diffusion-v1-4")

# remove VAE encoder as it's not needed
del pipe.vae.encoder

prompt = "a photo of an astronaut riding a horse on mars"
image = pipe(prompt)["sample"][0] 
```

**Comment by breadbrowser** [comment]
> > > > right here https://huggingface.co/spaces/stabilityai/stable-diffusion
> > > 
> > > 
> > > Hi, yeah that's a really great option albeit a limited one. Can't control the size of the images and also can't use any adult terms because it is censored.
> > 
> > 
> > http://beta.dreamstudio.ai/
> 
> and that one is paid unless you want to keep switching IP's and creating accounts and still censors your prompts.

wrong just use temp mail

**Comment by warior456** [comment]
> With diffusers it's quite easy to run it on CPU only:
> 
> ```python
> # !pip install diffusers
> from diffusers import StableDiffusionPipeline
> 
> pipe = StableDiffusionPipeline.from_pretrained("CompVis/stable-diffusion-v1-4")
> 
> # remove VAE encoder as it's not needed
> del pipe.vae.encoder
> 
> prompt = "a photo of an astronaut riding a horse on mars"
> image = pipe(prompt)["sample"][0] 
> ```

where do i put this? @patrickvonplaten

**Comment by Sivll** [comment]
Sustain! 
Where to put?

**Comment by Sivll** [comment]
damn... so clow with CPU.. is it safe? it consumes >> 100% of cpu amount. I have quad core Intel i5. Hope it means 25% usage per core))
>>> del pipe.vae.encoder
>>> prompt = "a photo of an astronaut riding a horse on mars"
>>> image = pipe(prompt)["sample"][0]
  8%|██████▌                                                                           | 4/50 [02:09<22:20, 29.13s/it]

And I've got such message:
Cannot initialize model with low cpu memory usage because `accelerate` was not found in the environment. Defaulting to `low_cpu_mem_usage=False`. It is strongly recommended to install `accelerate` for faster and less memory-intense model loading. You can do so with: 
```
pip install accelerate

Can I install it without exit from interpreter >>>???


And where generated image wil be saved????

**Comment by Sivll** [comment]
after process finished an error appears 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/semkovigor/sd/MetalDiffusion/venv/lib/python3.11/site-packages/diffusers/utils/outputs.py", line 88, in __getitem__
    return inner_dict[k]
           ~~~~~~~~~~^^^
KeyError: 'sample'

what should I do to fix it?
