### ISSUE TITLE
ImportError: cannot import name 'SAFE_WEIGHTS_NAME' from 'transformers.utils'

### ISSUE THREAD

**Issue by Duality142857** [CompVis/stable-diffusion#621]
I did exactly following the guidelines, but when I run the script, following errors occur, any idea how to fix it? 
script: 
python scripts/txt2img.py --prompt "a photograph of an astronaut riding a horse" --plms 

error msg: 
Traceback (most recent call last):
  File "scripts/txt2img.py", line 22, in <module>
    from diffusers.pipelines.stable_diffusion.safety_checker import StableDiffusionSafetyChecker
  File "/home/liberttyy/anaconda3/envs/ldm/lib/python3.8/site-packages/diffusers/__init__.py", line 27, in <module>
    from .pipelines import OnnxRuntimeModel
  File "/home/liberttyy/anaconda3/envs/ldm/lib/python3.8/site-packages/diffusers/pipelines/__init__.py", line 18, in <module>
    from .dance_diffusion import DanceDiffusionPipeline
  File "/home/liberttyy/anaconda3/envs/ldm/lib/python3.8/site-packages/diffusers/pipelines/dance_diffusion/__init__.py", line 1, in <module>
    from .pipeline_dance_diffusion import DanceDiffusionPipeline
  File "/home/liberttyy/anaconda3/envs/ldm/lib/python3.8/site-packages/diffusers/pipelines/dance_diffusion/pipeline_dance_diffusion.py", line 21, in <module>
    from ..pipeline_utils import AudioPipelineOutput, DiffusionPipeline
  File "/home/liberttyy/anaconda3/envs/ldm/lib/python3.8/site-packages/diffusers/pipelines/pipeline_utils.py", line 63, in <module>
    from transformers.utils import SAFE_WEIGHTS_NAME as TRANSFORMERS_SAFE_WEIGHTS_NAME
ImportError: cannot import name 'SAFE_WEIGHTS_NAME' from 'transformers.utils' (/home/liberttyy/anaconda3/envs/ldm/lib/python3.8/site-packages/transformers/utils/__init__.py)

**Comment by kadaliao** [comment]
> 

same here

**Comment by kght6123** [comment]
Me too.

**Comment by ipfedor** [comment]
it helped: pip install diffusers==0.12.1

**Comment by xws117** [comment]
> it helped: pip install diffusers==0.12.1

cool

**Comment by arnaudlamy** [comment]
same here (using miniconda)

**Comment by Bingordinary** [comment]
> it helped: pip install diffusers==0.12.1

it work！ Thank you！

**Comment by MikoSamey** [comment]
it helped : pip install transformers
and the version is 4.26.1
