### ISSUE TITLE
WebUI Error suddenly occured: "elem_id", Stabele Diffusion stopps working

### ISSUE THREAD

**Issue by spring-phul** [CompVis/stable-diffusion#637]
I use a automated updating version. A few days ago I installed the extensions dreambooth and controlnet. No issues so far. Yesterday after starting the webUI via the normal bat, the following errors are shown and stable diffusion doesn't work anymore. What can I do, what did I maybe wrong?

```
Launching Web UI with arguments:
No module 'xformers'. Proceeding without it.
SD-Webui API layer loaded
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Loading weights [81761151] from C:\GrafikAI\stable-diffusion-webui\models\Stable-diffusion\models.ckpt
Loading VAE weights from: C:\GrafikAI\stable-diffusion-webui\models\Stable-diffusion\Anything-V3.0.vae.pt
Applying cross attention optimization (Doggettx).
Model loaded.
Textual inversion embeddings loaded(0):
Error calling: C:\GrafikAI\stable-diffusion-webui\extensions\stable-diffusion-webui\scripts\prompt_matrix.py/ui
Traceback (most recent call last):
  File "C:\GrafikAI\stable-diffusion-webui\modules\scripts.py", line 212, in wrap_call
    res = func(*args, **kwargs)
  File "C:\GrafikAI\stable-diffusion-webui\extensions\stable-diffusion-webui\scripts\prompt_matrix.py", line 51, in ui
    put_at_start = gr.Checkbox(label='Put variable parts at start of prompt', value=False, elem_id=self.elem_id("put_at_start"))
AttributeError: 'Script' object has no attribute 'elem_id'

Error calling: C:\GrafikAI\stable-diffusion-webui\extensions\stable-diffusion-webui\scripts\prompts_from_file.py/ui
Traceback (most recent call last):
  File "C:\GrafikAI\stable-diffusion-webui\modules\scripts.py", line 212, in wrap_call
    res = func(*args, **kwargs)
  File "C:\GrafikAI\stable-diffusion-webui\extensions\stable-diffusion-webui\scripts\prompts_from_file.py", line 115, in ui
    checkbox_iterate = gr.Checkbox(label="Iterate seed every line", value=False, elem_id=self.elem_id("checkbox_iterate"))
AttributeError: 'Script' object has no attribute 'elem_id'

Error calling: C:\GrafikAI\stable-diffusion-webui\extensions\stable-diffusion-webui\scripts\xyz_grid.py/ui
Traceback (most recent call last):
  File "C:\GrafikAI\stable-diffusion-webui\modules\scripts.py", line 212, in wrap_call
    res = func(*args, **kwargs)
  File "C:\GrafikAI\stable-diffusion-webui\extensions\stable-diffusion-webui\scripts\xyz_grid.py", line 345, in ui
    x_type = gr.Dropdown(label="X type", choices=[x.label for x in self.current_axis_options], value=self.current_axis_options[1].label, type="index", elem_id=self.elem_id("x_type"))
AttributeError: 'Script' object has no attribute 'elem_id'

Error calling: C:\GrafikAI\stable-diffusion-webui\extensions\stable-diffusion-webui\scripts\img2imgalt.py/ui
Traceback (most recent call last):
  File "C:\GrafikAI\stable-diffusion-webui\modules\scripts.py", line 212, in wrap_call
    res = func(*args, **kwargs)
  File "C:\GrafikAI\stable-diffusion-webui\extensions\stable-diffusion-webui\scripts\img2imgalt.py", line 133, in ui
    override_sampler = gr.Checkbox(label="Override `Sampling method` to Euler?(this method is built for it)", value=True, elem_id=self.elem_id("override_sampler"))
AttributeError: 'Script' object has no attribute 'elem_id'

Error calling: C:\GrafikAI\stable-diffusion-webui\extensions\stable-diffusion-webui\scripts\loopback.py/ui
Traceback (most recent call last):
  File "C:\GrafikAI\stable-diffusion-webui\modules\scripts.py", line 212, in wrap_call
    res = func(*args, **kwargs)
  File "C:\GrafikAI\stable-diffusion-webui\extensions\stable-diffusion-webui\scripts\loopback.py", line 22, in ui
    loops = gr.Slider(minimum=1, maximum=32, step=1, label='Loops', value=4, elem_id=self.elem_id("loops"))
AttributeError: 'Script' object has no attribute 'elem_id'

Error calling: C:\GrafikAI\stable-diffusion-webui\extensions\stable-diffusion-webui\scripts\outpainting_mk_2.py/ui
Traceback (most recent call last):
  File "C:\GrafikAI\stable-diffusion-webui\modules\scripts.py", line 212, in wrap_call
    res = func(*args, **kwargs)
  File "C:\GrafikAI\stable-diffusion-webui\extensions\stable-diffusion-webui\scripts\outpainting_mk_2.py", line 134, in ui
    pixels = gr.Slider(label="Pixels to expand", minimum=8, maximum=256, step=8, value=128, elem_id=self.elem_id("pixels"))
AttributeError: 'Script' object has no attribute 'elem_id'

Error calling: C:\GrafikAI\stable-diffusion-webui\extensions\stable-diffusion-webui\scripts\poor_mans_outpainting.py/ui
Traceback (most recent call last):
  File "C:\GrafikAI\stable-diffusion-webui\modules\scripts.py", line 212, in wrap_call
    res = func(*args, **kwargs)
  File "C:\GrafikAI\stable-diffusion-webui\extensions\stable-diffusion-webui\scripts\poor_mans_outpainting.py", line 23, in ui
    pixels = gr.Slider(label="Pixels to expand", minimum=8, maximum=256, step=8, value=128, elem_id=self.elem_id("pixels"))
AttributeError: 'Script' object has no attribute 'elem_id'

Error calling: C:\GrafikAI\stable-diffusion-webui\extensions\stable-diffusion-webui\scripts\prompt_matrix.py/ui
Traceback (most recent call last):
  File "C:\GrafikAI\stable-diffusion-webui\modules\scripts.py", line 212, in wrap_call
    res = func(*args, **kwargs)
  File "C:\GrafikAI\stable-diffusion-webui\extensions\stable-diffusion-webui\scripts\prompt_matrix.py", line 51, in ui
    put_at_start = gr.Checkbox(label='Put variable parts at start of prompt', value=False, elem_id=self.elem_id("put_at_start"))
AttributeError: 'Script' object has no attribute 'elem_id'

Error calling: C:\GrafikAI\stable-diffusion-webui\extensions\stable-diffusion-webui\scripts\prompts_from_file.py/ui
Traceback (most recent call last):
  File "C:\GrafikAI\stable-diffusion-webui\modules\scripts.py", line 212, in wrap_call
    res = func(*args, **kwargs)
  File "C:\GrafikAI\stable-diffusion-webui\extensions\stable-diffusion-webui\scripts\prompts_from_file.py", line 115, in ui
    checkbox_iterate = gr.Checkbox(label="Iterate seed every line", value=False, elem_id=self.elem_id("checkbox_iterate"))
AttributeError: 'Script' object has no attribute 'elem_id'

Error calling: C:\GrafikAI\stable-diffusion-webui\extensions\stable-diffusion-webui\scripts\sd_upscale.py/ui
Traceback (most recent call last):
  File "C:\GrafikAI\stable-diffusion-webui\modules\scripts.py", line 212, in wrap_call
    res = func(*args, **kwargs)
  File "C:\GrafikAI\stable-diffusion-webui\extensions\stable-diffusion-webui\scripts\sd_upscale.py", line 21, in ui
    overlap = gr.Slider(minimum=0, maximum=256, step=16, label='Tile overlap', value=64, elem_id=self.elem_id("overlap"))
AttributeError: 'Script' object has no attribute 'elem_id'

Error calling: C:\GrafikAI\stable-diffusion-webui\extensions\stable-diffusion-webui\scripts\xyz_grid.py/ui
Traceback (most recent call last):
  File "C:\GrafikAI\stable-diffusion-webui\modules\scripts.py", line 212, in wrap_call
    res = func(*args, **kwargs)
  File "C:\GrafikAI\stable-diffusion-webui\extensions\stable-diffusion-webui\scripts\xyz_grid.py", line 345, in ui
    x_type = gr.Dropdown(label="X type", choices=[x.label for x in self.current_axis_options], value=self.current_axis_options[1].label, type="index", elem_id=self.elem_id("x_type"))
AttributeError: 'Script' object has no attribute 'elem_id'
```

**Comment by jenuk** [comment]
From the error-message I am assuming your question is about the [stable diffusion webui by AUTOMATIC1111](https://github.com/AUTOMATIC1111/stable-diffusion-webui). Please be aware this is a third-party tool and we cannot provide any support for it. You may want to look into the [issues](https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues?q=is%3Aissue) there, both closed and open to find out if other people have reported this problem before, or open a new issue if that is not the case.
