### ISSUE TITLE
RuntimeError: Couldn't install open_clip.

### ISSUE THREAD

**Issue by Cauchy929** [CompVis/stable-diffusion#661]
Please help if you can :)
I'm trying to install Stable Diffusion on Macbook with Intel Silicon.
Here's cmd script:
```
(base) localhost:stable-diffusion-webui apple$ ./webui.sh

################################################################
Install script for stable-diffusion + Web UI
Tested on Debian 11 (Bullseye)
################################################################

################################################################
Running on apple user
################################################################

################################################################
Repo already cloned, using it as install directory
################################################################

################################################################
Create and activate python venv
################################################################

################################################################
Launching launch.py...
################################################################
Python 3.10.10 (main, Mar 11 2023, 19:24:07) [Clang 14.0.0 (clang-1400.0.29.202)]
Commit hash: 0cc0ee1bcb4c24a8c9715f66cede06601bfc00c8
Installing open_clip
Traceback (most recent call last):
  File "/Users/apple/stable-diffusion-webui/launch.py", line 360, in <module>
    prepare_environment()
  File "/Users/apple/stable-diffusion-webui/launch.py", line 281, in prepare_environment
    run_pip(f"install {openclip_package}", "open_clip")
  File "/Users/apple/stable-diffusion-webui/launch.py", line 137, in run_pip
    return run(f'"{python}" -m pip {args} --prefer-binary{index_url_line}', desc=f"Installing {desc}", errdesc=f"Couldn't install {desc}")
  File "/Users/apple/stable-diffusion-webui/launch.py", line 105, in run
    raise RuntimeError(message)
RuntimeError: Couldn't install open_clip.
Command: "/Users/apple/stable-diffusion-webui/venv/bin/python3.10" -m pip install git+https://github.com/mlfoundations/open_clip.git@bb6e834e9c70d9c27d0dc3ecedeebeaeb1ffad6b --prefer-binary
Error code: 1
stdout: Collecting git+https://github.com/mlfoundations/open_clip.git@bb6e834e9c70d9c27d0dc3ecedeebeaeb1ffad6b
  Cloning https://github.com/mlfoundations/open_clip.git (to revision bb6e834e9c70d9c27d0dc3ecedeebeaeb1ffad6b) to /private/var/folders/0m/8wpr5pj129z3xs0vsrrf5fqh0000gn/T/pip-req-build-p8lgsig_

stderr:   Running command git clone --filter=blob:none --quiet https://github.com/mlfoundations/open_clip.git /private/var/folders/0m/8wpr5pj129z3xs0vsrrf5fqh0000gn/T/pip-req-build-p8lgsig_
  致命错误：无法访问 'https://github.com/mlfoundations/open_clip.git/'：LibreSSL SSL_read: error:02FFF03C:system library:func(4095):Operation timed out, errno 60
  error: subprocess-exited-with-error
  
  × git clone --filter=blob:none --quiet https://github.com/mlfoundations/open_clip.git /private/var/folders/0m/8wpr5pj129z3xs0vsrrf5fqh0000gn/T/pip-req-build-p8lgsig_ did not run successfully.
  │ exit code: 128
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× git clone --filter=blob:none --quiet https://github.com/mlfoundations/open_clip.git /private/var/folders/0m/8wpr5pj129z3xs0vsrrf5fqh0000gn/T/pip-req-build-p8lgsig_ did not run successfully.
│ exit code: 128
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

[notice] A new release of pip available: 22.3.1 -> 23.0.1
[notice] To update, run: pip install --upgrade pip
```

Ex. I met a similar error on the procedure of  ```installing gfpgan``` and I solved that by running ```pip install gfpgan``` individually. So I tried to solve this problem by running ```pip install open_clip_torch``` but that doesn't work :(

**Comment by Sealandsky** [comment]
问题解决了吗？

**Comment by KSroido** [comment]
> 问题解决了吗？
@Sealandsky 

due to Chinese GFW network issue. To solve this, use route proxy or TUN mode proxy

**Comment by jenuk** [comment]
From the error-message I am assuming your question is about the [stable diffusion webui by AUTOMATIC1111](https://github.com/AUTOMATIC1111/stable-diffusion-webui). Please be aware this is a third-party tool and we cannot provide any support for it. You may want to look into the [issues](https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues?q=is%3Aissue) there, both closed and open to find out if other people have reported this problem before, or open a new issue if that is not the case.
