### ISSUE TITLE
Installation error on executing webui-user.bat

### ISSUE THREAD

**Issue by fpradom** [CompVis/stable-diffusion#695]
I get following error during installation 

venv "C:\Users\f_prado\stable-diffusion-webui\venv\Scripts\Python.exe"
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Commit hash: 22bcc7be428c94e9408f589966c2040187245d81
Traceback (most recent call last):
  File "C:\Users\f_prado\stable-diffusion-webui\launch.py", line 355, in <module>
    prepare_environment()
  File "C:\Users\f_prado\stable-diffusion-webui\launch.py", line 260, in prepare_environment
    run_python("import torch; assert torch.cuda.is_available(), 'Torch is not able to use GPU; add --skip-torch-cuda-test to COMMANDLINE_ARGS variable to disable this check'")
  File "C:\Users\f_prado\stable-diffusion-webui\launch.py", line 121, in run_python
    return run(f'"{python}" -c "{code}"', desc, errdesc)
  File "C:\Users\f_prado\stable-diffusion-webui\launch.py", line 97, in run
    raise RuntimeError(message)
RuntimeError: Error running command.
Command: "C:\Users\f_prado\stable-diffusion-webui\venv\Scripts\python.exe" -c "import torch; assert torch.cuda.is_available(), 'Torch is not able to use GPU; add --skip-torch-cuda-test to COMMANDLINE_ARGS variable to disable this check'"
Error code: 1
stdout: <empty>
stderr: Traceback (most recent call last):
  File "<string>", line 1, in <module>
AssertionError: Torch is not able to use GPU; add --skip-torch-cuda-test to COMMANDLINE_ARGS variable to disable this check

Presione una tecla para continuar . . .

where must i change the COMMANDLINE_ARGS to resolve the problem?

**Comment by NolanYangWithEmma** [comment]
Hi I stuck at this point as well. ONLY differerce is I had this cmd window poped up BUT vanised in less than 1 sec. I didnt even have these error msgs. I checked online tutorials about inserting python 3.10.6 file path into .bat file. But it didn`t work. Can someone help me on this issue? Thanks a lot.

**Comment by fpradom** [comment]
I have resolved the problem after searching in other forum and I have obtin following indication.
If you run stable-diffusion on windows as me, edit  webui-user.bat in the stable-diffusion-webui folder and add configure the command line as follow: **set COMMANDLINE_ARGS= --lowvram --precision full --no-half --skip-torch-cuda-test**.
This solved the problem for me. Good luck
