### ISSUE TITLE
pytorch_lightning fails when running txt2img

### ISSUE THREAD

**Issue by ClaireCJS** [CompVis/stable-diffusion#714]
I kept getting this error:

```
(ldm) c:\ProgramData\anaconda3\envs\ldm\stable-diffusion>python scripts\txt2img.py  --prompt "a dead bird" --ckpt c:\checkpoints\768-v-ema.ckpt
Global seed set to 42
Loading model from c:\checkpoints\768-v-ema.ckpt
Global Step: 140000
Traceback (most recent call last):
  File "scripts\txt2img.py", line 352, in <module>
    main()
  File "scripts\txt2img.py", line 246, in main
    model = load_model_from_config(config, f"{opt.ckpt}")
  File "scripts\txt2img.py", line 55, in load_model_from_config
    model = instantiate_from_config(config.model)
  File "c:\programdata\anaconda3\envs\ldm\stable-diffusion\ldm\util.py", line 85, in instantiate_from_config
    return get_obj_from_str(config["target"])(**config.get("params", dict()))
  File "c:\programdata\anaconda3\envs\ldm\stable-diffusion\ldm\util.py", line 93, in get_obj_from_str
    return getattr(importlib.import_module(module, package=None), cls)
  File "C:\ProgramData\anaconda3\envs\ldm\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "c:\programdata\anaconda3\envs\ldm\stable-diffusion\ldm\models\diffusion\ddpm.py", line 19, in <module>
    from pytorch_lightning.utilities.distributed import rank_zero_only
ModuleNotFoundError: No module named 'pytorch_lightning.utilities.distributed'

```

It turns out to be something in the way pytorch changed -- i posted a solution in the comment below this one

**Comment by ClaireCJS** [comment]
Someone else found a fix so i'm pasting it here. 

File: stable-diffusion\ldm\models\diffusion\DDPM.py
Line: 19ish

change:

`from pytorch_lightning.utilities.distributed import rank_zero_only_`

to:

`from pytorch_lightning.utilities.rank_zero import rank_zero_only`


This will fix your code for me, but maybe break it for others who aren't using the newest pytorch.
