### ISSUE TITLE
Stable Diffiusion not working

### ISSUE THREAD

**Issue by EridalEnn** [CompVis/stable-diffusion#719]
Im not a coder, pls help. I wasted all day today trying to install this. Every time I try to change something, I get a problem. I uninstalled and reinstalled everything and it shows again:

[notice] A new release of pip available: 22.2.2 -> 23.1.2
[notice] To update, run: C:\Dysk D;\Programy\Stable Diffiusion\stable-diffusion-webui\venv\Scripts\python.exe -m pip install --upgrade pip
Traceback (most recent call last):
  File "C:\Dysk D;\Programy\Stable Diffiusion\stable-diffusion-webui\launch.py", line 352, in <module>
    prepare_environment()
  File "C:\Dysk D;\Programy\Stable Diffiusion\stable-diffusion-webui\launch.py", line 257, in prepare_environment
    run_python("import torch; assert torch.cuda.is_available(), 'Torch is not able to use GPU; add --skip-torch-cuda-test to COMMANDLINE_ARGS variable to disable this check'")
  File "C:\Dysk D;\Programy\Stable Diffiusion\stable-diffusion-webui\launch.py", line 120, in run_python
    return run(f'"{python}" -c "{code}"', desc, errdesc)
  File "C:\Dysk D;\Programy\Stable Diffiusion\stable-diffusion-webui\launch.py", line 96, in run
    raise RuntimeError(message)
RuntimeError: Error running command.
Command: "C:\Dysk D;\Programy\Stable Diffiusion\stable-diffusion-webui\venv\Scripts\python.exe" -c "import torch; assert torch.cuda.is_available(), 'Torch is not able to use GPU; add --skip-torch-cuda-test to COMMANDLINE_ARGS variable to disable this check'"
Error code: 1
stdout: <empty>
stderr: Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Dysk D;\Programy\Stable Diffiusion\stable-diffusion-webui\venv\lib\site-packages\torch\__init__.py", line 133, in <module>
    raise err
OSError: [WinError 126] The specified module could not be found. Error loading "C:\Dysk D;\Programy\Stable Diffiusion\stable-diffusion-webui\venv\lib\site-packages\torch\lib\cudnn_adv_infer64_8.dll" or one of its dependencies.

**Comment by zyc-bit** [comment]
Hi there, it looks like you have deployed a very well-known forked project of this repository called 'stable diffusion webui', instead of this repository itself. You can inquire about it at this repository link：https://github.com/AUTOMATIC1111/stable-diffusion-webui
