### ISSUE TITLE
ImportError: cannot import name 'SAFE_WEIGHTS_NAME' from 'transformers.utils'

### ISSUE THREAD

**Issue by 0546trigger** [CompVis/stable-diffusion#742]
when I downloaded the v1.4 model and tried to generate graph from text I met following error: 

python scripts/txt2img.py --prompt "a photograph of an astronaut riding a horse" --plms 
Traceback (most recent call last):
  File "scripts/txt2img.py", line 22, in <module>
    from diffusers.pipelines.stable_diffusion.safety_checker import StableDiffusionSafetyChecker
  File "/home/ubuntu/anaconda3/envs/ldm/lib/python3.8/site-packages/diffusers/__init__.py", line 28, in <module>
    from .pipelines import OnnxRuntimeModel
  File "/home/ubuntu/anaconda3/envs/ldm/lib/python3.8/site-packages/diffusers/pipelines/__init__.py", line 19, in <module>
    from .dance_diffusion import DanceDiffusionPipeline
  File "/home/ubuntu/anaconda3/envs/ldm/lib/python3.8/site-packages/diffusers/pipelines/dance_diffusion/__init__.py", line 1, in <module>
    from .pipeline_dance_diffusion import DanceDiffusionPipeline
  File "/home/ubuntu/anaconda3/envs/ldm/lib/python3.8/site-packages/diffusers/pipelines/dance_diffusion/pipeline_dance_diffusion.py", line 21, in <module>
    from ..pipeline_utils import AudioPipelineOutput, DiffusionPipeline
  File "/home/ubuntu/anaconda3/envs/ldm/lib/python3.8/site-packages/diffusers/pipelines/pipeline_utils.py", line 66, in <module>
    from transformers.utils import SAFE_WEIGHTS_NAME as TRANSFORMERS_SAFE_WEIGHTS_NAME
ImportError: cannot import name 'SAFE_WEIGHTS_NAME' from 'transformers.utils' (/home/ubuntu/anaconda3/envs/ldm/lib/python3.8/site-packages/transformers/utils/__init__.py)

how can i fix it?

**Comment by houpanpan** [comment]
i meet the same error

**Comment by houpanpan** [comment]
hi~, just try it !!
pip install diffusers==0.12.1

**Comment by Vprashant** [comment]
Getting Same error , resolved using --pip install diffusers==0.12.1

**Comment by darrinh** [comment]
pip install diffusers==0.12.1 worked for me as well.

**Comment by Getiem** [comment]
pip install transformers --upgrade
