### ISSUE TITLE
_pickle.UnpicklingError: invalid load key, 'm'.

### ISSUE THREAD

**Issue by sussyboiiii** [CompVis/stable-diffusion#759]
Hello, 
Yes I have seen that an issue on this error has been made already, but I'am logged into huggingface and I still get the same error.

`(ai) user@MBP-from-user stablediffusion % python scripts/txt2img.py --prompt "a professional photograph of an astronaut riding a horse" --ckpt <~/ai/stablediffusion/models/v2-1_768-ema-pruned.ckpt> --config configs/stable-diffusion/v2-inference-v.yaml --H 768 --W 768   

Global seed set to 42
Traceback (most recent call last):
  File "/Users/user/ai/stablediffusion/scripts/txt2img.py", line 388, in <module>
    main(opt)
  File "/Users/user/ai/stablediffusion/scripts/txt2img.py", line 219, in main
    model = load_model_from_config(config, f"{opt.ckpt}", device)
  File "/Users/user/ai/stablediffusion/scripts/txt2img.py", line 30, in load_model_from_config
    pl_sd = torch.load(ckpt, map_location="cpu")
  File "/Library/miniconda3/envs/ai/lib/python3.9/site-packages/torch/serialization.py", line 713, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/Library/miniconda3/envs/ai/lib/python3.9/site-packages/torch/serialization.py", line 920, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, 'm'.`

Thank you for your help!

**Comment by hw-liang** [comment]
same error

**Comment by ChaitanyaKharche** [comment]
was this resolved?
if yes then how?

**Comment by sussyboiiii** [comment]
> was this resolved? if yes then how?

I can recommend ComfyUI to you. It's versatile and easy to work with.
