### ISSUE TITLE
ModuleNotFoundError: No module named 'imwatermark' (SD 1.5)

### ISSUE THREAD

**Issue by Owenonly** [CompVis/stable-diffusion#812]
Hi! How can I solve the problem 'ModuleNotFoundError: No module named 'imwatermark'' ? 
I have attepmted 'pip install invisible-watermark' through cmd already,but the Error still remains the same.
the following is the error message in texts

*** Error loading script: img2img.py
    Traceback (most recent call last):
      File "C:\Users\anchw\OneDrive\桌面\etc. etc\stable-diffusion-webui\modules\scripts.py", line 382, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "C:\Users\anchw\OneDrive\桌面\etc. etc\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "C:\Users\anchw\OneDrive\桌面\etc. etc\stable-diffusion-webui\extensions\stablediffusion\scripts\img2img.py", line 16, in <module>
        from imwatermark import WatermarkEncoder
    ModuleNotFoundError: No module named 'imwatermark'

---
*** Error loading script: txt2img.py
    Traceback (most recent call last):
      File "C:\Users\anchw\OneDrive\桌面\etc. etc\stable-diffusion-webui\modules\scripts.py", line 382, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "C:\Users\anchw\OneDrive\桌面\etc. etc\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "C:\Users\anchw\OneDrive\桌面\etc. etc\stable-diffusion-webui\extensions\stablediffusion\scripts\txt2img.py", line 14, in <module>
        from imwatermark import WatermarkEncoder
    ModuleNotFoundError: No module named 'imwatermark'

**Comment by KuiperGamesGithub** [comment]
Install with !pip install invisible-watermark will resolve the issue.
Tested.
