### ISSUE TITLE
ModuleNotFoundError: No module named 'ldm.util'; 'ldm' is not a package

### ISSUE THREAD

**Issue by zxk72** [CompVis/stable-diffusion#818]
When I run the command 
`python scripts/txt2img.py --prompt "a photograph of an astronaut riding a horse" --plms`, 
it returns an error:
Traceback (most recent call last):
  File "scripts/txt2img.py", line 17, in <module>
    from ldm.util import instantiate_from_config
ModuleNotFoundError: No module named 'ldm.util'; 'ldm' is not a package

**Comment by CreamyLong** [comment]
Did you “pip install -e .” ?

**Comment by Ontheroad123** [comment]
> When I run the command `python scripts/txt2img.py --prompt "a photograph of an astronaut riding a horse" --plms`, it returns an error: Traceback (most recent call last): File "scripts/txt2img.py", line 17, in from ldm.util import instantiate_from_config ModuleNotFoundError: No module named 'ldm.util'; 'ldm' is not a package

Add code in txt2img.py :
import sys 
sys.path.append('/***/stable-diffusion-master')

**Comment by samrat-boda** [comment]
```
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
if ROOT not in sys.path:
    sys.path.append(ROOT)
from ldm.util import instantiate_from_config
```
add this line in img2img.py above from ldm.util import instantiate_from_config
