### ISSUE TITLE
mian.py

### ISSUE THREAD

**Issue by kkkkuka** [CompVis/stable-diffusion#854]
Global seed set to 23
Traceback (most recent call last):
  File "E:\桌面\复现\stable-diffusion-main\main.py", line 535, in <module>
    model = instantiate_from_config(config.model)
                                    ^^^^^^^^^^^^
  File "E:\桌面\复现\stable-diffusion-main\venv\Lib\site-packages\omegaconf\dictconfig.py", line 355, in __getattr__
    self._format_and_raise(
  File "E:\桌面\复现\stable-diffusion-main\venv\Lib\site-packages\omegaconf\base.py", line 231, in _format_and_raise
    format_and_raise(
  File "E:\桌面\复现\stable-diffusion-main\venv\Lib\site-packages\omegaconf\_utils.py", line 899, in format_and_raise
    _raise(ex, cause)
  File "E:\桌面\复现\stable-diffusion-main\venv\Lib\site-packages\omegaconf\_utils.py", line 797, in _raise
    raise ex.with_traceback(sys.exc_info()[2])  # set env var OC_CAUSE=1 for full trace
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\桌面\复现\stable-diffusion-main\venv\Lib\site-packages\omegaconf\dictconfig.py", line 351, in __getattr__
    return self._get_impl(
           ^^^^^^^^^^^^^^^
  File "E:\桌面\复现\stable-diffusion-main\venv\Lib\site-packages\omegaconf\dictconfig.py", line 442, in _get_impl
    node = self._get_child(
           ^^^^^^^^^^^^^^^^
  File "E:\桌面\复现\stable-diffusion-main\venv\Lib\site-packages\omegaconf\basecontainer.py", line 73, in _get_child
    child = self._get_node(
            ^^^^^^^^^^^^^^^
  File "E:\桌面\复现\stable-diffusion-main\venv\Lib\site-packages\omegaconf\dictconfig.py", line 480, in _get_node
    raise ConfigKeyError(f"Missing key {key!s}")
omegaconf.errors.ConfigAttributeError: Missing key model
    full_key: model
    object_type=dict

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\桌面\复现\stable-diffusion-main\main.py", line 740, in <module>
    if trainer.global_rank == 0:
       ^^^^^^^
NameError: name 'trainer' is not defined. Did you mean: 'Trainer'?

**Comment by IwantNewway** [comment]
hi，do u solve it ?

**Comment by lisa264** [comment]
> 嗨，你解决了吗？
Does anyone fix this, ask for help

**Comment by IwantNewway** [comment]
> > 嗨，你解决了吗？
> > Does anyone fix this, ask for help
再输入的语法后面 加一个,

**Comment by lisa264** [comment]
> > > 嗨，你解决了吗？有人解决这个问题吗，寻求帮助再输入的语法后面 加一个，

D:\environment\Anaconda\envs\ldm\python.exe D:\environment\stable-diffusion\SD-CompVis\code\stable-diffusion\main.py 
Global seed set to 23
Traceback (most recent call last):
  File "D:\environment\stable-diffusion\SD-CompVis\code\stable-diffusion\main.py", line 541, in <module>
    print(config.model)
  File "D:\environment\Anaconda\envs\ldm\lib\site-packages\omegaconf\dictconfig.py", line 355, in __getattr__
    self._format_and_raise(
  File "D:\environment\Anaconda\envs\ldm\lib\site-packages\omegaconf\base.py", line 231, in _format_and_raise
    format_and_raise(
  File "D:\environment\Anaconda\envs\ldm\lib\site-packages\omegaconf\_utils.py", line 899, in format_and_raise
    _raise(ex, cause)
  File "D:\environment\Anaconda\envs\ldm\lib\site-packages\omegaconf\_utils.py", line 797, in _raise
    raise ex.with_traceback(sys.exc_info()[2])  # set env var OC_CAUSE=1 for full trace
  File "D:\environment\Anaconda\envs\ldm\lib\site-packages\omegaconf\dictconfig.py", line 351, in __getattr__
    return self._get_impl(
  File "D:\environment\Anaconda\envs\ldm\lib\site-packages\omegaconf\dictconfig.py", line 442, in _get_impl
    node = self._get_child(
  File "D:\environment\Anaconda\envs\ldm\lib\site-packages\omegaconf\basecontainer.py", line 73, in _get_child
    child = self._get_node(
  File "D:\environment\Anaconda\envs\ldm\lib\site-packages\omegaconf\dictconfig.py", line 480, in _get_node
    raise ConfigKeyError(f"Missing key {key!s}")
omegaconf.errors.ConfigAttributeError: Missing key model
    full_key: model
    object_type=dict

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\environment\stable-diffusion\SD-CompVis\code\stable-diffusion\main.py", line 748, in <module>
    if trainer.global_rank == 0:
NameError: name 'trainer' is not defined        This problem?
