### ISSUE TITLE
PytorchStreamReader failed reading zip archive: failed finding central directory

### ISSUE THREAD

**Issue by SnowConure** [CompVis/stable-diffusion#93]
after trying to run txt2img.py in the environment, I get this error. any ideas?

`Traceback (most recent call last):
  File "scripts/txt2img.py", line 344, in <module>
    main()
  File "scripts/txt2img.py", line 240, in main
    model = load_model_from_config(config, f"{opt.ckpt}")
  File "scripts/txt2img.py", line 50, in load_model_from_config
    pl_sd = torch.load(ckpt, map_location="cpu")
  File "C:\Users\Simon\anaconda3\envs\ldm\lib\site-packages\torch\serialization.py", line 705, in load
    with _open_zipfile_reader(opened_file) as opened_zipfile:
  File "C:\Users\Simon\anaconda3\envs\ldm\lib\site-packages\torch\serialization.py", line 243, in __init__
    super(_open_zipfile_reader, self).__init__(torch._C.PyTorchFileReader(name_or_buffer))
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory`

**Comment by cissoidx** [comment]
same here

**Comment by SnowConure** [comment]
For anyone with this issue, what worked for me was simply redownloading the model again...

**Comment by rjamesnw** [comment]
For me, it turned out I copied `sd-v1-4-full-ema.ckpt` instead of `sd-v1-4.ckpt`. Using the latter fixed the issue.
